begin;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  category text,
  equipment text,
  image_path text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table public.training_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  description text,
  version integer not null default 1 check (version > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name, version)
);

create table public.plan_workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_id bigint not null references public.training_plans(id) on delete cascade,
  code text not null,
  title text not null,
  sequence_number integer not null check (sequence_number > 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_id, sequence_number),
  unique (plan_id, code),
  unique (id, user_id)
);

create table public.plan_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_workout_id bigint not null,
  exercise_id bigint not null,
  position integer not null check (position > 0),
  target_sets integer not null check (target_sets > 0),
  min_reps integer check (min_reps is null or min_reps >= 0),
  max_reps integer check (max_reps is null or max_reps >= min_reps),
  rest_seconds integer check (rest_seconds is null or rest_seconds >= 0),
  failure_rule text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_workout_id, position),
  foreign key (plan_workout_id, user_id) references public.plan_workouts(id, user_id) on delete cascade,
  foreign key (exercise_id) references public.exercises(id)
);

create table public.exercise_alternatives (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary_exercise_id bigint not null references public.exercises(id) on delete cascade,
  alternative_exercise_id bigint not null references public.exercises(id) on delete cascade,
  priority integer not null default 1 check (priority > 0),
  notes text,
  created_at timestamptz not null default now(),
  unique (user_id, primary_exercise_id, alternative_exercise_id),
  check (primary_exercise_id <> alternative_exercise_id)
);

create table public.user_plan_state (
  user_id uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  active_plan_id bigint references public.training_plans(id) on delete set null,
  next_plan_workout_id bigint,
  open_workout_id bigint,
  preferred_weekdays smallint[] not null default '{}',
  minimum_rest_hours integer not null default 24 check (minimum_rest_hours >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (next_plan_workout_id, user_id) references public.plan_workouts(id, user_id)
);

create table public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  plan_id bigint references public.training_plans(id) on delete set null,
  plan_workout_id bigint,
  workout_date date not null default current_date,
  status text not null default 'planned' check (status in ('planned','started','completed','discarded')),
  started_at timestamptz,
  finished_at timestamptz,
  title text,
  body_weight_kg numeric(5,2) check (body_weight_kg is null or body_weight_kg >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  foreign key (plan_workout_id, user_id) references public.plan_workouts(id, user_id)
);

alter table public.user_plan_state
  add constraint user_plan_state_open_workout_fk
  foreign key (open_workout_id, user_id) references public.workouts(id, user_id);

create table public.workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workout_id bigint not null,
  exercise_id bigint not null references public.exercises(id),
  set_number integer not null check (set_number > 0),
  weight_kg numeric(6,2) check (weight_kg is null or weight_kg >= 0),
  repetitions integer check (repetitions is null or repetitions >= 0),
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  distance_meters numeric(8,2) check (distance_meters is null or distance_meters >= 0),
  rir numeric(3,1) check (rir is null or rir >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workout_id, exercise_id, set_number),
  foreign key (workout_id, user_id) references public.workouts(id, user_id) on delete cascade
);

create table public.body_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  measurement_date date not null default current_date,
  weight_kg numeric(5,2) check (weight_kg is null or weight_kg >= 0),
  body_fat_percent numeric(4,1) check (body_fat_percent is null or body_fat_percent between 0 and 100),
  waist_cm numeric(5,1) check (waist_cm is null or waist_cm >= 0),
  chest_cm numeric(5,1) check (chest_cm is null or chest_cm >= 0),
  upper_arm_cm numeric(5,1) check (upper_arm_cm is null or upper_arm_cm >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, measurement_date)
);

create index exercises_user_id_idx on public.exercises(user_id);
create index plans_user_id_idx on public.training_plans(user_id);
create index plan_workouts_plan_id_idx on public.plan_workouts(plan_id);
create index plan_exercises_workout_idx on public.plan_exercises(plan_workout_id);
create index workouts_user_date_idx on public.workouts(user_id, workout_date desc);
create index workout_sets_workout_idx on public.workout_sets(workout_id);
create index workout_sets_exercise_idx on public.workout_sets(exercise_id);
create index measurements_user_date_idx on public.body_measurements(user_id, measurement_date desc);

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger exercises_updated_at before update on public.exercises for each row execute function public.set_updated_at();
create trigger plans_updated_at before update on public.training_plans for each row execute function public.set_updated_at();
create trigger plan_workouts_updated_at before update on public.plan_workouts for each row execute function public.set_updated_at();
create trigger plan_exercises_updated_at before update on public.plan_exercises for each row execute function public.set_updated_at();
create trigger plan_state_updated_at before update on public.user_plan_state for each row execute function public.set_updated_at();
create trigger workouts_updated_at before update on public.workouts for each row execute function public.set_updated_at();
create trigger workout_sets_updated_at before update on public.workout_sets for each row execute function public.set_updated_at();
create trigger measurements_updated_at before update on public.body_measurements for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.training_plans enable row level security;
alter table public.plan_workouts enable row level security;
alter table public.plan_exercises enable row level security;
alter table public.exercise_alternatives enable row level security;
alter table public.user_plan_state enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_sets enable row level security;
alter table public.body_measurements enable row level security;

do $$
declare t text;
begin
  foreach t in array array['profiles','exercises','training_plans','plan_workouts','plan_exercises','exercise_alternatives','user_plan_state','workouts','workout_sets','body_measurements']
  loop
    execute format('create policy %I on public.%I for select to authenticated using (auth.uid() = %s)', t || '_select_own', t, case when t='profiles' then 'id' else 'user_id' end);
    execute format('create policy %I on public.%I for insert to authenticated with check (auth.uid() = %s)', t || '_insert_own', t, case when t='profiles' then 'id' else 'user_id' end);
    execute format('create policy %I on public.%I for update to authenticated using (auth.uid() = %s) with check (auth.uid() = %s)', t || '_update_own', t, case when t='profiles' then 'id' else 'user_id' end, case when t='profiles' then 'id' else 'user_id' end);
    execute format('create policy %I on public.%I for delete to authenticated using (auth.uid() = %s)', t || '_delete_own', t, case when t='profiles' then 'id' else 'user_id' end);
  end loop;
end $$;

commit;
