import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const SNAP='gym-snapshot-v6',ACTIVE='gym-active-v6',QUEUE='gym-queue-v6',THEME='gym-theme';
const $=s=>document.querySelector(s);
let session=null,snapshot=null,currentCode='A',viewed=new Date(),selectedSchedule=null,timerInterval=null;
const els={loading:$('#loading'),login:$('#login-screen'),dashboard:$('#dashboard'),form:$('#login-form'),error:$('#login-error'),calendar:$('#calendar-grid'),calendarTitle:$('#calendar-title'),calendarHelp:$('#calendar-help'),next:$('#next-workout'),nextDate:$('#next-date'),connection:$('#connection-status'),list:$('#workout-list'),completed:$('#completed-count'),week:$('#week-count'),streak:$('#streak-count'),dialog:$('#workout-dialog'),dialogTitle:$('#dialog-title'),exercises:$('#exercise-list'),timer:$('#workout-timer'),timerToggle:$('#timer-toggle'),complete:$('#complete-workout'),completionHint:$('#completion-hint'),toast:$('#toast'),weightDialog:$('#weight-dialog'),weightInput:$('#weight-input'),weightStatus:$('#weight-status')};
const iso=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d);
const pd=v=>new Date(`${v}T12:00:00`);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const notify=m=>{els.toast.textContent=m;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2400)};
const showOnly=el=>{[els.loading,els.login,els.dashboard].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')};

async function loadRemote(){
 const {data:plans,error:pErr}=await supabase.from('training_plans').select('id,name,goal,version').eq('is_active',true).order('version',{ascending:false}).limit(1); if(pErr)throw pErr;if(!plans?.length)throw new Error('Kein aktiver Plan');
 const plan=plans[0];
 const {data:pws,error:wErr}=await supabase.from('plan_workouts').select('id,code,title,focus,sequence_position').eq('plan_id',plan.id).order('sequence_position');if(wErr)throw wErr;
 const pwIds=pws.map(x=>x.id);
 const {data:pes,error:peErr}=await supabase.from('plan_exercises').select('id,plan_workout_id,exercise_id,exercise_order,target_sets,rep_min,rep_max,rest_seconds,instructions,failure_rule,is_core_exercise').in('plan_workout_id',pwIds).order('exercise_order');if(peErr)throw peErr;
 const exIds=[...new Set(pes.map(x=>x.exercise_id))];
 const {data:exs,error:eErr}=await supabase.from('exercises').select('id,name,image_path,equipment').in('id',exIds);if(eErr)throw eErr;
 const exMap=Object.fromEntries(exs.map(x=>[x.id,x]));
 const workouts={};for(const w of pws){workouts[w.code]={...w,exercises:pes.filter(x=>x.plan_workout_id===w.id).map(pe=>({...pe,name:exMap[pe.exercise_id]?.name||'Übung',image_path:exMap[pe.exercise_id]?.image_path||null,equipment:exMap[pe.exercise_id]?.equipment||''}))};}
 const [{data:schedule,error:sErr},{data:done,error:dErr},{data:weights,error:wiErr}]=await Promise.all([
  supabase.from('scheduled_workouts').select('id,plan_workout_id,scheduled_date,status').order('scheduled_date'),
  supabase.from('workouts').select('id,plan_workout_id,workout_date,status').in('status',['completed','partial']).order('workout_date',{ascending:false}).limit(100),
  supabase.from('weigh_ins').select('id,measured_at,weight_kg').order('measured_at',{ascending:false}).limit(1)
 ]);if(sErr)throw sErr;if(dErr)throw dErr;if(wiErr)throw wiErr;
 const codeById=Object.fromEntries(pws.map(x=>[x.id,x.code]));
 snapshot={plan,workouts,schedule:(schedule||[]).map(x=>({id:x.id,plan_workout_id:x.plan_workout_id,date:x.scheduled_date,status:x.status,code:codeById[x.plan_workout_id]||'?'})),completed:(done||[]).map(x=>({id:x.id,date:x.workout_date,status:x.status,code:codeById[x.plan_workout_id]||'?'})),latestWeight:weights?.[0]||null};
 write(SNAP,snapshot);return snapshot;
}
function loadCached(){snapshot=read(SNAP,null);return snapshot}
function weekKey(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const ys=new Date(Date.UTC(d.getUTCFullYear(),0,1));return `${d.getUTCFullYear()}-${Math.ceil((((d-ys)/86400000)+1)/7)}`}
function stats(){const c=snapshot?.completed||[];els.completed.textContent=c.length;els.week.textContent=c.filter(x=>weekKey(pd(x.date))===weekKey(new Date())).length;const weeks=[...new Set(c.map(x=>weekKey(pd(x.date))))];let s=0,d=new Date();while(weeks.includes(weekKey(d))){s++;d.setDate(d.getDate()-7)}els.streak.textContent=s}
function renderPlans(){els.list.innerHTML=Object.values(snapshot?.workouts||{}).sort((a,b)=>a.sequence_position-b.sequence_position).map(w=>`<article class="workout-card"><p class="eyebrow">EINHEIT ${w.code}</p><h3>${w.title}</h3><p class="muted">${w.focus||''}</p><div class="workout-meta"><span>${w.exercises.length} Übungen</span></div><button data-workout="${w.code}">Plan ansehen</button></article>`).join('')}
function renderCalendar(){if(!snapshot)return;const y=viewed.getFullYear(),m=viewed.getMonth();els.calendarTitle.textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(viewed);const first=new Date(y,m,1),off=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),done=new Map(snapshot.completed.map(x=>[x.date,x])),planned=new Map(snapshot.schedule.map((x,i)=>[x.date,{...x,index:i}])),cells=[];for(let i=0;i<off;i++)cells.push('<span class="calendar-day empty"></span>');for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,a=done.get(date),p=planned.get(date),cl=['calendar-day'];if(date===iso())cl.push('today');if(a)cl.push('completed');else if(p)cl.push('planned');if(p?.index===selectedSchedule)cl.push('selected');cells.push(`<button class="${cl.join(' ')}" data-date="${date}"><span>${d}</span>${a?`<small class="plan-badge">${a.code} ✓</small>`:p?`<small class="plan-badge">${p.code}</small>`:''}</button>`)}els.calendar.innerHTML=cells.join('')}
function refresh(){if(!snapshot)return;const next=snapshot.schedule.find(x=>['planned','confirmed','started'].includes(x.status));els.next.textContent=next?`Training ${next.code}`:'Training planen';els.nextDate.textContent=next?new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(pd(next.date)):'Kein Termin vorhanden';$('#latest-weight').textContent=snapshot.latestWeight?`${Number(snapshot.latestWeight.weight_kg).toFixed(1)} kg`:'Noch kein Gewicht';renderPlans();stats();renderCalendar();setConnection()}
function setConnection(){const q=read(QUEUE,[]).length;els.connection.textContent=navigator.onLine?(q?`Online · ${q} offen`:'Online'):(q?`Offline · ${q} offen`:'Offline')}
function getActive(){return read(ACTIVE,null)}function saveActive(v){v?write(ACTIVE,v):localStorage.removeItem(ACTIVE)}function elapsed(a){return a?(a.elapsed_ms||0)+(a.running_since?Date.now()-a.running_since:0):0}
function renderTimer(){const a=getActive(),s=Math.floor(elapsed(a)/1000);els.timer.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;els.timerToggle.textContent=a?.running_since?'Pause':'Training starten'}
function openWorkout(code){const w=snapshot?.workouts?.[code];if(!w){notify('Trainingsplan konnte nicht geöffnet werden.');return}currentCode=code;els.dialogTitle.textContent=w.title;const a=getActive(),states=a?.code===code?a.states||{}:{};els.exercises.innerHTML=w.exercises.map(ex=>`<article class="exercise-card ${states[ex.id]||''}" data-exercise-id="${ex.id}"><div class="exercise-image">${ex.image_path?`<img src="${ex.image_path}" alt="${ex.name}">`:'Gerätebild folgt'}</div><div class="exercise-body"><h3>${ex.name}</h3><p class="exercise-prescription">${ex.target_sets} × ${ex.rep_min||''}${ex.rep_max?`–${ex.rep_max}`:''} · ${ex.rest_seconds||0} Sek.</p><p class="exercise-notes">${ex.instructions||''}</p><div class="exercise-actions"><button class="mark-done">Erledigt</button><button class="skip">Nicht geschafft</button></div></div></article>`).join('');updateCompletion();renderTimer();els.dialog.showModal()}
function ensureActive(){let a=getActive();if(!a||a.code!==currentCode)a={id:crypto.randomUUID(),code:currentCode,date:iso(),elapsed_ms:0,running_since:null,states:{}};saveActive(a);return a}
function toggleTimer(){const a=ensureActive();if(a.running_since){a.elapsed_ms+=Date.now()-a.running_since;a.running_since=null}else a.running_since=Date.now();saveActive(a);renderTimer()}
function setState(id,state){const a=ensureActive();a.states[id]=a.states[id]===state?null:state;saveActive(a);const card=els.exercises.querySelector(`[data-exercise-id="${id}"]`);card.classList.toggle('done',a.states[id]==='done');card.classList.toggle('skipped',a.states[id]==='skipped');updateCompletion()}
function updateCompletion(){const w=snapshot?.workouts?.[currentCode];if(!w)return;const a=getActive(),states=a?.code===currentCode?a.states||{}:{};const n=w.exercises.filter(ex=>['done','skipped'].includes(states[ex.id])).length;els.complete.disabled=n!==w.exercises.length;els.completionHint.textContent=`${n} von ${w.exercises.length} Übungen bewertet`}
async function saveCompletion(payload){const w=snapshot.workouts[payload.code],scheduled=snapshot.schedule.find(x=>x.code===payload.code&&['planned','confirmed','started'].includes(x.status));const status=Object.values(payload.states).includes('skipped')?'partial':'completed';const {data:row,error}=await supabase.from('workouts').insert({user_id:session.user.id,plan_id:snapshot.plan.id,plan_workout_id:w.id,scheduled_workout_id:scheduled?.id||null,workout_date:payload.date,started_at:payload.started_at,finished_at:payload.finished_at,elapsed_seconds:payload.elapsed_seconds,status}).select('id').single();if(error)throw error;const rows=w.exercises.map((ex,i)=>({user_id:session.user.id,workout_id:row.id,plan_exercise_id:ex.id,exercise_id:ex.exercise_id,exercise_order:i+1,status:payload.states[ex.id]==='done'?'completed':'skipped'}));const {error:e}=await supabase.from('workout_exercises').insert(rows);if(e)throw e;if(scheduled)await supabase.from('scheduled_workouts').update({status:'completed'}).eq('id',scheduled.id)}
async function completeWorkout(){const a=getActive(),w=snapshot.workouts[currentCode];if(!a||a.code!==currentCode)return;if(!w.exercises.every(ex=>['done','skipped'].includes(a.states[ex.id]))){notify('Bitte jede Übung bewerten.');return}if(a.running_since){a.elapsed_ms+=Date.now()-a.running_since;a.running_since=null}const p={...a,started_at:new Date(Date.now()-a.elapsed_ms).toISOString(),finished_at:new Date().toISOString(),elapsed_seconds:Math.round(a.elapsed_ms/1000)};try{if(!navigator.onLine)throw new Error('offline');await saveCompletion(p);saveActive(null);els.dialog.close();await loadRemote();refresh();notify('Training gespeichert.')}catch{const q=read(QUEUE,[]);q.push({type:'complete',payload:p});write(QUEUE,q);saveActive(null);els.dialog.close();snapshot.completed.push({id:p.id,date:p.date,code:p.code,status:Object.values(p.states).includes('skipped')?'partial':'completed'});refresh();notify('Lokal gespeichert. Synchronisierung folgt.') }}
async function moveSchedule(index,date){const item=snapshot.schedule[index];if(!item)return;const {error}=await supabase.from('scheduled_workouts').update({scheduled_date:date}).eq('id',item.id);if(error)throw error;await loadRemote();refresh()}
async function saveWeight(){const val=Number(String(els.weightInput.value).replace(',','.'));if(!val||val<30||val>300){els.weightStatus.textContent='Bitte gültiges Gewicht eingeben.';return}const {error}=await supabase.from('weigh_ins').insert({user_id:session.user.id,weight_kg:val,toilet_status:$('#weight-toilet').value,food_status:$('#weight-food').value,late_meal:$('#weight-late').value,unusual_time:$('#weight-unusual').checked,trained_previous_day:$('#weight-trained').checked});if(error){els.weightStatus.textContent='Speichern fehlgeschlagen.';return}els.weightDialog.close();await loadRemote();refresh();notify('Gewicht gespeichert.')}
async function syncQueue(){if(!navigator.onLine||!session)return;const q=read(QUEUE,[]),rest=[];for(const op of q){try{if(op.type==='complete')await saveCompletion(op.payload)}catch{rest.push(op)}}write(QUEUE,rest);setConnection();if(rest.length!==q.length){await loadRemote();refresh()}}
async function boot(){document.documentElement.dataset.theme=localStorage.getItem(THEME)||'light';if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});const {data:{session:s}}=await supabase.auth.getSession();session=s;if(!session){showOnly(els.login);return}showOnly(els.loading);try{await loadRemote()}catch(err){console.error(err);loadCached();if(!snapshot){els.error.textContent='Plan konnte nicht geladen werden. Bitte Seite neu laden.';showOnly(els.login);return}notify('Offline-Stand geladen.')}showOnly(els.dashboard);refresh();timerInterval=setInterval(renderTimer,1000);syncQueue()}

els.form.addEventListener('submit',async e=>{e.preventDefault();els.error.textContent='';const {data,error}=await supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){els.error.textContent='Anmeldung fehlgeschlagen.';return}session=data.session;await boot()});
$('#logout').onclick=async()=>{await supabase.auth.signOut();session=null;showOnly(els.login)};
$('#theme-toggle').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem(THEME,t)};
$('#start-workout').onclick=()=>{const next=snapshot?.schedule.find(x=>['planned','confirmed','started'].includes(x.status));openWorkout(next?.code||'A')};
els.list.onclick=e=>{const b=e.target.closest('[data-workout]');if(b)openWorkout(b.dataset.workout)};
$('#close-dialog').onclick=()=>els.dialog.close();els.timerToggle.onclick=toggleTimer;els.complete.onclick=completeWorkout;
els.exercises.onclick=e=>{const c=e.target.closest('.exercise-card');if(!c)return;if(e.target.closest('.mark-done'))setState(c.dataset.exerciseId,'done');if(e.target.closest('.skip'))setState(c.dataset.exerciseId,'skipped')};
els.calendar.onclick=async e=>{const b=e.target.closest('[data-date]');if(!b)return;const date=b.dataset.date,idx=snapshot.schedule.findIndex(x=>x.date===date);if(selectedSchedule===null){if(idx>=0){selectedSchedule=idx;els.calendarHelp.textContent=`Training ${snapshot.schedule[idx].code} gewählt. Jetzt neuen Tag antippen.`;renderCalendar()}else{try{await moveSchedule(0,date);notify('Nächstes Training verschoben.')}catch{notify('Verschieben fehlgeschlagen.')}}}else{try{await moveSchedule(selectedSchedule,date);selectedSchedule=null;els.calendarHelp.textContent='Geplante Einheit antippen und danach den neuen Tag.';notify('Termin verschoben.')}catch{notify('Verschieben fehlgeschlagen.')}}};
$('#prev-month').onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()-1,1);renderCalendar()};$('#next-month').onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()+1,1);renderCalendar()};
$('#open-weight').onclick=()=>{els.weightStatus.textContent='';els.weightDialog.showModal();setTimeout(()=>els.weightInput.focus(),100)};$('#close-weight').onclick=()=>els.weightDialog.close();$('#save-weight').onclick=saveWeight;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${b.dataset.tab}`))});
window.addEventListener('online',()=>{setConnection();syncQueue()});window.addEventListener('offline',setConnection);supabase.auth.onAuthStateChange((_e,s)=>{session=s;if(!s)showOnly(els.login)});boot();