import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const SNAP='gym-snapshot-v11', ACTIVE='gym-active-workout-v11', DRAFT='gym-v53-draft';
const DEVICE_DRAFT='gym-v55-device-draft', HISTORY='gym-v55-device-history';
const HISTORY_STAMP='gym-v55-history-stamp', MIGRATION='gym-v55-device-model';
const OFFLINE='gym-offline-v11', EDIT='gym-v53-edit';
let restoring=false, historyPromise=null, moveItem=null;

const canon=v=>String(v||'').toLowerCase().replaceAll('ä','a').replaceAll('ö','o').replaceAll('ü','u').replaceAll('ß','ss').replace(/[^a-z0-9]+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
const fmt=v=>num(v)==null?'–':num(v).toLocaleString('de-DE',{maximumFractionDigits:2});
const meaningful=s=>Boolean(String(s?.weight??'').trim()||String(s?.reps??'').trim()||String(s?.rir??'').trim()||s?.warmup);

const VARIANTS={
 'Schrägbankdrückmaschine dual':['Schrägbankdrückmaschine dual','Schrägbankmaschine sitzend','Kurzhantel Schrägbankdrücken','Bankdrückmaschine sitzend dual'],
 'Kurzhantel-Schrägbankdrücken':['Kurzhantel Schrägbankdrücken','Schrägbankdrückmaschine dual','Schrägbankmaschine sitzend'],
 'Kurzhantel Schrägbankdrücken':['Kurzhantel Schrägbankdrücken','Schrägbankdrückmaschine dual','Schrägbankmaschine sitzend'],
 'Brustpresse sitzend':['Brustpresse sitzend','Bankdrückmaschine sitzend dual','Bankdrückmaschine liegend dual'],
 'Butterfly mit Griffen':['Butterfly mit Griffen','Butterfly mit Pads'],
 'Seithebemaschine ohne Armpolster':['Seithebemaschine ohne Armpolster','Seithebemaschine dual ohne Armpolster','Kurzhantel Seitheben sitzend','Kurzhantel Seitheben stehend'],
 'Trizepsmaschine Überkopf':['Trizepsmaschine über Kopf','Trizepsmaschine horizontal','Trizeps Dip Maschine sitzend dual'],
 'Trizepsmaschine über Kopf':['Trizepsmaschine über Kopf','Trizepsmaschine horizontal','Trizeps Dip Maschine sitzend dual'],
 'Bizepsmaschine':['Bizepsmaschine','Bizepsmaschine Plate loaded','Scott Curler sitzend'],
 'Bauchmuskelmaschine':['Bauchmuskelmaschine','Bauchmuskelmaschine Crunch liegend','Klappsitz Bauchmaschine sitzend','Klappsitz Bauchmaschine liegend, Plate loaded'],
 'Latzugstation mit Oberschenkelpolster':['Latzugstation mit Oberschenkelpolster','Rückenzugmaschine dual','High Row dual'],
 'Rudermaschine mit Brustpolster':['Rudermaschine mit Brustpolster','Low Row dual','High Row dual'],
 'High Row dual':['High Row dual','Rückenzugmaschine dual','Rudermaschine mit Brustpolster'],
 'Low Row dual':['Low Row dual','Rudermaschine mit Brustpolster','High Row dual'],
 'Butterfly reverse mit Griffen':['Butterfly reverse mit Griffen','Butterfly reverse mit Pads'],
 'Rückenstreckermaschine':['Rückenstreckermaschine']
};

function loadCss(){const href='css/app-v55.css';if(q(`link[href="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link)}
function snapshot(){return read(SNAP,{workouts:{},schedule:[]})}
function exerciseKey(ex,i){return String(ex?.id||ex?.plan_exercise_id||`${i}:${ex?.name||'Übung'}`)}
function card(){return q('#workout-dialog.workout-v53 .training-exercise-v53')}
function context(){const c=card();if(!c)return null;return {card:c,code:c.dataset.codeV53||read(ACTIVE,null)?.code,key:c.dataset.exKeyV53,index:Number(c.dataset.exIndexV53),device:q('.device-nav-v53 strong',c)?.textContent.trim()||''}}
function planExercise(ctx){return (snapshot().workouts?.[ctx.code]?.exercises||[]).find((ex,i)=>exerciseKey(ex,i)===ctx.key)||null}
function variantNames(ex){return VARIANTS[ex?.name]||[ex?.name].filter(Boolean)}
function rows(c=card()){return qa('.set-row-v53',c).map(r=>({weight:q('[data-field-v53="weight"]',r)?.value||'',reps:q('[data-field-v53="reps"]',r)?.value||'',rir:q('[data-field-v53="rir"]',r)?.value||'',warmup:Boolean(q('[data-field-v53="warmup"]',r)?.checked)}))}
function exactHistory(name){const all=read(HISTORY,{});return all[name]||Object.entries(all).find(([n])=>canon(n)===canon(name))?.[1]||null}
function workSets(row){return (row?.sets||[]).filter(s=>!s.warmup&&num(s.weight)!=null&&num(s.reps)!=null)}
function deviceDraft(ctx,name){return read(DEVICE_DRAFT,{})?.[ctx.code]?.[ctx.key]?.[canon(name)]||null}
function saveDevice(ctx,sets=rows(ctx.card)){if(restoring||!ctx?.device)return;const all=read(DEVICE_DRAFT,{});all[ctx.code]??={};all[ctx.code][ctx.key]??={};all[ctx.code][ctx.key][canon(ctx.device)]={device:ctx.device,sets,updatedAt:new Date().toISOString()};write(DEVICE_DRAFT,all)}
function source(ctx,name,count){const own=deviceDraft(ctx,name)?.sets,history=workSets(exactHistory(name)),base=own?.some(meaningful)?own:history;if(!base?.length)return Array.from({length:Math.max(1,count)},()=>({weight:'',reps:'',rir:'',warmup:false}));return Array.from({length:Math.max(count,base.length)},(_,i)=>{const s=base[i]||base.at(-1);return {weight:s?.weight??'',reps:s?.reps??'',rir:s?.rir??'',warmup:Boolean(s?.warmup)}})}
function writeLegacy(ctx,sets,index){const all=read(DRAFT,{});all[ctx.code]??={};const old=all[ctx.code][ctx.key]||{};all[ctx.code][ctx.key]={...old,variantIndex:index??old.variantIndex??0,status:old.status||'pending',sets};write(DRAFT,all)}
function sanitize(){if(localStorage.getItem(MIGRATION)==='done'||read(EDIT,null))return;const all=read(DRAFT,{});for(const entries of Object.values(all))for(const [key,state] of Object.entries(entries||{}))if(!key.startsWith('__'))entries[key]={...state,sets:[]};write(DRAFT,all);localStorage.setItem(MIGRATION,'done');localStorage.removeItem('gym-v54-history-stamp')}
function setField(input,value,type='input'){if(!input)return;if(input.type==='checkbox')input.checked=Boolean(value);else input.value=value??'';input.dispatchEvent(new Event(type,{bubbles:true}))}
function restore(){const ctx=context();if(!ctx?.device)return;const domRows=qa('.set-row-v53',ctx.card),sets=source(ctx,ctx.device,domRows.length);restoring=true;try{domRows.forEach((r,i)=>{const s=sets[i]||{};setField(q('[data-field-v53="weight"]',r),s.weight);setField(q('[data-field-v53="reps"]',r),s.reps);setField(q('[data-field-v53="rir"]',r),s.rir);setField(q('[data-field-v53="warmup"]',r),s.warmup,'change')})}finally{restoring=false}const current=read(DRAFT,{})?.[ctx.code]?.[ctx.key];writeLegacy(ctx,sets,current?.variantIndex);saveDevice(ctx,sets);renderDevices(ctx);renderCoach(ctx);renderPrefill(ctx)}
function summary(name){const h=exactHistory(name),sets=workSets(h);if(!sets.length)return {used:false,text:'Noch nicht verwendet'};const date=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit'}).format(new Date(`${h.date}T12:00:00`));return {used:true,text:`${date} · ${sets.map(s=>`${fmt(s.weight)}×${s.reps}`).join(' · ')}`}}
function renderDevices(ctx){const ex=planExercise(ctx),nav=q('.device-nav-v53',ctx.card);if(!ex||!nav)return;let strip=q('.device-history-v55',ctx.card);if(!strip){strip=document.createElement('div');strip.className='device-history-v55';nav.insertAdjacentElement('afterend',strip)}strip.innerHTML=variantNames(ex).map((name,i)=>{const s=summary(name),active=canon(name)===canon(ctx.device);return `<button type="button" class="${active?'active':''} ${s.used?'used':'unused'}" data-device-index-v55="${i}"><strong>${esc(name)}</strong><span>${esc(s.text)}</span></button>`}).join('')}
function range(ctx){const t=q('.exercise-title-v53 p',ctx.card)?.textContent||'',m=t.match(/(\d+)\s*[–-]\s*(\d+)/);return m?{min:Number(m[1]),max:Number(m[2])}:{min:8,max:12}}
function coachRows(ctx){const sets=workSets(exactHistory(ctx.device));if(!sets.length)return [];const r=range(ctx),highest=Math.max(...sets.map(s=>num(s.weight)||0));return sets.map((s,i)=>{const weight=num(s.weight),reps=num(s.reps),rir=num(s.rir);let target=reps,note;if(weight<highest&&i===0)note='Einstiegssatz halten';else if(rir===0)note='Gleiches Gewicht und gleiche Wiederholungen, diesmal etwa RIR 1 statt Muskelversagen';else if(reps<r.max){target=Math.min(r.max,reps+1);note='Eine saubere Wiederholung mehr, Ziel RIR 1–2'}else note='Oberes Ziel erreicht; erst bei erneut stabiler Ausführung den nächsten Gewichtsschritt testen';return {weight,reps,rir,target,note}})}
function renderCoach(ctx){const box=q('.coach-card-v53',ctx.card);if(!box)return;const data=coachRows(ctx);if(!data.length){box.innerHTML=`<div class="coach-label-v55"><span>COACH</span><strong>Neue Gerätereferenz</strong></div><p class="coach-empty-v55">Für <b>${esc(ctx.device)}</b> gibt es noch keine eigenen Werte. Andere Gerätewerte werden nicht übertragen.</p>`;return}box.innerHTML=`<div class="coach-label-v55"><span>COACH · ${esc(ctx.device)}</span><strong>Vorgabe je Satz</strong></div><div class="coach-sets-v55">${data.map((s,i)=>`<article><span>Satz ${i+1}</span><div><small>Zuletzt</small><strong>${fmt(s.weight)} kg × ${s.reps}${s.rir==null?'':` · RIR ${s.rir}`}</strong></div><div><small>Heute</small><strong>${fmt(s.weight)} kg × ${s.target}</strong><p>${esc(s.note)}</p></div></article>`).join('')}</div><p class="coach-foot-v55">Warm-up-Sätze werden nicht für Coach oder Progression gewertet.</p>`}
function renderPrefill(ctx){const tracking=q('.tracking-card-v53',ctx.card);if(!tracking)return;let p=q('.prefill-badge-v55',tracking);if(!p){p=document.createElement('p');p.className='prefill-badge-v55';tracking.prepend(p)}const h=exactHistory(ctx.device);p.textContent=h?`Vorbelegt aus dem Training vom ${new Intl.DateTimeFormat('de-DE').format(new Date(`${h.date}T12:00:00`))}.`:'Für dieses Gerät gibt es noch keine gespeicherten Werte.';p.classList.toggle('empty',!h)}
function chooseVariant(index){const ctx=context();if(!ctx)return;saveDevice(ctx);const names=variantNames(planExercise(ctx)),target=Math.max(0,Math.min(index,names.length-1)),sets=source(ctx,names[target],qa('.set-row-v53',ctx.card).length);writeLegacy(ctx,sets,target);(q('#workout-dialog .overview-item-v53.active')||q('#workout-dialog [data-select-ex-v53]'))?.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));setTimeout(restore,70)}
function propagate(event){if(restoring||!event.isTrusted)return;const input=event.target.closest('#workout-dialog.workout-v53 [data-field-v53="weight"],#workout-dialog.workout-v53 [data-field-v53="reps"],#workout-dialog.workout-v53 [data-field-v53="rir"]');if(!input)return;const row=input.closest('.set-row-v53');if(q('[data-field-v53="warmup"]',row)?.checked)return;const list=qa('.set-row-v53',input.closest('.sets-v53')),start=list.indexOf(row);restoring=true;try{for(let i=start+1;i<list.length;i++){if(q('[data-field-v53="warmup"]',list[i])?.checked)continue;const target=q(`[data-field-v53="${input.dataset.fieldV53}"]`,list[i]);if(target&&!String(target.value).trim())setField(target,input.value)}}finally{restoring=false}saveDevice(context())}
async function hydrate({force=false}={}){if(!navigator.onLine||localStorage.getItem(OFFLINE)==='1')return;const stamp=Number(localStorage.getItem(HISTORY_STAMP)||0);if(!force&&Date.now()-stamp<30000)return;if(historyPromise)return historyPromise;historyPromise=(async()=>{try{const {data:{session},error}=await supabase.auth.getSession();if(error||!session)return;const w=await supabase.from('workouts').select('id,workout_date,created_at').eq('user_id',session.user.id).in('status',['completed','partial']).order('workout_date',{ascending:false}).order('created_at',{ascending:false}).limit(60);if(w.error||!w.data?.length)return;const ids=w.data.map(x=>x.id),dates=Object.fromEntries(w.data.map(x=>[x.id,x.workout_date])),rank=Object.fromEntries(w.data.map((x,i)=>[x.id,i]));const we=await supabase.from('workout_exercises').select('id,workout_id,exercise_id').in('workout_id',ids);if(we.error||!we.data?.length)return;const exIds=[...new Set(we.data.map(x=>x.exercise_id).filter(Boolean))],names=exIds.length?await supabase.from('exercises').select('id,name').in('id',exIds):{data:[],error:null};if(names.error)return;const nameMap=Object.fromEntries((names.data||[]).map(x=>[x.id,x.name]));const sets=await supabase.from('workout_sets').select('workout_exercise_id,set_number,weight_kg,repetitions,rir,notes').in('workout_exercise_id',we.data.map(x=>x.id)).order('set_number');if(sets.error)return;const latest={};for(const row of [...we.data].sort((a,b)=>(rank[a.workout_id]??999)-(rank[b.workout_id]??999))){const name=nameMap[row.exercise_id];if(!name||Object.keys(latest).some(n=>canon(n)===canon(name)))continue;const values=sets.data.filter(s=>s.workout_exercise_id===row.id).map(s=>({weight:s.weight_kg??'',reps:s.repetitions??'',rir:s.rir??'',warmup:s.notes==='warmup'}));if(values.some(meaningful))latest[name]={date:dates[row.workout_id],sets:values}}write(HISTORY,latest);localStorage.setItem(HISTORY_STAMP,String(Date.now()));setTimeout(restore,60)}finally{historyPromise=null}})();return historyPromise}

function ensureMoveDialog(){let d=q('#move-dialog-v55');if(d)return d;d=document.createElement('dialog');d.id='move-dialog-v55';d.innerHTML=`<header><div><small>TERMIN VERSCHIEBEN</small><h2 id="move-title-v55">Training</h2></div><button type="button" id="move-close-v55">Schließen</button></header><div class="move-body-v55"><label>Neues Datum<input type="date" id="move-date-v55"></label><button type="button" class="primary" id="move-save-v55">Verschieben</button><p id="move-status-v55"></p></div>`;document.body.append(d);q('#move-close-v55').onclick=()=>d.close();q('#move-save-v55').onclick=saveMove;return d}
function openMove(){const date=q('#planning-dialog')?.dataset.date,item=snapshot().schedule?.find(x=>x.date===date&&['planned','confirmed','started'].includes(x.status));if(!item)return;moveItem=item;q('#planning-dialog')?.close();const d=ensureMoveDialog();q('#move-title-v55').textContent=`Training ${item.code}`;q('#move-date-v55').value=item.date;q('#move-status-v55').textContent='';d.showModal()}
const noon=v=>new Date(`${v}T12:00:00`),iso=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d);function addDays(v,n){const d=noon(v);d.setDate(d.getDate()+n);return iso(d)}
async function saveMove(){const target=q('#move-date-v55').value,status=q('#move-status-v55'),button=q('#move-save-v55');if(!target||!moveItem)return;const snap=snapshot(),source=snap.schedule.find(x=>String(x.id)===String(moveItem.id));if(!source)return;const delta=Math.round((noon(target)-noon(source.date))/86400000),future=snap.schedule.filter(x=>x.date>=source.date&&['planned','confirmed','started'].includes(x.status)).sort((a,b)=>a.date.localeCompare(b.date)),remote=future.filter(x=>!String(x.id).startsWith('local-'));button.disabled=true;status.textContent='Wird verschoben …';try{for(let i=0;i<remote.length;i++){const u=await supabase.from('scheduled_workouts').update({scheduled_date:addDays('2099-12-01',i)}).eq('id',remote[i].id);if(u.error)throw u.error}for(const row of remote){const u=await supabase.from('scheduled_workouts').update({scheduled_date:addDays(row.date,delta),status:'planned'}).eq('id',row.id);if(u.error)throw u.error}localStorage.removeItem(SNAP);location.reload()}catch(error){status.textContent=error.message||String(error);button.disabled=false}}

loadCss();sanitize();
document.addEventListener('click',event=>{if(event.target.closest('#planning-move')){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openMove();return}const device=event.target.closest('[data-device-index-v55]');if(device){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();chooseVariant(Number(device.dataset.deviceIndexV55));return}if(event.target.closest('[data-variant-prev-v53],[data-variant-next-v53],[data-select-ex-v53],[data-prev-ex-v53],[data-next-ex-v53]')){saveDevice(context());setTimeout(restore,80)}if(event.target.closest('[data-add-set-v53],[data-remove-set-v53],[data-status-v53],#order-toggle-v53,[data-order-up-v53],[data-order-down-v53]'))setTimeout(restore,80);if(event.target.closest('[data-workout],#start-workout')){hydrate();[180,420,800].forEach(ms=>setTimeout(restore,ms))}},true);
document.addEventListener('input',event=>{propagate(event);if(event.target.closest('#workout-dialog.workout-v53 [data-field-v53]'))setTimeout(()=>saveDevice(context()),0)});
document.addEventListener('change',event=>{if(event.target.closest('#workout-dialog.workout-v53 [data-field-v53]'))setTimeout(()=>saveDevice(context()),0)});
window.addEventListener('load',()=>{hydrate({force:true});const d=q('#workout-dialog');d?.addEventListener('toggle',()=>{if(d.open){hydrate();[180,420].forEach(ms=>setTimeout(restore,ms))}})});
window.addEventListener('online',()=>hydrate({force:true}));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){hydrate();setTimeout(restore,100)}});
