import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const SNAP='gym-snapshot-v9',THEME='gym-theme';
let session=null,snapshot=null,viewed=new Date(),selectedScheduleId=null,currentCode='A',timerStartedAt=null,timerInterval=null;
const iso=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d);
const pd=v=>new Date(`${v}T12:00:00`);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const showOnly=el=>{['#loading','#login-screen','#dashboard'].forEach(s=>$(s)?.classList.add('hidden'));el?.classList.remove('hidden')};

const fallback={plan:{id:null,name:'Dave'},workouts:{A:{id:null,code:'A',title:'Training A',focus:'Brust · Rückenbreite · seitliche Schulter',sequence_position:1,exercises:[['Schrägbankdrückmaschine dual',3,6,10,180],['Latzugstation mit Oberschenkelpolster',3,8,12,120],['Brustpresse sitzend',3,8,12,120],['Rudermaschine mit Brustpolster',3,8,12,120],['Seithebemaschine ohne Armpolster',4,12,20,90],['Butterfly reverse mit Griffen',3,12,18,90],['Bauchmuskelmaschine',3,10,15,90]].map((x,i)=>({id:`fa${i}`,name:x[0],target_sets:x[1],rep_min:x[2],rep_max:x[3],rest_seconds:x[4]}))},B:{id:null,code:'B',title:'Training B',focus:'obere Brust · Rückendicke · hintere Schulter · Arme',sequence_position:2,exercises:[['Kurzhantel-Schrägbankdrücken',3,6,10,180],['High Row dual',3,8,12,120],['Butterfly mit Griffen',3,8,12,90],['Low Row dual',3,8,12,120],['Seithebemaschine ohne Armpolster',4,12,20,90],['Butterfly reverse mit Griffen',3,12,18,90],['Trizepsmaschine Überkopf',2,8,12,90],['Bizepsmaschine',2,8,12,90]].map((x,i)=>({id:`fb${i}`,name:x[0],target_sets:x[1],rep_min:x[2],rep_max:x[3],rest_seconds:x[4]}))}},schedule:[],completed:[],latestWeight:null,offlineFallback:true};
function makeFallbackSchedule(){const out=[];let d=new Date(),code='A';while(out.length<18){if([2,4,6].includes(d.getDay())){out.push({id:`local-${out.length}`,date:iso(d),status:'planned',code});code=code==='A'?'B':'A'}d.setDate(d.getDate()+1)}return out}fallback.schedule=makeFallbackSchedule();

function addError(title,message){const stack=$('#error-stack');if(!stack)return;const item=document.createElement('article');item.className='error-banner';item.innerHTML=`<strong>${title}</strong><p>${message}</p><button aria-label="Fehler schließen">×</button>`;item.querySelector('button').onclick=()=>item.remove();stack.append(item)}
function clearErrors(){$('#error-stack')?.replaceChildren()}

async function loadRemote(){
 const {data:plans,error:pErr}=await supabase.from('training_plans').select('id,name,goal,version').eq('is_active',true).order('version',{ascending:false}).limit(1);if(pErr)throw new Error(`training_plans: ${pErr.message}`);if(!plans?.length)throw new Error('training_plans: kein aktiver Plan');
 const plan=plans[0];
 const {data:pws,error:wErr}=await supabase.from('plan_workouts').select('id,code,title,focus,sequence_position').eq('plan_id',plan.id).order('sequence_position');if(wErr)throw new Error(`plan_workouts: ${wErr.message}`);
 const ids=(pws||[]).map(x=>x.id);
 const {data:pes,error:peErr}=ids.length?await supabase.from('plan_exercises').select('id,plan_workout_id,exercise_id,exercise_order,target_sets,rep_min,rep_max,rest_seconds,instructions').in('plan_workout_id',ids).order('exercise_order'):{data:[],error:null};if(peErr)throw new Error(`plan_exercises: ${peErr.message}`);
 const exIds=[...new Set((pes||[]).map(x=>x.exercise_id))];let exs=[];if(exIds.length){const r=await supabase.from('exercises').select('id,name,image_path,equipment').in('id',exIds);if(r.error)throw new Error(`exercises: ${r.error.message}`);exs=r.data||[]}
 const exMap=Object.fromEntries(exs.map(x=>[x.id,x]));const workouts={};for(const w of pws||[])workouts[w.code]={...w,exercises:(pes||[]).filter(x=>x.plan_workout_id===w.id).map(x=>({...x,name:exMap[x.exercise_id]?.name||'Übung',image_path:exMap[x.exercise_id]?.image_path||null,equipment:exMap[x.exercise_id]?.equipment||''}))};
 const sr=await supabase.from('scheduled_workouts').select('id,plan_workout_id,scheduled_date,status').order('scheduled_date');if(sr.error)throw new Error(`scheduled_workouts: ${sr.error.message}`);
 const dr=await supabase.from('workouts').select('id,plan_workout_id,workout_date,status').in('status',['completed','partial']).order('workout_date',{ascending:false}).limit(100);if(dr.error)throw new Error(`workouts: ${dr.error.message}`);
 const wr=await supabase.from('weigh_ins').select('id,measured_at,weight_kg').order('measured_at',{ascending:false}).limit(1);if(wr.error)throw new Error(`weigh_ins: ${wr.error.message}`);
 const codeById=Object.fromEntries((pws||[]).map(x=>[x.id,x.code]));snapshot={plan,workouts,schedule:(sr.data||[]).map(x=>({id:x.id,plan_workout_id:x.plan_workout_id,date:x.scheduled_date,status:x.status,code:codeById[x.plan_workout_id]||'?'})),completed:(dr.data||[]).map(x=>({id:x.id,date:x.workout_date,status:x.status,code:codeById[x.plan_workout_id]||'?'})),latestWeight:wr.data?.[0]||null};write(SNAP,snapshot);return snapshot;
}

function monthMarkup(){const y=viewed.getFullYear(),m=viewed.getMonth(),off=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),planned=new Map(snapshot.schedule.map(x=>[x.date,x])),done=new Map(snapshot.completed.map(x=>[x.date,x]));let html='';for(let i=0;i<off;i++)html+='<span class="calendar-day empty"></span>';for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,p=planned.get(date),a=done.get(date),sel=p?.id===selectedScheduleId;html+=`<button class="calendar-day ${date===iso()?'today':''} ${a?'completed':p?'planned':''} ${sel?'selected':''}" data-date="${date}" data-schedule-id="${p?.id||''}"><span>${d}</span>${a?`<small class="plan-badge">${a.code} ✓</small>`:p?`<small class="plan-badge">${p.code}</small>`:''}</button>`}return html}
function renderCalendars(){const title=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(viewed);$$('[data-calendar-title]').forEach(e=>e.textContent=title);$$('[data-calendar-grid]').forEach(e=>e.innerHTML=monthMarkup())}
function nextPlanned(){return snapshot.schedule.find(x=>['planned','confirmed','started'].includes(x.status))||snapshot.schedule[0]}
function render(){const next=nextPlanned();$('#next-workout').textContent=next?`Training ${next.code}`:'Training planen';$('#next-date').textContent=next?new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(pd(next.date)):'Noch kein Termin';$('#completed-count').textContent=snapshot.completed.length;$('#week-count').textContent=snapshot.completed.filter(x=>Math.abs(new Date()-pd(x.date))<7*864e5).length;$('#streak-count').textContent='0';$('#latest-weight').textContent=snapshot.latestWeight?`${Number(snapshot.latestWeight.weight_kg).toFixed(1)} kg`:'Noch kein Gewicht';$('#connection-status').textContent=snapshot.offlineFallback?'Lokaler Plan':'Online';$('#workout-list').innerHTML=Object.values(snapshot.workouts).sort((a,b)=>a.sequence_position-b.sequence_position).map(w=>`<article class="workout-card"><p class="eyebrow">EINHEIT ${w.code}</p><h3>${w.title}</h3><p>${w.focus||''}</p><button data-workout="${w.code}">Plan ansehen</button></article>`).join('');renderCalendars()}

function setTab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));closeDrawer();window.scrollTo({top:0,behavior:'smooth'})}
function openDrawer(){$('#drawer').classList.add('open');$('#drawer-backdrop').classList.remove('hidden')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer-backdrop').classList.add('hidden')}
function openWorkout(code){const w=snapshot?.workouts?.[code];if(!w){addError('Training konnte nicht geöffnet werden',`Einheit ${code} wurde nicht gefunden.`);return}currentCode=code;$('#dialog-title').textContent=w.title;$('#exercise-list').innerHTML=w.exercises.map(ex=>`<article class="exercise-card"><div class="exercise-image">${ex.image_path?`<img src="${ex.image_path}" alt="${ex.name}">`:'Gerätebild folgt'}</div><div class="exercise-body"><h3>${ex.name}</h3><p>${ex.target_sets} × ${ex.rep_min}–${ex.rep_max} · ${ex.rest_seconds} Sek.</p></div></article>`).join('');$('#workout-timer').textContent='00:00';timerStartedAt=null;clearInterval(timerInterval);$('#timer-toggle').textContent='Training starten';$('#workout-dialog').showModal()}
function toggleTimer(){if(timerStartedAt){timerStartedAt=null;clearInterval(timerInterval);$('#timer-toggle').textContent='Fortsetzen';return}timerStartedAt=Date.now();$('#timer-toggle').textContent='Pause';timerInterval=setInterval(()=>{const sec=Math.floor((Date.now()-timerStartedAt)/1000);$('#workout-timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`},1000)}

async function moveSchedule(id,date){const item=snapshot.schedule.find(x=>x.id===id);if(!item)return;const r=await supabase.from('scheduled_workouts').update({scheduled_date:date,status:'planned'}).eq('id',id);if(r.error)throw new Error(r.error.message);await loadRemote();selectedScheduleId=null;render();}
async function createSchedule(code,date){const w=snapshot.workouts[code];if(!w?.id)throw new Error('Plan ist nur lokal geladen. Termin kann erst online gespeichert werden.');const r=await supabase.from('scheduled_workouts').insert({user_id:session.user.id,plan_workout_id:w.id,scheduled_date:date,status:'planned'});if(r.error)throw new Error(r.error.message);await loadRemote();render()}
function openPlanning(date){$('#planning-date').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long'}).format(pd(date));$('#planning-dialog').dataset.date=date;$('#planning-dialog').showModal()}
async function calendarClick(e){const b=e.target.closest('[data-date]');if(!b)return;const date=b.dataset.date,id=b.dataset.scheduleId;if(selectedScheduleId){try{await moveSchedule(selectedScheduleId,date)}catch(err){addError('Termin konnte nicht verschoben werden',err.message)}return}if(id){selectedScheduleId=id;renderCalendars();$$('.calendar-help').forEach(x=>x.textContent='Gewähltes Training: Jetzt den neuen Tag antippen.');return}openPlanning(date)}

async function enter(){showOnly($('#loading'));clearErrors();try{await loadRemote()}catch(err){snapshot=read(SNAP,null)||structuredClone(fallback);addError('Datenbank konnte nicht vollständig geladen werden',err.message)}showOnly($('#dashboard'));render()}
async function boot(){document.documentElement.dataset.theme=localStorage.getItem(THEME)||'light';if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});const r=await supabase.auth.getSession();session=r.data.session;if(session)await enter();else showOnly($('#login-screen'))}

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const r=await supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(r.error){$('#login-error').textContent=`Anmeldung fehlgeschlagen: ${r.error.message}`;return}session=r.data.session;await enter()});
$('#logout').onclick=async()=>{await supabase.auth.signOut();session=null;showOnly($('#login-screen'))};
$('#theme-toggle').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem(THEME,t)};
$('#menu-toggle').onclick=openDrawer;$('#drawer-close').onclick=closeDrawer;$('#drawer-backdrop').onclick=closeDrawer;
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-drawer-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.drawerTab));
$('#start-workout').onclick=()=>openWorkout(nextPlanned()?.code||'A');$('#change-next').onclick=()=>{const n=nextPlanned();if(n)selectedScheduleId=n.id;setTab('calendar');renderCalendars()};
$('#workout-list').onclick=e=>{const b=e.target.closest('[data-workout]');if(b)openWorkout(b.dataset.workout)};$('#close-dialog').onclick=()=>$('#workout-dialog').close();$('#timer-toggle').onclick=toggleTimer;
$$('[data-prev-month]').forEach(b=>b.onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()-1,1);renderCalendars()});$$('[data-next-month]').forEach(b=>b.onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()+1,1);renderCalendars()});$$('[data-calendar-grid]').forEach(g=>g.onclick=calendarClick);
$('#planning-close').onclick=()=>$('#planning-dialog').close();$$('[data-plan-code]').forEach(b=>b.onclick=async()=>{const date=$('#planning-dialog').dataset.date;$('#planning-dialog').close();try{await createSchedule(b.dataset.planCode,date)}catch(err){addError('Training konnte nicht geplant werden',err.message)}});
$('#open-weight').onclick=()=>$('#weight-dialog').showModal();$('#open-weight-2').onclick=()=>$('#weight-dialog').showModal();$('#close-weight').onclick=()=>$('#weight-dialog').close();$('#save-weight').onclick=async()=>{const v=Number(String($('#weight-input').value).replace(',','.'));if(!v||v<30||v>300){$('#weight-status').textContent='Ungültiges Gewicht';return}const r=await supabase.from('weigh_ins').insert({user_id:session.user.id,weight_kg:v,toilet_status:$('#weight-toilet').value,food_status:$('#weight-food').value,late_meal:$('#weight-late').value,unusual_time:$('#weight-unusual').checked,trained_previous_day:$('#weight-trained').checked});if(r.error){$('#weight-status').textContent=r.error.message;return}$('#weight-dialog').close();await enter()};
supabase.auth.onAuthStateChange((_e,s)=>{session=s;if(!s)showOnly($('#login-screen'))});boot();