const SUPABASE_URL='https://spmyrocxftgisdeiuiyg.supabase.co';
const SUPABASE_KEY='sb_publishable_090vD-HjxF19zoKWc9LLMQ_Xz6JliJs';
const SNAP='gym-snapshot-v11';
const THEME='gym-theme';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const fallback={plan:{id:null},workouts:{},schedule:[],completed:[],weights:[],measurements:[]};
let supabase=null;
let session=null;
let snapshot=read(SNAP,fallback);
let viewed=new Date();

function read(key,fallbackValue){try{return JSON.parse(localStorage.getItem(key))??fallbackValue}catch{return fallbackValue}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function showOnly(selector){['#loading','#login-screen','#dashboard'].forEach(s=>$(s)?.classList.add('hidden'));$(selector)?.classList.remove('hidden')}
function setText(selector,value){const el=$(selector);if(el)el.textContent=value}
function addError(title,message){const stack=$('#error-stack');if(!stack)return;const box=document.createElement('article');box.className='error-banner';box.innerHTML=`<strong>${title}</strong><p>${message}</p><button type="button">×</button>`;box.querySelector('button').onclick=()=>box.remove();stack.prepend(box)}
function withTimeout(promise,ms,label){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`${label} dauert zu lange.`)),ms))])}
function loadScript(src){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const script=document.createElement('script');script.src=src;script.async=true;script.onload=resolve;script.onerror=()=>reject(new Error('Supabase-Bibliothek konnte nicht geladen werden.'));document.head.appendChild(script)})}
function iso(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(date)}
function parseDate(value){return new Date(`${value}T12:00:00`)}

function openDrawer(){$('#drawer')?.classList.add('open');$('#drawer-backdrop')?.classList.remove('hidden')}
function closeDrawer(){$('#drawer')?.classList.remove('open');$('#drawer-backdrop')?.classList.add('hidden')}
function setPage(name){$$('.page').forEach(page=>page.classList.toggle('active',page.id===`page-${name}`));$$('[data-page]').forEach(button=>button.classList.toggle('active',button.dataset.page===name));const names={dashboard:'Dashboard Dave',plan:'Trainingsplan Dave',calendar:'Kalender Dave',weight:'Gewicht Dave',measurements:'Umfänge Dave',progress:'Fortschritt Dave',photos:'Fotos Dave',studio:'Studio Dave',settings:'Einstellungen Dave'};setText('#page-title',names[name]||'Dave');closeDrawer();scrollTo(0,0)}
function toggleTheme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem(THEME,next)}

function monthHtml(){const y=viewed.getFullYear(),m=viewed.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();const planned=new Map((snapshot.schedule||[]).map(x=>[x.date||x.scheduled_date,x]));const done=new Map((snapshot.completed||[]).map(x=>[x.date||x.workout_date,x]));let html='';for(let i=0;i<offset;i++)html+='<span></span>';for(let day=1;day<=days;day++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,p=planned.get(date),c=done.get(date);html+=`<button class="calendar-day ${date===iso()?'today':''} ${c?'completed':p?'planned':''}" data-date="${date}"><span>${day}</span>${c?`<small class="plan-badge">${c.code||''} ✓</small>`:p?`<small class="plan-badge">${p.code||''}</small>`:''}</button>`}return html}
function chart(el,rows,key){if(!el)return;const values=(rows||[]).map(row=>Number(row[key])).filter(Number.isFinite);if(!values.length){el.innerHTML='<div class="chart-empty">Noch keine Daten</div>';return}const min=Math.min(...values),max=Math.max(...values),range=max-min||1,w=320,h=145,p=18;const points=values.map((value,index)=>`${p+index*(w-2*p)/Math.max(1,values.length-1)},${h-p-(value-min)/range*(h-2*p)}`).join(' ');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" class="chart"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="3"/></svg>`}
function render(){const title=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(viewed);$$('[data-calendar-title]').forEach(el=>el.textContent=title);$$('[data-calendar-grid]').forEach(el=>el.innerHTML=monthHtml());const upcoming=(snapshot.schedule||[]).filter(x=>['planned','confirmed','started',undefined].includes(x.status)).sort((a,b)=>(a.date||a.scheduled_date).localeCompare(b.date||b.scheduled_date))[0];setText('#next-workout',upcoming?`Training ${upcoming.code||''}`:'Training planen');setText('#next-date',upcoming?new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(parseDate(upcoming.date||upcoming.scheduled_date)):'');const last=(snapshot.weights||[]).at(-1);setText('#latest-weight',last?`${Number(last.weight_kg).toFixed(2)} kg`:'Noch kein Gewicht');setText('#completed-count',(snapshot.completed||[]).length);setText('#week-count',(snapshot.completed||[]).filter(x=>Math.abs(new Date()-parseDate(x.date||x.workout_date))<7*864e5).length);setText('#streak-count','0');const list=$('#workout-list');if(list){const workouts=Object.values(snapshot.workouts||{}).sort((a,b)=>(a.sequence_position||0)-(b.sequence_position||0));list.innerHTML=workouts.length?workouts.map(w=>`<article class="workout-card"><small>EINHEIT ${w.code||''}</small><h3>${w.title||`Training ${w.code||''}`}</h3><p>${w.focus||''}</p><button class="secondary" data-workout="${w.code||''}">Plan öffnen</button></article>`).join(''):'<article class="workout-card"><h3>Trainingsplan wird synchronisiert</h3><p>Die Grundoberfläche ist bereits bedienbar.</p></article>'}chart($('#weight-chart'),snapshot.weights,'weight_kg');chart($('#weight-chart-2'),snapshot.weights,'weight_kg');chart($('#waist-chart'),snapshot.measurements,'waist_cm');chart($('#waist-chart-2'),snapshot.measurements,'waist_cm')}

async function loadData(){if(!supabase||!session)return;const planResult=await withTimeout(supabase.from('training_plans').select('*').eq('is_active',true).order('version',{ascending:false}).limit(1),8000,'Trainingsplan');if(planResult.error)throw planResult.error;if(!planResult.data?.length)throw new Error('Kein aktiver Trainingsplan gefunden.');const plan=planResult.data[0];const workoutResult=await withTimeout(supabase.from('plan_workouts').select('*').eq('plan_id',plan.id).order('sequence_position'),8000,'Trainingseinheiten');if(workoutResult.error)throw workoutResult.error;const ids=workoutResult.data.map(x=>x.id);const exerciseResult=ids.length?await withTimeout(supabase.from('plan_exercises').select('*').in('plan_workout_id',ids).order('exercise_order'),8000,'Übungen'):{data:[],error:null};if(exerciseResult.error)throw exerciseResult.error;const exerciseIds=[...new Set(exerciseResult.data.map(x=>x.exercise_id))];const names=exerciseIds.length?await withTimeout(supabase.from('exercises').select('id,name,image_path').in('id',exerciseIds),8000,'Übungsnamen'):{data:[],error:null};if(names.error)throw names.error;const nameMap=Object.fromEntries(names.data.map(x=>[x.id,x]));const workouts={};workoutResult.data.forEach(w=>{workouts[w.code]={...w,exercises:exerciseResult.data.filter(e=>e.plan_workout_id===w.id).map(e=>({...e,name:nameMap[e.exercise_id]?.name||'Übung',image_path:nameMap[e.exercise_id]?.image_path||null}))}});const results=await Promise.all([
withTimeout(supabase.from('scheduled_workouts').select('*').order('scheduled_date'),8000,'Kalender'),
withTimeout(supabase.from('workouts').select('*').in('status',['completed','partial']).order('workout_date'),8000,'Trainingshistorie'),
withTimeout(supabase.from('weigh_ins').select('*').order('measured_at'),8000,'Gewichtsdaten'),
withTimeout(supabase.from('body_measurements').select('*').order('measured_at'),8000,'Körpermaße')]);
for(const result of results)if(result.error)throw result.error;const codeMap=Object.fromEntries(workoutResult.data.map(x=>[x.id,x.code]));snapshot={plan,workouts,schedule:results[0].data.map(x=>({...x,date:x.scheduled_date,code:codeMap[x.plan_workout_id]})),completed:results[1].data.map(x=>({...x,date:x.workout_date,code:codeMap[x.plan_workout_id]})),weights:results[2].data,measurements:results[3].data};write(SNAP,snapshot);render()}

function bindUi(){document.documentElement.dataset.theme=localStorage.getItem(THEME)||'light';$('#menu-toggle')?.addEventListener('click',openDrawer);$('#drawer-close')?.addEventListener('click',closeDrawer);$('#drawer-backdrop')?.addEventListener('click',closeDrawer);$('#theme-toggle')?.addEventListener('click',toggleTheme);$('#settings-theme')?.addEventListener('click',toggleTheme);$$('[data-page]').forEach(button=>button.addEventListener('click',()=>setPage(button.dataset.page)));$$('[data-page-link]').forEach(button=>button.addEventListener('click',()=>setPage(button.dataset.pageLink)));$$('[data-prev-month]').forEach(button=>button.addEventListener('click',()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()-1,1);render()}));$$('[data-next-month]').forEach(button=>button.addEventListener('click',()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()+1,1);render()}));$('#close-dialog')?.addEventListener('click',()=>$('#workout-dialog')?.close());$('#planning-close')?.addEventListener('click',()=>$('#planning-dialog')?.close());$('#login-form')?.addEventListener('submit',login);$('#logout')?.addEventListener('click',logout);$('#workout-list')?.addEventListener('click',event=>{const button=event.target.closest('[data-workout]');if(button)openBasicWorkout(button.dataset.workout)});$('#start-workout')?.addEventListener('click',()=>{const next=(snapshot.schedule||[]).sort((a,b)=>(a.date||'').localeCompare(b.date||''))[0];openBasicWorkout(next?.code||'A')});}
function openBasicWorkout(code){const workout=snapshot.workouts?.[code];if(!workout){addError('Training noch nicht verfügbar','Die Trainingsdaten konnten noch nicht synchronisiert werden.');return}setText('#dialog-title',workout.title||`Training ${code}`);const list=$('#exercise-list');if(list)list.innerHTML=(workout.exercises||[]).map(ex=>`<article class="exercise-card"><h3>${ex.name}</h3><p>${ex.target_sets||3} × ${ex.rep_min||8}–${ex.rep_max||12}</p></article>`).join('');$('#workout-dialog')?.showModal()}
async function login(event){event.preventDefault();setText('#login-error','');if(!supabase){setText('#login-error','Verbindung wird noch geladen. Bitte kurz erneut versuchen.');return}try{const result=await withTimeout(supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value}),10000,'Anmeldung');if(result.error)throw result.error;session=result.data.session;showOnly('#dashboard');render();loadData().catch(error=>addError('Datenbankfehler',error.message))}catch(error){setText('#login-error',error.message)}}
async function logout(){try{await supabase?.auth.signOut()}catch{}session=null;showOnly('#login-screen')}

async function boot(){bindUi();render();showOnly('#login-screen');try{await withTimeout(loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js'),8000,'Supabase');if(!window.supabase?.createClient)throw new Error('Supabase ist nicht verfügbar.');supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const result=await withTimeout(supabase.auth.getSession(),8000,'Sitzungsprüfung');session=result.data?.session||null;if(session){showOnly('#dashboard');render();loadData().catch(error=>addError('Datenbankfehler',error.message))}else{showOnly('#login-screen')}}catch(error){showOnly('#login-screen');setText('#login-error',`Startfehler: ${error.message}`)}}

document.addEventListener('DOMContentLoaded',boot,{once:true});
