import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const KEY='gym-progress-v4',THEME='gym-theme';const preferred=[2,4,6];
const plans={A:{title:'Training A',focus:'Brust · Rückenbreite · seitliche Schulter',exercises:[['Schrägbankdrückmaschine dual','3 × 6–10','150–180 Sek.'],['Latzugstation mit Oberschenkelpolster','3 × 8–12','120 Sek.'],['Brustpresse sitzend','3 × 8–12','120 Sek.'],['Rudermaschine mit Brustpolster','3 × 8–12','120 Sek.'],['Seithebemaschine ohne Armpolster','4 × 12–20','75–90 Sek.'],['Butterfly reverse mit Griffen','3 × 12–18','90 Sek.'],['Bauchmuskelmaschine','3 × 10–15','90 Sek.']]},B:{title:'Training B',focus:'obere Brust · Rückendicke · hintere Schulter · Arme',exercises:[['Kurzhantel-Schrägbankdrücken','3 × 6–10','180 Sek.'],['High Row dual','3 × 8–12','120 Sek.'],['Butterfly mit Griffen','3 × 8–12','90 Sek.'],['Low Row dual','3 × 8–12','120 Sek.'],['Seithebemaschine ohne Armpolster','4 × 12–20','75–90 Sek.'],['Butterfly reverse mit Griffen','3 × 12–18','90 Sek.'],['Trizepsmaschine Überkopf','2 × 8–12','90 Sek.'],['Bizepsmaschine','2 × 8–12','90 Sek.']]}};
const $=s=>document.querySelector(s),els={loading:$('#loading'),login:$('#login-screen'),dashboard:$('#dashboard'),form:$('#login-form'),error:$('#login-error'),list:$('#workout-list'),dialog:$('#workout-dialog'),exercises:$('#exercise-list'),dialogTitle:$('#dialog-title'),next:$('#next-workout'),nextDate:$('#next-date'),completed:$('#completed-count'),streak:$('#streak-count'),week:$('#week-count'),calendar:$('#calendar-grid'),calendarTitle:$('#calendar-title'),calendarHelp:$('#calendar-help'),connection:$('#connection-status'),complete:$('#complete-workout'),timer:$('#workout-timer'),completionHint:$('#completion-hint'),toast:$('#toast')};
let current='A',viewed=new Date(),selected=null,timerId=null;
function iso(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d)}function pd(v){return new Date(`${v}T12:00:00`)}
function nextDay(after){const d=new Date(after);d.setDate(d.getDate()+1);while(!preferred.includes(d.getDay()))d.setDate(d.getDate()+1);return d}
function build(start,code,count=18){let d=new Date(start);if(!preferred.includes(d.getDay()))d=nextDay(new Date(d.getFullYear(),d.getMonth(),d.getDate()-1));const r=[];for(let i=0;i<count;i++){r.push({date:iso(d),code,id:crypto.randomUUID()});code=code==='A'?'B':'A';d=nextDay(d)}return r}
function load(){try{const p=JSON.parse(localStorage.getItem(KEY));if(p?.schedule)return p}catch{}const p={completed:[],schedule:build(new Date(),'A'),active:null};save(p);return p}function save(p){localStorage.setItem(KEY,JSON.stringify(p))}
function showOnly(el){[els.loading,els.login,els.dashboard].forEach(x=>x.classList.add('hidden'));el.classList.remove('hidden')}function toast(m){els.toast.textContent=m;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2200)}
function renderPlans(){els.list.innerHTML=Object.entries(plans).map(([c,p])=>`<article class="workout-card"><p class="eyebrow">EINHEIT ${c}</p><h3>${p.title}</h3><p class="muted">${p.focus}</p><div class="workout-meta"><span>${p.exercises.length} Übungen</span></div><button data-workout="${c}">Plan ansehen</button></article>`).join('')}
function weekKey(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return `${x.getUTCFullYear()}-${Math.ceil((((x-y)/86400000)+1)/7)}`}
function stats(p){els.completed.textContent=p.completed.length;els.week.textContent=p.completed.filter(x=>weekKey(pd(x.date))===weekKey(new Date())).length;const weeks=[...new Set(p.completed.map(x=>weekKey(pd(x.date))))];let s=0,c=new Date();while(weeks.includes(weekKey(c))){s++;c.setDate(c.getDate()-7)}els.streak.textContent=s}
function renderCalendar(p){const y=viewed.getFullYear(),m=viewed.getMonth();els.calendarTitle.textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(viewed);const first=new Date(y,m,1),off=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),done=new Map(p.completed.map(x=>[x.date,x.code])),planned=new Map(p.schedule.map((x,i)=>[x.date,{...x,index:i}])),cells=[];for(let i=0;i<off;i++)cells.push('<span class="calendar-day empty"></span>');for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,info=planned.get(date),cl=['calendar-day'];if(date===iso())cl.push('today');if(done.has(date))cl.push('completed');else if(info)cl.push('planned');if(info?.index===selected)cl.push('selected');if(pd(date).getDay()===1)cl.push('monday');cells.push(`<button class="${cl.join(' ')}" data-date="${date}"><span>${d}</span>${done.has(date)?`<small class="plan-badge">${done.get(date)}</small>`:info?`<small class="plan-badge">${info.code}</small>`:''}</button>`)}els.calendar.innerHTML=cells.join('')}
function refresh(){const p=load(),first=p.schedule[0];els.next.textContent=`Training ${first?.code||'A'}`;els.nextDate.textContent=first?new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(pd(first.date)):'';stats(p);renderCalendar(p)}
function elapsed(active){if(!active)return 0;return active.elapsed||0+(active.runningSince?Date.now()-active.runningSince:0)}function drawTimer(){const p=load(),a=p.active,ms=a?(a.elapsed||0)+(a.runningSince?Date.now()-a.runningSince:0):0,s=Math.floor(ms/1000);els.timer.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function renderExerciseStates(){const p=load(),a=p.active&&p.active.code===current?p.active:{states:{}};els.exercises.querySelectorAll('.exercise-card').forEach(card=>{const st=a.states?.[card.dataset.exercise];card.classList.toggle('done',st==='done');card.classList.toggle('skipped',st==='skipped')});updateCompletion()}
function openWorkout(code){current=code;els.dialogTitle.textContent=plans[code].title;els.exercises.innerHTML=plans[code].exercises.map(([n,r,pa],i)=>`<article class="exercise-card" data-exercise="${i}"><div class="exercise-image">Gerätebild folgt</div><div class="exercise-body"><h3>${n}</h3><p class="exercise-prescription">${r} · ${pa}</p><div class="exercise-actions"><button class="mark-done">Erledigt</button><button class="skip">Nicht geschafft</button></div></div></article>`).join('');renderExerciseStates();drawTimer();els.dialog.showModal()}
function ensureActive(){const p=load();if(!p.active||p.active.code!==current)p.active={code:current,date:iso(),elapsed:0,runningSince:null,states:{}};save(p);return p}
function startPause(){const p=ensureActive(),a=p.active;if(a.runningSince){a.elapsed=(a.elapsed||0)+(Date.now()-a.runningSince);a.runningSince=null}else a.runningSince=Date.now();save(p);drawTimer()}
function updateCompletion(){const p=load(),a=p.active&&p.active.code===current?p.active:null,total=plans[current].exercises.length,resolved=a?Object.values(a.states||{}).filter(x=>x==='done'||x==='skipped').length:0;els.complete.disabled=resolved!==total;els.completionHint.textContent=`${resolved} von ${total} Übungen bewertet`}
function setState(i,state){const p=ensureActive();p.active.states[i]=p.active.states[i]===state?null:state;save(p);renderExerciseStates()}
function complete(){const p=load(),a=p.active;if(!a||a.code!==current)return;const vals=Object.values(a.states||{});if(vals.length!==plans[current].exercises.length){toast('Bitte jede Übung als erledigt oder nicht geschafft markieren.');return}if(a.runningSince){a.elapsed=(a.elapsed||0)+(Date.now()-a.runningSince);a.runningSince=null}const skipped=Object.entries(a.states).filter(([,v])=>v==='skipped').map(([i])=>Number(i));p.completed.push({date:a.date,code:current,duration_minutes:Math.round((a.elapsed||0)/60000),skipped,id:crypto.randomUUID()});const idx=p.schedule.findIndex(x=>x.code===current);if(idx>=0)p.schedule.splice(idx,1);while(p.schedule.length<18){const last=pd(p.schedule.at(-1)?.date||iso()),code=p.schedule.at(-1)?.code==='A'?'B':'A';p.schedule.push({date:iso(nextDay(last)),code,id:crypto.randomUUID()})}p.active=null;save(p);clearInterval(timerId);els.dialog.close();refresh();toast(skipped.length?`Training ${current} mit ${skipped.length} offener Übung gespeichert.`:`Training ${current} vollständig gespeichert.`)}
function moveSchedule(p,index,date){const moved=p.schedule[index],before=p.schedule.slice(0,index),rep=[{...moved,date}],start=pd(date);let d=start,code=moved.code==='A'?'B':'A';for(let i=index+1;i<p.schedule.length;i++){d=nextDay(d);rep.push({...p.schedule[i],date:iso(d),code});code=code==='A'?'B':'A'}p.schedule=[...before,...rep]}
function calendarClick(date){const p=load(),idx=p.schedule.findIndex(x=>x.date===date);if(date<iso()&&!p.completed.some(x=>x.date===date)){const code=prompt('Training nachtragen: A oder B?');if(code&&['A','B'].includes(code.toUpperCase())){p.completed.push({date,code:code.toUpperCase(),duration_minutes:null,skipped:[],id:crypto.randomUUID()});save(p);refresh();toast('Training nachgetragen.')}return}if(selected===null){if(idx>=0){selected=idx;els.calendarHelp.textContent=`Training ${p.schedule[idx].code} gewählt. Jetzt neuen Tag antippen.`;renderCalendar(p)}else{moveSchedule(p,0,date);save(p);refresh();toast('Nächstes Training verschoben.')}}else{moveSchedule(p,selected,date);save(p);selected=null;els.calendarHelp.textContent='Vorgeschlagen: Dienstag, Donnerstag und Samstag. Geplante Einheit antippen und dann auf den neuen Tag.';refresh();toast('Terminfolge angepasst.')}}
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem(THEME,t);document.querySelector('meta[name="theme-color"]').content=t==='dark'?'#171a17':'#f3f1ea'}
async function init(){setTheme(localStorage.getItem(THEME)||'light');renderPlans();refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');const{data:{session}}=await supabase.auth.getSession();showOnly(session?els.dashboard:els.login);timerId=setInterval(drawTimer,1000)}
els.form.addEventListener('submit',async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){els.error.textContent='Anmeldung fehlgeschlagen.';return}showOnly(els.dashboard)});$('#logout').onclick=async()=>{await supabase.auth.signOut();showOnly(els.login)};$('#theme-toggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('#start-workout').onclick=()=>openWorkout(load().schedule[0]?.code||'A');els.list.onclick=e=>{const b=e.target.closest('[data-workout]');if(b)openWorkout(b.dataset.workout)};$('#close-dialog').onclick=()=>els.dialog.close();els.complete.onclick=complete;els.exercises.onclick=e=>{const card=e.target.closest('.exercise-card');if(!card)return;if(e.target.closest('.mark-done'))setState(card.dataset.exercise,'done');if(e.target.closest('.skip'))setState(card.dataset.exercise,'skipped')};$('#workout-dialog').addEventListener('click',e=>{if(e.target.id==='timer-toggle')startPause()});els.calendar.onclick=e=>{const d=e.target.closest('[data-date]');if(d)calendarClick(d.dataset.date)};$('#prev-month').onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()-1,1);renderCalendar(load())};$('#next-month').onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()+1,1);renderCalendar(load())};window.addEventListener('online',()=>els.connection.textContent='Online');window.addEventListener('offline',()=>els.connection.textContent='Offline – lokal');supabase.auth.onAuthStateChange((_e,s)=>showOnly(s?els.dashboard:els.login));init().catch(()=>showOnly(els.login));