import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SNAP='gym-snapshot-v10',THEME='gym-theme',OFFLINE='gym-manual-offline',QUEUE='gym-sync-queue-v10';
let session=null,snapshot=null,viewed=new Date(),selectedScheduleId=null,currentCode='A',timerStartedAt=null,timerElapsed=0,timerInterval=null,manualOffline=localStorage.getItem(OFFLINE)==='1';
const iso=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d);
const pd=v=>new Date(`${v}T12:00:00`);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const showOnly=el=>{['#loading','#login-screen','#dashboard'].forEach(s=>$(s)?.classList.add('hidden'));el?.classList.remove('hidden')};
const online=()=>navigator.onLine&&!manualOffline;

const fallback={plan:{id:null,name:'Dave'},workouts:{A:{id:null,code:'A',title:'Training A',focus:'Brust · Rückenbreite · seitliche Schulter',sequence_position:1,exercises:[['Schrägbankdrückmaschine dual',3,6,10,180],['Latzugstation mit Oberschenkelpolster',3,8,12,120],['Brustpresse sitzend',3,8,12,120],['Rudermaschine mit Brustpolster',3,8,12,120],['Seithebemaschine ohne Armpolster',4,12,20,90],['Butterfly reverse mit Griffen',3,12,18,90],['Bauchmuskelmaschine',3,10,15,90]].map((x,i)=>({id:`fa${i}`,name:x[0],target_sets:x[1],rep_min:x[2],rep_max:x[3],rest_seconds:x[4]}))},B:{id:null,code:'B',title:'Training B',focus:'obere Brust · Rückendicke · hintere Schulter · Arme',sequence_position:2,exercises:[['Kurzhantel-Schrägbankdrücken',3,6,10,180],['High Row dual',3,8,12,120],['Butterfly mit Griffen',3,8,12,90],['Low Row dual',3,8,12,120],['Seithebemaschine ohne Armpolster',4,12,20,90],['Butterfly reverse mit Griffen',3,12,18,90],['Trizepsmaschine Überkopf',2,8,12,90],['Bizepsmaschine',2,8,12,90]].map((x,i)=>({id:`fb${i}`,name:x[0],target_sets:x[1],rep_min:x[2],rep_max:x[3],rest_seconds:x[4]}))}},schedule:[],completed:[],weights:[],measurements:[],offlineFallback:true};
function makeFallbackSchedule(){const out=[];let d=new Date(),code='A';while(out.length<18){if([2,4,6].includes(d.getDay())){out.push({id:`local-${out.length}`,date:iso(d),status:'planned',code});code=code==='A'?'B':'A'}d.setDate(d.getDate()+1)}return out}fallback.schedule=makeFallbackSchedule();

function addError(title,message){const stack=$('#error-stack');const item=document.createElement('article');item.className='error-banner';item.innerHTML=`<strong>${title}</strong><p>${message}</p><button aria-label="Fehler schließen">×</button>`;item.querySelector('button').onclick=()=>item.remove();stack.append(item)}
function clearErrors(){$('#error-stack')?.replaceChildren()}
function queue(action){const q=read(QUEUE,[]);q.push({...action,queued_at:new Date().toISOString()});write(QUEUE,q);updateStatus()}
async function syncQueue(){if(!online()||!session)return;const q=read(QUEUE,[]),remaining=[];for(const item of q){try{if(item.type==='weight')await insertWeight(item.payload);else if(item.type==='measurement')await insertMeasurement(item.payload);else if(item.type==='deleteSchedule')await deleteScheduleRemote(item.id);else if(item.type==='rotate')await rotateRemote(item.id,item.date);else if(item.type==='createSchedule')await createScheduleRemote(item.code,item.date)}catch(e){remaining.push(item)}}write(QUEUE,remaining);updateStatus()}
function updateStatus(){const q=read(QUEUE,[]).length;$('#connection-status').textContent=manualOffline?'Offline manuell':navigator.onLine?'Online':'Offline';$('#offline-toggle')?.classList.toggle('active',manualOffline);$('#offline-toggle').textContent=manualOffline?'Offline aktiv':'Offline-Modus';$('#sync-count').textContent=q?`${q} offen`:''}

async function loadRemote(){
 const {data:plans,error:pErr}=await supabase.from('training_plans').select('id,name,goal,version').eq('is_active',true).order('version',{ascending:false}).limit(1);if(pErr)throw new Error(`training_plans: ${pErr.message}`);if(!plans?.length)throw new Error('training_plans: kein aktiver Plan');const plan=plans[0];
 const {data:pws,error:wErr}=await supabase.from('plan_workouts').select('id,code,title,focus,sequence_position').eq('plan_id',plan.id).order('sequence_position');if(wErr)throw new Error(`plan_workouts: ${wErr.message}`);const ids=(pws||[]).map(x=>x.id);
 const {data:pes,error:peErr}=ids.length?await supabase.from('plan_exercises').select('id,plan_workout_id,exercise_id,exercise_order,target_sets,rep_min,rep_max,rest_seconds,instructions').in('plan_workout_id',ids).order('exercise_order'):{data:[],error:null};if(peErr)throw new Error(`plan_exercises: ${peErr.message}`);
 const exIds=[...new Set((pes||[]).map(x=>x.exercise_id))];let exs=[];if(exIds.length){const r=await supabase.from('exercises').select('id,name,image_path,equipment').in('id',exIds);if(r.error)throw new Error(`exercises: ${r.error.message}`);exs=r.data||[]}
 const exMap=Object.fromEntries(exs.map(x=>[x.id,x]));const workouts={};for(const w of pws||[])workouts[w.code]={...w,exercises:(pes||[]).filter(x=>x.plan_workout_id===w.id).map(x=>({...x,name:exMap[x.exercise_id]?.name||'Übung',image_path:exMap[x.exercise_id]?.image_path||null,equipment:exMap[x.exercise_id]?.equipment||''}))};
 const [sr,dr,wr,mr]=await Promise.all([supabase.from('scheduled_workouts').select('id,plan_workout_id,scheduled_date,status').order('scheduled_date'),supabase.from('workouts').select('id,plan_workout_id,workout_date,status').in('status',['completed','partial']).order('workout_date',{ascending:false}).limit(100),supabase.from('weigh_ins').select('id,measured_at,weight_kg').order('measured_at',{ascending:true}).limit(365),supabase.from('body_measurements').select('id,measured_at,waist_cm,chest_cm,upper_arm_left_cm,upper_arm_right_cm,shoulder_cm').order('measured_at',{ascending:true}).limit(100)]);for(const r of [sr,dr,wr,mr])if(r.error)throw new Error(r.error.message);
 const codeById=Object.fromEntries((pws||[]).map(x=>[x.id,x.code]));snapshot={plan,workouts,schedule:(sr.data||[]).map(x=>({id:x.id,plan_workout_id:x.plan_workout_id,date:x.scheduled_date,status:x.status,code:codeById[x.plan_workout_id]||'?'})),completed:(dr.data||[]).map(x=>({id:x.id,date:x.workout_date,status:x.status,code:codeById[x.plan_workout_id]||'?'})),weights:wr.data||[],measurements:mr.data||[]};write(SNAP,snapshot);return snapshot;
}

function monthMarkup(){const y=viewed.getFullYear(),m=viewed.getMonth(),off=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),planned=new Map(snapshot.schedule.map(x=>[x.date,x])),done=new Map(snapshot.completed.map(x=>[x.date,x]));let html='';for(let i=0;i<off;i++)html+='<span class="calendar-day empty"></span>';for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,p=planned.get(date),a=done.get(date),sel=p?.id===selectedScheduleId;html+=`<button class="calendar-day ${date===iso()?'today':''} ${a?'completed':p?'planned':''} ${sel?'selected':''}" data-date="${date}" data-schedule-id="${p?.id||''}"><span>${d}</span>${a?`<small class="plan-badge">${a.code} ✓</small>`:p?`<small class="plan-badge">${p.code}</small>`:''}</button>`}return html}
function renderCalendars(){const title=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(viewed);$$('[data-calendar-title]').forEach(e=>e.textContent=title);$$('[data-calendar-grid]').forEach(e=>e.innerHTML=monthMarkup())}
function nextPlanned(){return snapshot.schedule.filter(x=>['planned','confirmed','started'].includes(x.status)).sort((a,b)=>a.date.localeCompare(b.date))[0]}
function lineChart(el,rows,key,label){if(!el)return;if(!rows.length){el.innerHTML='<div class="chart-empty">Noch keine Daten</div>';return}const vals=rows.map(r=>Number(r[key])).filter(Number.isFinite);if(!vals.length){el.innerHTML='<div class="chart-empty">Noch keine Daten</div>';return}const min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,w=320,h=150,p=18;const pts=vals.map((v,i)=>`${p+i*((w-2*p)/Math.max(1,vals.length-1))},${h-p-(v-min)/span*(h-2*p)}`).join(' ');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" class="chart" role="img" aria-label="${label}"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><text x="${p}" y="14" font-size="11" fill="currentColor">${max.toFixed(1)}</text><text x="${p}" y="${h-3}" font-size="11" fill="currentColor">${min.toFixed(1)}</text></svg>`}
function render(){const next=nextPlanned(),latest=snapshot.weights?.at(-1);$('#next-workout').textContent=next?`Training ${next.code}`:'Training planen';$('#next-date').textContent=next?new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(pd(next.date)):'Noch kein Termin';$('#completed-count').textContent=snapshot.completed.length;$('#week-count').textContent=snapshot.completed.filter(x=>Math.abs(new Date()-pd(x.date))<7*864e5).length;$('#streak-count').textContent='0';$('#latest-weight').textContent=latest?`${Number(latest.weight_kg).toFixed(1)} kg`:'Noch kein Gewicht';$('#workout-list').innerHTML=Object.values(snapshot.workouts).sort((a,b)=>a.sequence_position-b.sequence_position).map(w=>`<article class="workout-card"><p class="eyebrow">EINHEIT ${w.code}</p><h3>${w.title}</h3><p>${w.focus||''}</p><button data-workout="${w.code}">Plan ansehen</button></article>`).join('');renderCalendars();lineChart($('#weight-chart'),snapshot.weights||[],'weight_kg','Gewichtsverlauf');lineChart($('#waist-chart'),snapshot.measurements||[],'waist_cm','Bauchumfang');updateStatus()}

function setTab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));closeDrawer();window.scrollTo({top:0,behavior:'smooth'})}
function openDrawer(){$('#drawer').classList.add('open');$('#drawer-backdrop').classList.remove('hidden')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer-backdrop').classList.add('hidden')}
function openWorkout(code){const w=snapshot?.workouts?.[code];if(!w)return addError('Training konnte nicht geöffnet werden',`Einheit ${code} wurde nicht gefunden.`);currentCode=code;$('#dialog-title').textContent=w.title;$('#exercise-list').innerHTML=w.exercises.map(ex=>`<article class="exercise-card"><div class="exercise-image">${ex.image_path?`<img src="${ex.image_path}" alt="${ex.name}">`:'Gerätebild folgt'}</div><div class="exercise-body"><h3>${ex.name}</h3><p>${ex.target_sets} × ${ex.rep_min}–${ex.rep_max} · ${ex.rest_seconds} Sek.</p></div></article>`).join('');timerElapsed=0;timerStartedAt=null;clearInterval(timerInterval);$('#workout-timer').textContent='00:00';$('#timer-toggle').textContent='Training starten';$('#workout-dialog').showModal()}
function toggleTimer(){if(timerStartedAt){timerElapsed+=Date.now()-timerStartedAt;timerStartedAt=null;clearInterval(timerInterval);$('#timer-toggle').textContent='Fortsetzen';return}timerStartedAt=Date.now();$('#timer-toggle').textContent='Pause';timerInterval=setInterval(()=>{const sec=Math.floor((timerElapsed+Date.now()-timerStartedAt)/1000);$('#workout-timer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`},1000)}

function futureDates(start,count){const dates=[start];let d=pd(start);while(dates.length<count){d.setDate(d.getDate()+1);if([2,4,6].includes(d.getDay())&&((pd(dates.at(-1))-d)/864e5<=-1))dates.push(iso(d))}return dates}
async function rotateRemote(id,date){const sorted=snapshot.schedule.filter(x=>x.date>=snapshot.schedule.find(s=>s.id===id).date).sort((a,b)=>a.date.localeCompare(b.date));const dates=futureDates(date,sorted.length);for(let i=0;i<sorted.length;i++){const temp=`2099-12-${String(i+1).padStart(2,'0')}`;const r=await supabase.from('scheduled_workouts').update({scheduled_date:temp}).eq('id',sorted[i].id);if(r.error)throw r.error}for(let i=0;i<sorted.length;i++){const r=await supabase.from('scheduled_workouts').update({scheduled_date:dates[i],status:'planned'}).eq('id',sorted[i].id);if(r.error)throw r.error}}
async function deleteScheduleRemote(id){const r=await supabase.from('scheduled_workouts').delete().eq('id',id);if(r.error)throw r.error}
async function createScheduleRemote(code,date){const w=snapshot.workouts[code];const r=await supabase.from('scheduled_workouts').insert({user_id:session.user.id,plan_workout_id:w.id,scheduled_date:date,status:'planned'});if(r.error)throw r.error}
async function moveSchedule(id,date){if(!online()){queue({type:'rotate',id,date});const item=snapshot.schedule.find(x=>x.id===id);const future=snapshot.schedule.filter(x=>x.date>=item.date).sort((a,b)=>a.date.localeCompare(b.date)),dates=futureDates(date,future.length);future.forEach((x,i)=>x.date=dates[i]);write(SNAP,snapshot);selectedScheduleId=null;render();return}await rotateRemote(id,date);await loadRemote();selectedScheduleId=null;render()}
async function removeSchedule(id){if(!online()){queue({type:'deleteSchedule',id});snapshot.schedule=snapshot.schedule.filter(x=>x.id!==id);write(SNAP,snapshot);render();return}await deleteScheduleRemote(id);await loadRemote();render()}
async function createSchedule(code,date){if(!online()){queue({type:'createSchedule',code,date});snapshot.schedule.push({id:`local-${Date.now()}`,date,status:'planned',code});snapshot.schedule.sort((a,b)=>a.date.localeCompare(b.date));write(SNAP,snapshot);render();return}await createScheduleRemote(code,date);await loadRemote();render()}
function openPlanning(date,id=''){const item=snapshot.schedule.find(x=>x.id===id);$('#planning-date').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long'}).format(pd(date));$('#planning-dialog').dataset.date=date;$('#planning-dialog').dataset.id=id;$('#planning-existing').classList.toggle('hidden',!item);$('#planning-new').classList.toggle('hidden',!!item);$('#planning-current').textContent=item?`Training ${item.code}`:'';$('#planning-dialog').showModal()}
async function calendarClick(e){const b=e.target.closest('[data-date]');if(!b)return;const date=b.dataset.date,id=b.dataset.scheduleId;if(selectedScheduleId){try{await moveSchedule(selectedScheduleId,date);$$('.calendar-help').forEach(x=>x.textContent='Training antippen, um es zu ändern.')}catch(err){addError('Termin konnte nicht verschoben werden',err.message)}return}openPlanning(date,id)}

async function insertWeight(payload){const r=await supabase.from('weigh_ins').insert(payload);if(r.error)throw r.error}
async function insertMeasurement(payload){const r=await supabase.from('body_measurements').insert(payload);if(r.error)throw r.error}
function chipValue(group){return $(`[data-chip-group="${group}"] .chip.active`)?.dataset.value||'unknown'}
async function saveWeight(){const v=Number(String($('#weight-input').value).replace(',','.'));if(!v||v<30||v>300)return $('#weight-status').textContent='Bitte gültiges Gewicht eingeben.';const payload={user_id:session.user.id,weight_kg:v,toilet_status:chipValue('toilet'),food_status:chipValue('food'),late_meal:chipValue('late'),unusual_time:$('#weight-unusual').checked,trained_previous_day:$('#weight-trained').checked};if(!online()){queue({type:'weight',payload});snapshot.weights.push({measured_at:new Date().toISOString(),weight_kg:v});write(SNAP,snapshot)}else{await insertWeight(payload);await loadRemote()}$('#weight-dialog').close();render()}
async function saveMeasurement(){const num=id=>{const v=Number(String($(id).value).replace(',','.'));return v||null};const payload={user_id:session.user.id,waist_cm:num('#m-waist'),chest_cm:num('#m-chest'),upper_arm_left_cm:num('#m-arm-left'),upper_arm_right_cm:num('#m-arm-right'),shoulder_cm:num('#m-shoulder')};if(!Object.values(payload).some((v,k)=>k&&v))return $('#measurement-status').textContent='Mindestens einen Wert eintragen.';if(!online()){queue({type:'measurement',payload});snapshot.measurements.push({measured_at:new Date().toISOString(),...payload});write(SNAP,snapshot)}else{await insertMeasurement(payload);await loadRemote()}$('#measurement-dialog').close();render()}

async function enter(){showOnly($('#loading'));clearErrors();try{if(online())await loadRemote();else snapshot=read(SNAP,null)||structuredClone(fallback)}catch(err){snapshot=read(SNAP,null)||structuredClone(fallback);addError('Datenbank konnte nicht vollständig geladen werden',err.message)}showOnly($('#dashboard'));render();syncQueue().then(async()=>{if(online()&&!read(QUEUE,[]).length){try{await loadRemote();render()}catch{}}})}
async function boot(){document.documentElement.dataset.theme=localStorage.getItem(THEME)||'light';if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});const r=await supabase.auth.getSession();session=r.data.session;if(session)await enter();else showOnly($('#login-screen'))}

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const r=await supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(r.error)return $('#login-error').textContent=`Anmeldung fehlgeschlagen: ${r.error.message}`;session=r.data.session;await enter()});
$('#logout').onclick=async()=>{await supabase.auth.signOut();session=null;showOnly($('#login-screen'))};
$('#theme-toggle').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem(THEME,t)};
$('#offline-toggle').onclick=async()=>{manualOffline=!manualOffline;localStorage.setItem(OFFLINE,manualOffline?'1':'0');updateStatus();if(!manualOffline){await syncQueue();await enter()}};
$('#menu-toggle').onclick=openDrawer;$('#drawer-close').onclick=closeDrawer;$('#drawer-backdrop').onclick=closeDrawer;
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-drawer-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.drawerTab));
$('#start-workout').onclick=()=>openWorkout(nextPlanned()?.code||'A');$('#change-next').onclick=()=>{const n=nextPlanned();if(n){selectedScheduleId=n.id;setTab('calendar');renderCalendars()}};
$('#workout-list').onclick=e=>{const b=e.target.closest('[data-workout]');if(b)openWorkout(b.dataset.workout)};$('#close-dialog').onclick=()=>$('#workout-dialog').close();$('#timer-toggle').onclick=toggleTimer;
$$('[data-prev-month]').forEach(b=>b.onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()-1,1);renderCalendars()});$$('[data-next-month]').forEach(b=>b.onclick=()=>{viewed=new Date(viewed.getFullYear(),viewed.getMonth()+1,1);renderCalendars()});$$('[data-calendar-grid]').forEach(g=>g.onclick=calendarClick);
$('#planning-close').onclick=()=>$('#planning-dialog').close();$('#planning-move').onclick=()=>{selectedScheduleId=$('#planning-dialog').dataset.id;$('#planning-dialog').close();$$('.calendar-help').forEach(x=>x.textContent='Jetzt den neuen Tag antippen. Alle folgenden Termine werden angepasst.');renderCalendars()};$('#planning-delete').onclick=async()=>{const id=$('#planning-dialog').dataset.id;$('#planning-dialog').close();try{await removeSchedule(id)}catch(e){addError('Termin konnte nicht entfernt werden',e.message)}};$$('[data-plan-code]').forEach(b=>b.onclick=async()=>{const date=$('#planning-dialog').dataset.date;$('#planning-dialog').close();try{await createSchedule(b.dataset.planCode,date)}catch(e){addError('Training konnte nicht geplant werden',e.message)}});
$('#open-weight').onclick=$('#open-weight-2').onclick=()=>$('#weight-dialog').showModal();$('#close-weight').onclick=()=>$('#weight-dialog').close();$('#save-weight').onclick=()=>saveWeight().catch(e=>$('#weight-status').textContent=e.message);
$('#open-measurement').onclick=$('#open-measurement-2').onclick=()=>$('#measurement-dialog').showModal();$('#close-measurement').onclick=()=>$('#measurement-dialog').close();$('#save-measurement').onclick=()=>saveMeasurement().catch(e=>$('#measurement-status').textContent=e.message);
$$('[data-chip-group]').forEach(g=>g.onclick=e=>{const c=e.target.closest('.chip');if(!c)return;g.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===c))});
window.addEventListener('online',()=>{updateStatus();syncQueue()});window.addEventListener('offline',updateStatus);
supabase.auth.onAuthStateChange((_e,s)=>{session=s;if(!s)showOnly($('#login-screen'))});boot();