const C_HISTORY='gym-coach-history-v23';
const T_HISTORY='gym-tracking-history-v18';
const q31=(s,r=document)=>r.querySelector(s),qa31=(s,r=document)=>[...r.querySelectorAll(s)];
const read31=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const num31=v=>Number(String(v??'').replace(',','.'));
const variant31=card=>q31('[data-name]',card)?.textContent.trim()||q31('h3',card)?.textContent.trim()||'';
const workSets31=sets=>(sets||[]).filter(s=>!s.warmup&&(num31(s.weight)>0||num31(s.reps)>0));
function latest31(name){const a=read31(C_HISTORY,{}),b=read31(T_HISTORY,{});return a[name]||b[name]||null}
function fmt31(sets){const x=workSets31(sets);return x.length?x.map(s=>`${num31(s.weight).toLocaleString('de-DE',{maximumFractionDigits:2})} kg × ${num31(s.reps)||0}`).join(' · '):'Noch keine Arbeitssätze an diesem Gerät gespeichert.'}
function coachDecision31(card,row){const data=row?.sets||[],sets=workSets31(data),meta=q31('.exercise-v18-head p',card)?.textContent||'',range=meta.match(/(\d+)\s*[–-]\s*(\d+)/),max=range?Number(range[2]):12;if(!sets.length)return{title:'Erste Referenz setzen',text:'Trainiere heute sauber und speichere die Arbeitssätze genau an diesem Gerät.'};const weights=sets.map(s=>num31(s.weight)).filter(n=>n>0),reps=sets.map(s=>num31(s.reps)).filter(n=>n>0),same=weights.length&&weights.every(x=>x===weights[0]),allTop=reps.length===sets.length&&reps.every(x=>x>=max);if(allTop&&same)return{title:'Gewichtserhöhung prüfen',text:`Alle Arbeitssätze lagen bei mindestens ${max} Wiederholungen. Wähle an diesem Gerät den nächsten real verfügbaren Gewichtsschritt.`};const target=reps.map(r=>Math.min(max,r+1));return{title:'Heute steigern',text:`Gewicht an diesem Gerät beibehalten. Ziel: ${target.join(' / ')} Wiederholungen.`}}
function buildCoach31(card){if(!card?.dataset?.v18)return;const existing=q31('.coach-v31',card);if(existing)existing.remove();const name=variant31(card),row=latest31(name),decision=coachDecision31(card,row);const box=document.createElement('section');box.className='coach-v31';box.dataset.device=name;box.innerHTML=`<button type="button" class="coach-v31-toggle"><span>Coach</span><strong>${decision.title}</strong><span>›</span></button><div class="coach-v31-body"><div><small>Letztes Training an diesem Gerät</small><p>${fmt31(row?.sets)}</p></div><div><small>Empfehlung heute</small><p>${decision.text}</p></div><button type="button" class="coach-history-v31">Verlauf anzeigen</button><div class="coach-history-list-v31 hidden"></div></div>`;const anchor=q31('.tracking-summary',card)||q31('.variant-shell',card);anchor?.insertAdjacentElement('afterend',box);q31('.coach-v31-toggle',box).onclick=()=>q31('.coach-v31-body',box).classList.toggle('open');q31('.coach-history-v31',box).onclick=e=>{const list=q31('.coach-history-list-v31',box),history=read31('gym-coach-log-v31',{})[name]||[];list.classList.toggle('hidden');list.innerHTML=history.length?history.slice().reverse().map(x=>`<article><small>${new Date(x.date).toLocaleDateString('de-DE')}</small><p>${fmt31(x.sets)}</p></article>`).join(''):'<p>Noch kein Verlauf für dieses Gerät vorhanden.</p>';e.currentTarget.textContent=list.classList.contains('hidden')?'Verlauf anzeigen':'Verlauf schließen'}}
function archive31(){const log=read31('gym-coach-log-v31',{});qa31('#exercise-list .exercise-card[data-v18]').forEach(card=>{const name=variant31(card),sets=qa31('.set-row:not(.header)',card).map(r=>({weight:q31('[data-weight]',r)?.value||'',reps:q31('[data-reps]',r)?.value||'',rir:q31('[data-rir]',r)?.value||'',warmup:Boolean(q31('[data-warmup]',r)?.checked)})).filter(s=>s.weight||s.reps||s.rir||s.warmup);if(!name||!sets.length)return;log[name]=log[name]||[];log[name].push({date:new Date().toISOString(),sets});log[name]=log[name].slice(-20)});localStorage.setItem('gym-coach-log-v31',JSON.stringify(log))}
function enhance31(){qa31('#exercise-list .exercise-card[data-v18]').forEach(buildCoach31)}
document.addEventListener('click',e=>{if(e.target.closest('[data-workout],#start-workout,.exercise-step-v30,.training-next-v30,.training-prev-v30'))setTimeout(enhance31,100);if(e.target.closest('#complete-workout'))archive31()},true);
document.addEventListener('gym:variant-changed',e=>{const card=e.detail?.card;if(card)setTimeout(()=>buildCoach31(card),20)});
window.addEventListener('load',()=>setTimeout(enhance31,900));
