const PHOTO_DB='gym-progress-photos-v36';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
let stream=null,currentPose='front';

function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(PHOTO_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function savePhoto(record){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function deletePhoto(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function listPhotos(){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction('photos').objectStore('photos').getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))));req.onerror=()=>reject(req.error)})}
const poseLabel=p=>({front:'Front',left:'Links',right:'Rechts',back:'Rücken'})[p]||'Foto';

function markup(){return`<section class="photo-app"><article class="photo-capture-card"><div class="photo-head"><div><small>FORTSCHRITTSFOTOS</small><h2>Vergleichbare Aufnahmen</h2><p>Gleicher Abstand, gleiche Höhe, gleiche Haltung. So werden Veränderungen später wirklich sichtbar.</p></div></div><div class="pose-tabs"><button class="active" data-photo-pose="front">Front</button><button data-photo-pose="left">Links</button><button data-photo-pose="right">Rechts</button><button data-photo-pose="back">Rücken</button></div><div class="camera-stage"><video id="photo-video" playsinline muted></video><canvas id="photo-canvas" hidden></canvas><div class="body-guide" data-pose="front" aria-hidden="true"><span class="guide-head"></span><span class="guide-shoulders"></span><span class="guide-torso"></span><span class="guide-hips"></span><span class="guide-leg left"></span><span class="guide-leg right"></span><small>Füße an die Markierung · Kamera auf Brusthöhe</small></div></div><div class="photo-actions"><button id="camera-start" class="secondary">Kamera starten</button><button id="camera-capture" class="primary" disabled>Foto aufnehmen</button><button id="camera-stop" class="secondary" disabled>Kamera stoppen</button></div><label class="photo-upload">Vorhandenes Foto hinzufügen<input id="photo-file" type="file" accept="image/*"></label><p id="photo-status" class="photo-status"></p></article><section class="photo-gallery-wrap"><div class="photo-gallery-head"><div><small>VERLAUF</small><h3>Deine Fotos</h3></div><span id="photo-count"></span></div><div id="photo-gallery" class="photo-gallery"></div></section></section>`}

async function renderGallery(){const root=q('#photo-gallery'),count=q('#photo-count');if(!root)return;const rows=await listPhotos();if(count)count.textContent=`${rows.length} ${rows.length===1?'Foto':'Fotos'}`;root.innerHTML=rows.length?rows.map(r=>`<article class="photo-tile" data-photo-id="${r.id}"><button class="photo-image-button" type="button" data-photo-open><img src="${r.data_url}" alt="${poseLabel(r.pose)} vom ${new Date(r.created_at).toLocaleDateString('de-DE')}"></button><div class="photo-meta"><div><strong>${poseLabel(r.pose)}</strong><small>${new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(r.created_at))}</small></div><button type="button" data-photo-delete>Entfernen</button></div></article>`).join(''):'<div class="photo-empty">Noch keine Fortschrittsfotos gespeichert.</div>'}

function build(){const page=q('#page-photos');if(!page)return;page.querySelector('.photo-placeholder')?.remove();let app=q('.photo-app',page);if(!app){page.insertAdjacentHTML('beforeend',markup());bind()}renderGallery()}
async function startCamera(){const status=q('#photo-status');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1440},height:{ideal:1920}},audio:false});const video=q('#photo-video');video.srcObject=stream;await video.play();q('#camera-capture').disabled=false;q('#camera-stop').disabled=false;q('#camera-start').disabled=true;status.textContent='Kamera aktiv. Stelle dich in die feine Kontur.'}catch(e){status.textContent=`Kamera konnte nicht geöffnet werden: ${e.message}`}}
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;const video=q('#photo-video');if(video)video.srcObject=null;if(q('#camera-capture'))q('#camera-capture').disabled=true;if(q('#camera-stop'))q('#camera-stop').disabled=true;if(q('#camera-start'))q('#camera-start').disabled=false}
async function capture(){const video=q('#photo-video'),canvas=q('#photo-canvas'),status=q('#photo-status');if(!video?.videoWidth)return;const max=1600,scale=Math.min(1,max/video.videoHeight);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const data_url=canvas.toDataURL('image/jpeg',.86);await savePhoto({id:crypto.randomUUID(),pose:currentPose,created_at:new Date().toISOString(),data_url});status.textContent='Foto gespeichert.';await renderGallery()}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
async function addFile(file){if(!file)return;const status=q('#photo-status');try{const data_url=await fileToDataUrl(file);await savePhoto({id:crypto.randomUUID(),pose:currentPose,created_at:new Date().toISOString(),data_url});status.textContent='Foto hinzugefügt.';await renderGallery()}catch(e){status.textContent=`Foto konnte nicht gespeichert werden: ${e.message}`}}
function openPhoto(tile){const src=q('img',tile)?.src;if(!src)return;let d=q('#photo-viewer');if(!d){d=document.createElement('dialog');d.id='photo-viewer';d.className='photo-viewer';document.body.append(d)}d.innerHTML=`<div><button type="button" data-photo-close>Schließen</button><img src="${src}" alt="Fortschrittsfoto"></div>`;q('[data-photo-close]',d).onclick=()=>d.close();d.showModal()}
function bind(){q('#camera-start').onclick=startCamera;q('#camera-stop').onclick=stopCamera;q('#camera-capture').onclick=capture;q('#photo-file').onchange=e=>addFile(e.target.files?.[0]);qa('[data-photo-pose]').forEach(b=>b.onclick=()=>{currentPose=b.dataset.photoPose;qa('[data-photo-pose]').forEach(x=>x.classList.toggle('active',x===b));q('.body-guide').dataset.pose=currentPose});q('#photo-gallery').onclick=async e=>{const tile=e.target.closest('.photo-tile');if(!tile)return;if(e.target.closest('[data-photo-open]'))return openPhoto(tile);if(e.target.closest('[data-photo-delete]')){if(!confirm('Dieses Foto entfernen?'))return;await deletePhoto(tile.dataset.photoId);await renderGallery()}}}
function install(){build();document.addEventListener('click',e=>{if(e.target.closest('[data-page="photos"],[data-page-link="photos"]'))setTimeout(build,30)},true);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')stopCamera()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
