import './studio-page-v35.js';
import './device-photo-v36.js';
import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './supabase-config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

function fixHeader(){
 const line=$('.status-line');if(line)line.style.setProperty('display','none','important');
 ['#offline-toggle','#sync-now','#connection-status','#sync-count'].forEach(s=>{const el=$(s);if(el)el.style.setProperty('display','none','important')});
 const title=$('#page-title');if(title){const base=title.textContent.replace(/\s+Dave$/,'').replace(/^Dave\s*[·-]\s*/,'').trim()||'Dashboard';title.textContent=`${base} Dave`}
}
function ensureStudioEntry(){const nav=$('#drawer nav');if(!nav)return;if(!nav.querySelector('[data-page="studio"]')){const b=document.createElement('button');b.type='button';b.dataset.page='studio';b.textContent='Studio';nav.insertBefore(b,nav.querySelector('[data-page="settings"]')||null)}}
function forcePhotos(){const page=$('#page-photos');if(!page)return;page.querySelector('.photo-placeholder')?.remove();window.dispatchEvent(new Event('load'))}
function scheduleRows(){return $$('[data-calendar-grid]:first-of-type .calendar-day.planned').map(b=>({date:b.dataset.date,code:b.querySelector('.plan-badge')?.textContent.trim().charAt(0)})).filter(x=>x.code)}
function invalid(rows){for(let i=1;i<rows.length;i++){const days=Math.round((new Date(rows[i].date+'T12:00:00')-new Date(rows[i-1].date+'T12:00:00'))/86400000);if(rows[i].code===rows[i-1].code||days<3)return true}return false}
function showRepair(){if($('#schedule-repair-v37'))return;const stack=$('#error-stack');if(!stack)return;const box=document.createElement('article');box.id='schedule-repair-v37';box.className='error-banner';box.innerHTML='<strong>Kalenderfolge ist fehlerhaft</strong><p>Die zukünftigen Termine enthalten Doppelungen oder liegen zu dicht zusammen.</p><button type="button" id="repair-v37">A/B-Folge jetzt reparieren</button><button type="button" class="close-v37">×</button>';box.querySelector('.close-v37').onclick=()=>box.remove();box.querySelector('#repair-v37').onclick=repair;stack.prepend(box)}
async function repair(){const btn=$('#repair-v37');try{btn.disabled=true;btn.textContent='Repariere …';const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Bitte neu anmelden.');const plan=await supabase.from('training_plans').select('id').eq('is_active',true).order('version',{ascending:false}).limit(1).single();if(plan.error)throw plan.error;const pws=await supabase.from('plan_workouts').select('id,code').eq('plan_id',plan.data.id);if(pws.error)throw pws.error;const byCode=Object.fromEntries(pws.data.map(x=>[x.code,x.id]));const last=await supabase.from('workouts').select('workout_date,plan_workout_id').in('status',['completed','partial']).order('workout_date',{ascending:false}).limit(1);if(last.error)throw last.error;const latest=last.data?.[0];let start=new Date();let next='A';if(latest){start=new Date(latest.workout_date+'T12:00:00');start.setDate(start.getDate()+3);next=pws.data.find(x=>x.id===latest.plan_workout_id)?.code==='A'?'B':'A'}else{start.setHours(12,0,0,0);start.setDate(start.getDate()+1)}const del=await supabase.from('scheduled_workouts').delete().in('status',['planned','confirmed','started']);if(del.error)throw del.error;const rows=[];for(let i=0;i<20;i++){const d=new Date(start);d.setDate(start.getDate()+i*3);rows.push({user_id:session.user.id,plan_workout_id:byCode[i%2===0?next:(next==='A'?'B':'A')],scheduled_date:new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d),status:'planned'})}const ins=await supabase.from('scheduled_workouts').insert(rows);if(ins.error)throw ins.error;localStorage.removeItem('gym-snapshot-v11');location.reload()}catch(e){btn.disabled=false;btn.textContent='Erneut versuchen';const p=$('#schedule-repair-v37 p');if(p)p.textContent=e.message||String(e)}}
function install(){fixHeader();ensureStudioEntry();forcePhotos();if(invalid(scheduleRows()))showRepair()}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;install()})});observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true});document.addEventListener('DOMContentLoaded',install);window.addEventListener('load',()=>{install();setTimeout(install,200);setTimeout(install,1000)});window.addEventListener('online',fixHeader);window.addEventListener('offline',fixHeader);setInterval(()=>{fixHeader();ensureStudioEntry()},5000);
