import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const SNAP='gym-snapshot-v11',QUEUE='gym-queue-v11',OFF='gym-offline-v11',BLOCKED='gym-schedule-blocked-days',ACK='gym-schedule-missed-v2';
const ACTIVE=new Set(['planned','confirmed','started']);
const q=(s,r=document)=>r.querySelector(s);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(new Date());
const pd=v=>new Date(`${v}T12:00:00`),iso=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(d);
const add=(v,n)=>{const d=pd(v);d.setDate(d.getDate()+n);return iso(d)};
const fmt=v=>new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(pd(v));
const other=c=>c==='A'?'B':'A';
const snap=()=>read(SNAP,{workouts:{},schedule:[],completed:[]});
const online=()=>navigator.onLine&&localStorage.getItem(OFF)!=='1';
const blocked=()=>new Set(read(BLOCKED,[]));
const acks=()=>read(ACK,[]);
const ackKey=x=>`${x?.date||x?.scheduled_date||''}|${x?.code||''}`;
const acknowledged=x=>acks().some(a=>(a.id&&x.id&&String(a.id)===String(x.id))||ackKey(a)===ackKey(x));
function remember(item,decision){const list=acks().filter(a=>!((a.id&&item.id&&String(a.id)===String(item.id))||ackKey(a)===ackKey(item)));list.push({id:item.id||null,date:item.date,code:item.code,decision,at:new Date().toISOString()});write(ACK,list.slice(-40))}
function completed(s){return [...(s.completed||[])].filter(x=>x.code==='A'||x.code==='B').sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function expectedCode(s){const rows=completed(s);return rows.length?other(rows.at(-1).code):'A'}
function activeRows(s){const done=new Set(completed(s).map(x=>`${x.date}|${x.code}`));return (s.schedule||[]).filter(x=>ACTIVE.has(x.status)&&(x.code==='A'||x.code==='B')&&!done.has(`${x.date}|${x.code}`)&&!acknowledged(x)).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function actionable(s){const rows=activeRows(s),expected=expectedCode(s);return rows.find(x=>x.code===expected)||rows[0]||null}
function avoid(date){let d=date,b=blocked();for(let i=0;i<15;i++){const monday=d>='2026-09-01'&&pd(d).getDay()===1;if(!monday&&!b.has(d))return d;d=add(d,1)}return d}
function build(start,code){const rows=[];let d=avoid(start),c=code,end=add(today(),32);while(d<=end&&rows.length<40){rows.push({date:d,code:c});d=avoid(add(d,2));c=other(c)}return rows}
function ids(s){return Object.fromEntries(Object.values(s.workouts||{}).map(w=>[w.code,w.id]))}
function queue(item){const list=read(QUEUE,[]);list.push({...item,queued_at:new Date().toISOString()});write(QUEUE,list);window.dispatchEvent(new Event('gym:schedule-refresh'))}
function mirrorSkippedAndRotation(s,item,start,code){const map=ids(s),rotation=build(start,code);const old=(s.schedule||[]).map(x=>String(x.id)===String(item.id)||(!item.id&&x.date===item.date&&x.code===item.code)?{...x,status:'skipped'}:x);s.schedule=old.filter(x=>x.date<start||!ACTIVE.has(x.status));for(const r of rotation)s.schedule.push({id:`local-${crypto.randomUUID()}`,scheduled_date:r.date,date:r.date,code:r.code,plan_workout_id:map[r.code],status:'planned'});s.schedule.sort((a,b)=>String(a.date).localeCompare(String(b.date)));write(SNAP,s);remember(item,'no');renderHero();window.dispatchEvent(new Event('gym:schedule-refresh'));return rotation}
function renderHero(){const s=snap(),item=actionable(s),code=expectedCode(s),title=q('#next-workout'),date=q('#next-date'),start=q('#start-workout');if(!title||!date||!start)return;const label=title.closest('.hero')?.querySelector('small');if(!item){if(label)label.textContent='Als Nächstes';title.textContent=`Training ${code}`;date.textContent='Noch kein Termin festgelegt';start.dataset.workout=code;delete start.dataset.scheduleDate;return}if(label)label.textContent=item.date<today()?'Offenes Training':item.date===today()?'Heute':'Als Nächstes';title.textContent=`Training ${item.code}`;date.textContent=item.date<today()?`${fmt(item.date)} · nicht erledigt`:item.date===today()?`Heute · ${fmt(item.date)}`:fmt(item.date);start.dataset.workout=item.code;start.dataset.scheduleDate=item.date}

async function getUser(){const r=await supabase.auth.getSession();if(r.error||!r.data.session)throw r.error||new Error('Keine Sitzung');return r.data.session.user}
async function syncMissed(item){const u=await getUser(),s=snap(),map=ids(s),rotation=item.rotation||build(item.newDate,item.code);let req=supabase.from('scheduled_workouts').update({status:'skipped'}).eq('user_id',u.id);if(item.id&&!String(item.id).startsWith('local-'))req=req.eq('id',item.id);else req=req.eq('scheduled_date',item.date).eq('plan_workout_id',map[item.code]);const sk=await req.select('id');if(sk.error)throw sk.error;const del=await supabase.from('scheduled_workouts').delete().eq('user_id',u.id).gte('scheduled_date',item.newDate).in('status',['planned','confirmed','started']);if(del.error)throw del.error;if(rotation.length){const ins=await supabase.from('scheduled_workouts').insert(rotation.map(r=>({user_id:u.id,plan_workout_id:map[r.code],scheduled_date:r.date,status:'planned'})));if(ins.error)throw ins.error}}
async function flush(){if(!online())return;const list=read(QUEUE,[]),rest=[];for(const item of list){if(item.type!=='rescheduleMissed'){rest.push(item);continue}try{await syncMissed(item)}catch{rest.push(item);break}}write(QUEUE,rest);if(rest.length!==list.length)window.dispatchEvent(new CustomEvent('gym:snapshot-hydrated'))}

function ensureDialog(){let d=q('#missed-clean');if(d)return d;d=document.createElement('dialog');d.id='missed-clean';d.innerHTML='<div style="padding:20px;min-width:min(88vw,430px)"><div style="display:flex;justify-content:space-between;gap:12px"><div><small>TRAINING KLÄREN</small><h2 data-missed-title style="margin:.25rem 0"></h2></div><button type="button" data-close>×</button></div><p data-copy style="color:#737973;line-height:1.45"></p><div data-q style="display:grid;gap:9px"><button class="primary" type="button" data-yes>Ja, durchgeführt</button><button class="secondary" type="button" data-no>Nein, nicht gemacht</button></div><div data-plan hidden style="display:grid;gap:9px;margin-top:12px"><label style="display:grid;gap:6px">Wann ist dein nächstes Training?<input type="date" data-date></label><button class="primary" type="button" data-save>Termin übernehmen</button><small data-status></small></div></div>';document.body.append(d);q('[data-close]',d).onclick=()=>d.close();q('[data-no]',d).onclick=()=>{q('[data-q]',d).hidden=true;q('[data-plan]',d).hidden=false;q('[data-date]',d).value=today()};q('[data-yes]',d).onclick=()=>{const s=snap(),item=actionable(s);if(!item)return d.close();remember(item,'yes');const start=q('#start-workout');if(start){start.dataset.workout=item.code;start.dataset.scheduleDate=item.date}d.close();q(`#workout-list [data-workout="${item.code}"]`)?.click()};q('[data-save]',d).onclick=async()=>{const s=snap(),item=actionable(s),value=q('[data-date]',d).value,status=q('[data-status]',d);if(!item)return d.close();if(!value||value<today()){status.textContent='Bitte heute oder ein zukünftiges Datum wählen.';return}const code=expectedCode(s),rotation=mirrorSkippedAndRotation(s,item,value,code);queue({type:'rescheduleMissed',id:item.id,date:item.date,code:item.code,newDate:value,rotation});d.close();if(online())setTimeout(()=>flush(),100)};return d}
function maybeAsk(){const s=snap(),item=actionable(s);if(!item||item.date>=today())return;const d=ensureDialog();if(d.open)return;q('[data-missed-title]',d).textContent=`Training ${item.code} vom ${fmt(item.date)}`;q('[data-copy]',d).textContent=`Für ${fmt(item.date)} war Training ${item.code} geplant, aber es ist kein abgeschlossenes Training gespeichert. Hast du trainiert?`;q('[data-q]',d).hidden=false;q('[data-plan]',d).hidden=true;q('[data-status]',d).textContent='';d.showModal()}
function interceptStart(e){const b=e.target.closest('#start-workout');if(!b)return;const s=snap(),item=actionable(s);if(item?.date<today()){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();maybeAsk()}}

function installBlockDays(){const page=q('#page-calendar');if(!page||q('#block-days-button',page))return;const head=q('.page-head>div:last-child',page)||q('.page-head',page),btn=document.createElement('button');btn.id='block-days-button';btn.className='secondary';btn.textContent='Blocktage';btn.style.marginLeft='8px';head.append(btn);let d=q('#block-days-dialog');if(!d){d=document.createElement('dialog');d.id='block-days-dialog';d.innerHTML='<div style="padding:18px;min-width:min(88vw,420px)"><div style="display:flex;justify-content:space-between"><div><small>PLANUNG</small><h2>Blocktage</h2></div><button data-close>Schließen</button></div><div style="display:grid;grid-template-columns:1fr auto;gap:8px"><input type="date" data-date><button class="primary" data-add>Hinzufügen</button></div><div data-list style="display:grid;gap:8px;margin-top:12px"></div></div>';document.body.append(d)}const paint=()=>{q('[data-list]',d).innerHTML=[...blocked()].sort().map(x=>`<div style="display:flex;justify-content:space-between;padding:9px;border:1px solid #ddd;border-radius:12px"><span>${x}</span><button data-remove="${x}">Entfernen</button></div>`).join('')||'<small>Noch keine Blocktage.</small>';d.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{write(BLOCKED,[...blocked()].filter(x=>x!==b.dataset.remove));paint()})};btn.onclick=()=>{paint();d.showModal()};q('[data-close]',d).onclick=()=>d.close();q('[data-add]',d).onclick=()=>{const v=q('[data-date]',d).value;if(!v)return;const set=blocked();set.add(v);write(BLOCKED,[...set]);paint()}}

function install(){renderHero();installBlockDays();setTimeout(maybeAsk,700);if(online())setTimeout(()=>flush(),1300)}
document.addEventListener('click',interceptStart,true);
window.addEventListener('gym:snapshot-hydrated',()=>{renderHero();setTimeout(maybeAsk,350)});
window.addEventListener('gym:schedule-refresh',renderHero);
window.addEventListener('online',()=>setTimeout(()=>flush(),1500));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
