const STUDIO_KEY='gym-studio-profile-v32';
const q32=(s,r=document)=>r.querySelector(s),qa32=(s,r=document)=>[...r.querySelectorAll(s)];
const read32=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write32=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const CATALOG32=[
'Bauchmuskelmaschine','Bauchmuskelmaschine Crunch liegend','Klappsitz Bauchmaschine sitzend','Klappsitz Bauchmaschine liegend, Plate loaded','Bizepsmaschine','Bizepsmaschine Plate loaded','Scott Curler sitzend','Brustpresse sitzend','Bankdrückmaschine sitzend dual','Bankdrückmaschine liegend dual','Butterfly mit Griffen','Butterfly mit Pads','Schrägbankdrückmaschine dual','Schrägbankmaschine sitzend','Kurzhantel Schrägbankdrücken','Seithebemaschine ohne Armpolster','Seithebemaschine dual ohne Armpolster','Kurzhantel Seitheben sitzend','Kurzhantel Seitheben stehend','Trizepsmaschine über Kopf','Trizepsmaschine horizontal','Trizeps Dip Maschine sitzend dual','Latzugstation mit Oberschenkelpolster','Rückenzugmaschine dual','High Row dual','Rudermaschine mit Brustpolster','Low Row dual','Butterfly reverse mit Griffen','Butterfly reverse mit Pads','Rückenstreckermaschine'];
function default32(){return{studio:'John Reed Essen',updated_at:null,devices:Object.fromEntries(CATALOG32.map(name=>[name,{present:'unknown',rating:'',role:'',setup:{seat:'',backrest:'',chest_pad:'',start_position:'',bench_angle:'',grip:'',weight_steps:'',notes:''}}]))}}
function profile32(){const p=read32(STUDIO_KEY,default32());CATALOG32.forEach(n=>p.devices[n]??=default32().devices[n]);return p}
function card32(name,data){return `<article class="studio-device-v32" data-device="${name.replaceAll('"','&quot;')}"><div class="studio-device-head-v32"><div><strong>${name}</strong><small class="studio-state-v32">${data.present==='yes'?'Vorhanden':data.present==='no'?'Nicht vorhanden':'Noch nicht geprüft'}</small></div><select data-field="present"><option value="unknown" ${data.present==='unknown'?'selected':''}>Noch nicht geprüft</option><option value="yes" ${data.present==='yes'?'selected':''}>Vorhanden</option><option value="no" ${data.present==='no'?'selected':''}>Nicht vorhanden</option></select></div><button type="button" class="studio-details-toggle-v32">Einstellungen</button><div class="studio-details-v32"><label>Verwendung<select data-field="role"><option value="" ${!data.role?'selected':''}>Noch offen</option><option value="standard" ${data.role==='standard'?'selected':''}>Standard</option><option value="alternative" ${data.role==='alternative'?'selected':''}>Alternative</option><option value="avoid" ${data.role==='avoid'?'selected':''}>Nicht verwenden</option></select></label><label>Bewertung<input data-field="rating" inputmode="numeric" placeholder="1–5" value="${data.rating||''}"></label><label>Sitzhöhe<input data-setup="seat" placeholder="z. B. 5" value="${data.setup?.seat||''}"></label><label>Rückenlehne<input data-setup="backrest" placeholder="Position" value="${data.setup?.backrest||''}"></label><label>Brustpolster<input data-setup="chest_pad" placeholder="z. B. 3 / weit heraus" value="${data.setup?.chest_pad||''}"></label><label>Startposition<input data-setup="start_position" placeholder="z. B. Loch 3" value="${data.setup?.start_position||''}"></label><label>Bankwinkel<input data-setup="bench_angle" placeholder="z. B. Loch 2, ca. 20°" value="${data.setup?.bench_angle||''}"></label><label>Griff<input data-setup="grip" placeholder="neutral, breit …" value="${data.setup?.grip||''}"></label><label>Gewichtsstufen<input data-setup="weight_steps" placeholder="z. B. 5-kg-Schritte" value="${data.setup?.weight_steps||''}"></label><label class="studio-notes-v32">Notizen<textarea data-setup="notes" placeholder="Persönliche Einstellung oder Besonderheit">${data.setup?.notes||''}</textarea></label></div></article>`}
function saveFromDom32(root){const p=profile32();p.studio=q32('#studio-select-v32',root)?.value||'John Reed Essen';qa32('.studio-device-v32',root).forEach(card=>{const name=card.dataset.device,d=p.devices[name];d.present=q32('[data-field="present"]',card)?.value||'unknown';d.role=q32('[data-field="role"]',card)?.value||'';d.rating=q32('[data-field="rating"]',card)?.value||'';qa32('[data-setup]',card).forEach(i=>d.setup[i.dataset.setup]=i.value)});p.updated_at=new Date().toISOString();write32(STUDIO_KEY,p);q32('#studio-save-status-v32',root).textContent='Zwischengespeichert.';setTimeout(()=>{const s=q32('#studio-save-status-v32',root);if(s)s.textContent=''},1400)}
function export32(){const p=profile32(),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`john-reed-essen-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
function build32(){if(q32('#studio-manager-v32'))return;const settings=q32('#page-settings');if(!settings)return;const p=profile32(),section=document.createElement('section');section.id='studio-manager-v32';section.className='settings-card studio-manager-v32';section.innerHTML=`<div class="studio-title-v32"><div><small>STUDIOVERWALTUNG</small><h2>Studio und Geräte</h2><p>Du kannst den Katalog über mehrere Trainingstage ergänzen. Alles wird sofort lokal zwischengespeichert.</p></div></div><label>Studio<select id="studio-select-v32"><option>John Reed Essen</option></select></label><div class="studio-toolbar-v32"><input id="studio-search-v32" type="search" placeholder="Gerät suchen"><button type="button" id="studio-export-v32">JSON exportieren</button></div><div id="studio-save-status-v32" class="studio-save-status-v32"></div><div id="studio-list-v32">${CATALOG32.map(n=>card32(n,p.devices[n])).join('')}</div>`;settings.append(section);section.addEventListener('input',()=>saveFromDom32(section));section.addEventListener('change',e=>{saveFromDom32(section);const card=e.target.closest('.studio-device-v32');if(card)q32('.studio-state-v32',card).textContent=e.target.value==='yes'?'Vorhanden':e.target.value==='no'?'Nicht vorhanden':'Noch nicht geprüft'});section.addEventListener('click',e=>{const t=e.target.closest('.studio-details-toggle-v32');if(t)t.nextElementSibling.classList.toggle('open')});q32('#studio-export-v32',section).onclick=export32;q32('#studio-search-v32',section).oninput=e=>{const term=e.target.value.toLowerCase();qa32('.studio-device-v32',section).forEach(c=>c.hidden=!c.dataset.device.toLowerCase().includes(term))}}
document.addEventListener('click',e=>{if(e.target.closest('[data-page="settings"],[data-page-link="settings"]'))setTimeout(build32,40)},true);window.addEventListener('load',()=>setTimeout(build32,900));
