import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY} from './supabase-config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const SNAP='gym-snapshot-v11';
const SESSION='gym-workout-session';
const HISTORY='gym-device-history';
const STUDIO='gym-studio-profile-v35';
const LEGACY_ACTIVE='gym-active-workout-v11';
const q=(s,r=document)=>r.querySelector(s);
const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const canon=v=>String(v||'').toLowerCase().replaceAll('ä','a').replaceAll('ö','o').replaceAll('ü','u').replaceAll('ß','ss').replace(/[^a-z0-9]+/g,' ').trim();
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>num(v)==null?'–':num(v).toLocaleString('de-DE',{maximumFractionDigits:2});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(new Date());

const VARIANTS={
 'Schrägbankdrückmaschine dual':[['Schrägbankdrückmaschine dual','IMG_3062.png'],['Schrägbankmaschine sitzend','IMG_3063.png'],['Kurzhantel Schrägbankdrücken','IMG_3071.png'],['Bankdrückmaschine sitzend dual','IMG_3048.png']],
 'Kurzhantel-Schrägbankdrücken':[['Kurzhantel Schrägbankdrücken','IMG_3071.png'],['Schrägbankdrückmaschine dual','IMG_3062.png'],['Schrägbankmaschine sitzend','IMG_3063.png']],
 'Kurzhantel Schrägbankdrücken':[['Kurzhantel Schrägbankdrücken','IMG_3071.png'],['Schrägbankdrückmaschine dual','IMG_3062.png'],['Schrägbankmaschine sitzend','IMG_3063.png']],
 'Brustpresse sitzend':[['Brustpresse sitzend','IMG_3047.png'],['Bankdrückmaschine sitzend dual','IMG_3048.png'],['Bankdrückmaschine liegend dual','IMG_3049.png']],
 'Butterfly mit Griffen':[['Butterfly mit Griffen','pics_johnreed/IMG_3452.jpeg'],['Butterfly mit Pads','IMG_3051.png']],
 'Seithebemaschine ohne Armpolster':[['Seithebemaschine ohne Armpolster','IMG_3064.png'],['Seithebemaschine dual ohne Armpolster','IMG_3065.png'],['Kurzhantel Seitheben sitzend','IMG_3069.png'],['Kurzhantel Seitheben stehend','IMG_3070.png']],
 'Trizepsmaschine Überkopf':[['Trizepsmaschine über Kopf','IMG_3066.png'],['Trizepsmaschine horizontal','IMG_3067.png'],['Trizeps Dip Maschine sitzend dual','IMG_3068.png']],
 'Trizepsmaschine über Kopf':[['Trizepsmaschine über Kopf','IMG_3066.png'],['Trizepsmaschine horizontal','IMG_3067.png'],['Trizeps Dip Maschine sitzend dual','IMG_3068.png']],
 'Bizepsmaschine':[['Bizepsmaschine','IMG_3044.png'],['Bizepsmaschine Plate loaded','IMG_3045.png'],['Scott Curler sitzend','IMG_3046.png']],
 'Bauchmuskelmaschine':[['Bauchmuskelmaschine','IMG_3040.png'],['Bauchmuskelmaschine Crunch liegend','IMG_3041.png'],['Klappsitz Bauchmaschine sitzend','IMG_3042.png'],['Klappsitz Bauchmaschine liegend, Plate loaded','IMG_3043.png']],
 'Latzugstation mit Oberschenkelpolster':[['Latzugstation mit Oberschenkelpolster',null],['Rückenzugmaschine dual',null],['High Row dual',null]],
 'Rudermaschine mit Brustpolster':[['Rudermaschine mit Brustpolster',null],['Low Row dual',null],['High Row dual',null]],
 'High Row dual':[['High Row dual',null],['Rückenzugmaschine dual',null],['Rudermaschine mit Brustpolster',null]],
 'Low Row dual':[['Low Row dual',null],['Rudermaschine mit Brustpolster',null],['High Row dual',null]],
 'Butterfly reverse mit Griffen':[['Butterfly reverse mit Griffen',null],['Butterfly reverse mit Pads',null]],
 'Rückenstreckermaschine':[['Rückenstreckermaschine',null]]
};
const IMG={
 'butterfly mit griffen':'pics_johnreed/IMG_3452.jpeg','bauchmuskelmaschine':'IMG_3040.png','bauchmuskelmaschine crunch liegend':'IMG_3041.png','klappsitz bauchmaschine sitzend':'IMG_3042.png','klappsitz bauchmaschine liegend plate loaded':'IMG_3043.png','bizepsmaschine':'IMG_3044.png','bizepsmaschine plate loaded':'IMG_3045.png','scott curler sitzend':'IMG_3046.png','brustpresse sitzend':'IMG_3047.png','bankdruckmaschine sitzend dual':'IMG_3048.png','bankdruckmaschine liegend dual':'IMG_3049.png','schragbankdruckmaschine dual':'IMG_3062.png','schragbankmaschine sitzend':'IMG_3063.png','seithebemaschine ohne armpolster':'IMG_3064.png','seithebemaschine dual ohne armpolster':'IMG_3065.png','trizepsmaschine uber kopf':'IMG_3066.png','trizepsmaschine horizontal':'IMG_3067.png','trizeps dip maschine sitzend dual':'IMG_3068.png','kurzhantel seitheben sitzend':'IMG_3069.png','kurzhantel seitheben stehend':'IMG_3070.png','kurzhantel schragbankdrucken':'IMG_3071.png'
};

let state=null,tick=null;
function snapshot(){return read(SNAP,{plan:{},workouts:{},schedule:[]})}
function dialog(){return q('#workout-dialog')}
function studioProfile(){return read(STUDIO,read('gym-studio-profile-v32',{studio:'John Reed Essen',devices:{}}))}
function studioEntry(name){return Object.entries(studioProfile()?.devices||{}).find(([n])=>canon(n)===canon(name))?.[1]||null}
function available(name){const key=canon(name),studio=canon(studioProfile()?.studio||'John Reed Essen');if(studio==='john reed essen'&&(key==='butterfly mit pads'||key==='butterfly reverse mit pads'))return false;return studioEntry(name)?.present!=='no'}
function studioCode(name){const e=studioEntry(name);return e?.code||e?.number||e?.device_code||'–'}
function imageFor(name,fallback=''){return IMG[canon(name)]||fallback||''}
function target(ex){return{sets:Number(ex.target_sets)||3,min:Number(ex.rep_min)||8,max:Number(ex.rep_max)||12,rir:'1–2'}}
function variantsFor(ex){return (VARIANTS[ex.name]||[[ex.name,ex.image_path||null]]).map(([name,image])=>({name,image:imageFor(name,image)})).filter(v=>available(v.name)||canon(v.name)===canon(ex.name))}
function historyFor(name){const h=read(HISTORY,{}),key=canon(name);return h[name]||Object.entries(h).find(([n])=>canon(n)===key)?.[1]||null}
function workHistory(name){return (historyFor(name)?.sets||[]).filter(s=>!s.warmup&&num(s.weight)!=null&&num(s.reps)!=null)}
function topSet(name){const sets=workHistory(name);if(!sets.length)return null;return sets.reduce((a,b)=>num(b.weight)>num(a.weight)||(num(b.weight)===num(a.weight)&&num(b.reps)>num(a.reps))?b:a)}
function lastSet(name){return workHistory(name).at(-1)||null}
function compound(name){return /(schragbank|bankdruck|brustpresse|latzug|ruckenzug|rudermaschine|low row|high row)/.test(canon(name))}
function coach(ex,name){const t=target(ex),base=topSet(name);if(!base)return{kg:'',reps:t.min,rir:t.rir,sets:t.sets,title:'Erste Referenz setzen',text:`Heute nach Planrahmen: ${t.sets} Arbeitssätze mit ${t.min}–${t.max} sauberen Wiederholungen bei RIR ${t.rir}.`,base:null,adjusted:false};const kg=num(base.weight),reps=num(base.reps),rir=num(base.rir);let sets=t.sets,targetReps=Math.min(t.max,reps+1),targetRir=t.rir,reason='Planrahmen bleibt bestehen.';if(compound(name)&&rir!=null&&rir<=0){sets=Math.min(2,t.sets);targetRir='0–1';reason=`Tagesanpassung: Der relevante letzte Topsatz lag bereits bei RIR ${rir}. Deshalb heute ${sets} sehr harte statt ${t.sets} Arbeitssätze.`}else if(compound(name)&&rir===1){sets=Math.min(3,t.sets);targetRir='1';reason='Tagesanpassung auf Basis des letzten harten Satzes bei RIR 1.'}return{kg,reps:targetReps,rir:targetRir,sets,title:`${fmt(kg)} kg · Ziel ${targetReps}`,text:`Basis: ${fmt(kg)} kg × ${reps}${rir==null?'':` · RIR ${rir}`}. ${reason}`,base,adjusted:sets!==t.sets||String(targetRir)!==String(t.rir)}}
function sessionDate(code){const start=q('#start-workout');if(start?.dataset.workout===code&&start.dataset.scheduleDate)return start.dataset.scheduleDate;return today()}
function blankExercise(ex,index){const vs=variantsFor(ex),t=target(ex);return{id:String(ex.id||ex.plan_exercise_id||index),planExerciseId:ex.id||ex.plan_exercise_id||null,standardExerciseId:ex.exercise_id||null,name:ex.name,image:ex.image_path||null,extra:String(ex.plan_exercise_id||'').startsWith('extra-'),target:t,variants:vs.length?vs:[{name:ex.name,image:ex.image_path||null}],variantIndex:0,status:'pending',warmups:[],sets:Array.from({length:t.sets},()=>({weight:'',reps:'',rir:''}))}}
function newSession(code){const w=snapshot().workouts?.[code];if(!w)return null;return{code,date:sessionDate(code),selected:0,elapsed:0,running:false,lastStart:null,startedAt:new Date().toISOString(),coachInitialized:false,exercises:(w.exercises||[]).map(blankExercise)}}
function save(){if(state)write(SESSION,state)}
function elapsed(){return(state?.elapsed||0)+(state?.running&&state.lastStart?Date.now()-state.lastStart:0)}
function clock(){const s=Math.floor(elapsed()/1000);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function current(){return state?.exercises?.[state.selected]||null}
function currentVariant(){const ex=current();return ex?.variants?.[ex.variantIndex]||null}
function setViewport(){const meta=q('meta[name="viewport"]');if(meta)meta.content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover'}
function openSession(code){localStorage.removeItem(LEGACY_ACTIVE);const stored=read(SESSION,null);state=stored?.code===code&&stored?.date===sessionDate(code)?stored:newSession(code);if(!state)return;save();setViewport();const d=dialog();d.className='workout-approved';d.replaceChildren();if(!d.open)d.showModal();render(true);hydrateHistory().then(()=>{applyCoachDefaults();render(false)}).catch(()=>{});startTick()}
function closeSession(){if(state?.running){state.elapsed=elapsed();state.running=false;state.lastStart=null;save()}dialog()?.close();stopTick()}
function toggleTimer(){if(!state)return;if(state.running){state.elapsed=elapsed();state.running=false;state.lastStart=null}else{state.running=true;state.lastStart=Date.now()}save();renderHeader()}
function startTick(){stopTick();tick=setInterval(renderHeader,1000)}
function stopTick(){if(tick)clearInterval(tick);tick=null}
function blankSet(s){return !String(s?.weight||'').trim()&&!String(s?.reps||'').trim()&&!String(s?.rir||'').trim()}
function applyCoachDefaults(){if(!state||state.coachInitialized)return;for(const ex of state.exercises){if(ex.warmups.length||!ex.sets.every(blankSet))continue;const v=ex.variants[ex.variantIndex]||ex.variants[0],c=coach(ex,v.name);ex.sets=Array.from({length:c.sets},()=>({weight:'',reps:'',rir:''}));if(c.kg!==''){ex.sets[0]={weight:String(c.kg),reps:String(c.reps),rir:String(c.rir).includes('–')?String(c.rir).split('–').at(-1):String(c.rir)}}}state.coachInitialized=true;save()}

async function hydrateHistory(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;const wr=await supabase.from('workouts').select('id,workout_date').eq('user_id',session.user.id).in('status',['completed','partial']).order('workout_date',{ascending:false}).limit(40);if(wr.error||!wr.data?.length)return;const order=Object.fromEntries(wr.data.map((r,i)=>[r.id,i])),dates=Object.fromEntries(wr.data.map(r=>[r.id,r.workout_date]));const we=await supabase.from('workout_exercises').select('id,workout_id,exercise_id').in('workout_id',wr.data.map(r=>r.id));if(we.error||!we.data?.length)return;const exIds=[...new Set(we.data.map(r=>r.exercise_id).filter(Boolean))];const names=exIds.length?await supabase.from('exercises').select('id,name').in('id',exIds):{data:[]};if(names.error)return;const nameMap=Object.fromEntries((names.data||[]).map(r=>[r.id,r.name]));const sets=await supabase.from('workout_sets').select('workout_exercise_id,set_number,weight_kg,repetitions,rir,notes').in('workout_exercise_id',we.data.map(r=>r.id)).order('set_number');if(sets.error)return;const out={};for(const row of [...we.data].sort((a,b)=>(order[a.workout_id]??999)-(order[b.workout_id]??999))){const name=nameMap[row.exercise_id];if(!name||out[name])continue;const values=sets.data.filter(s=>s.workout_exercise_id===row.id).map(s=>({weight:s.weight_kg??'',reps:s.repetitions??'',rir:s.rir??'',warmup:s.notes==='warmup'}));if(values.length)out[name]={date:dates[row.workout_id],sets:values}}write(HISTORY,out)}

function renderHeader(){const d=dialog();if(!d?.open||!state)return;const time=q('.wo-timer span',d),label=q('.wo-timer small',d);if(time)time.textContent=clock();if(label)label.textContent=state.running?'Pause':state.elapsed?'Fortsetzen':'Training starten'}
function renderTabs(){const d=dialog(),tabs=q('.wo-tabs',d);if(!tabs)return;const left=tabs.scrollLeft;tabs.innerHTML=state.exercises.map((ex,i)=>`<button type="button" class="wo-tab ${i===state.selected?'active':''} ${ex.status==='completed'?'done':''}" data-action="select" data-index="${i}"><b>${ex.status==='completed'?'✓':i+1}</b><span>${esc(ex.name)}</span></button>`).join('');tabs.scrollLeft=left}
function deviceMarkup(ex){const v=currentVariant(),h=historyFor(v.name),last=lastSet(v.name),pr=topSet(v.name);return`<section class="wo-card"><div class="wo-card-head"><small>GERÄT & ALTERNATIVEN</small><button type="button" data-action="history">Verlauf</button></div><div class="wo-device-main"><img src="${esc(imageFor(v.name,v.image||ex.image||''))}" alt="${esc(v.name)}" data-action="zoom"><div><span class="wo-eyebrow">AKTIV</span><h2>${esc(v.name)}</h2><dl><dt>PR</dt><dd>${pr?`${fmt(pr.weight)} × ${pr.reps}${pr.rir==null?'':` · RIR ${pr.rir}`}`:'–'}</dd><dt>Zuletzt</dt><dd>${last?`${fmt(last.weight)} × ${last.reps}${last.rir==null?'':` · RIR ${last.rir}`} · ${esc(h?.date||'')}`:'–'}</dd><dt>Studio-Code</dt><dd>${esc(studioCode(v.name))}</dd></dl></div></div><div class="wo-variants">${ex.variants.map((x,i)=>`<button type="button" class="wo-variant ${i===ex.variantIndex?'active':''}" data-action="variant" data-index="${i}"><img src="${esc(imageFor(x.name,x.image||''))}" alt=""><span><strong>${esc(x.name)}</strong><span>${lastSet(x.name)?`Zuletzt ${fmt(lastSet(x.name).weight)} × ${lastSet(x.name).reps}`:'Noch keine Werte'}</span></span></button>`).join('')}</div></section>`}
function coachMarkup(ex){const v=currentVariant(),c=coach(ex,v.name),pr=topSet(v.name),last=lastSet(v.name);return`<section class="wo-card"><div class="wo-card-head"><small>COACH · GERÄTESPEZIFISCH</small><button type="button" data-action="info">Info</button></div><div class="wo-coachbox"><span class="wo-eyebrow">HEUTIGE EMPFEHLUNG</span><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p></div><div class="wo-coachstats"><article><small>PR</small><strong>${pr?`${fmt(pr.weight)} × ${pr.reps}${pr.rir==null?'':` · RIR ${pr.rir}`}`:'–'}</strong></article><article><small>LETZTES MAL</small><strong>${last?`${fmt(last.weight)} × ${last.reps}${last.rir==null?'':` · RIR ${last.rir}`}`:'–'}</strong></article><article><small>HEUTE</small><strong>${c.sets} Sätze · RIR ${esc(c.rir)}</strong></article></div></section>`}
function warmupMarkup(ex){return`<section class="wo-card"><div class="wo-card-head"><small>WARM-UP · OPTIONAL</small><button type="button" data-action="add-warmup">+ Warm-up</button></div><div class="wo-sets">${ex.warmups.length?ex.warmups.map((s,i)=>`<div class="wo-set wo-warmup-row"><span class="wo-setno">W</span><div class="wo-field"><label>kg</label><input inputmode="decimal" data-kind="warmup" data-index="${i}" data-field="weight" value="${esc(s.weight)}"></div><div class="wo-field"><label>Wdh.</label><input inputmode="numeric" data-kind="warmup" data-index="${i}" data-field="reps" value="${esc(s.reps)}"></div><button type="button" class="wo-previous" data-action="remove-warmup" data-index="${i}">Entfernen</button></div>`).join(''):'<p class="wo-empty">Noch kein Warm-up eingetragen.</p>'}</div></section>`}
function setsMarkup(ex){const c=coach(ex,currentVariant().name);return`<section class="wo-card"><div class="wo-card-head"><small>ARBEITSSÄTZE · HEUTE ${c.sets}</small><button type="button" data-action="history">Verlauf</button></div><div class="wo-sets">${ex.sets.map((s,i)=>{const previous=i===0?c.base:ex.sets[i-1],label=i===0?'Vorwert':`Satz ${i} übernehmen`;return`<div class="wo-set"><span class="wo-setno">${i+1}</span><div class="wo-field"><label>kg</label><input inputmode="decimal" data-kind="set" data-index="${i}" data-field="weight" value="${esc(s.weight)}" placeholder="${esc(c.kg)}"></div><div class="wo-field"><label>Wdh.</label><input inputmode="numeric" data-kind="set" data-index="${i}" data-field="reps" value="${esc(s.reps)}" placeholder="${esc(Math.max(1,c.reps-i))}"></div><div class="wo-field"><label>RIR</label><input inputmode="decimal" data-kind="set" data-index="${i}" data-field="rir" value="${esc(s.rir)}" placeholder="${esc(String(c.rir).split('–')[0])}"></div><button type="button" class="wo-previous" data-action="copy-set" data-index="${i}" ${previous?'':'disabled'}>${label}</button></div>`}).join('')}</div><div class="wo-set-actions"><button type="button" data-action="remove-set">− Satz</button><button type="button" data-action="add-set">+ Satz</button></div><button type="button" class="wo-set-count" data-action="coach-count">Auf heutige Empfehlung: ${c.sets} Arbeitssätze</button><div class="wo-wide"><button type="button" data-action="info">Info</button><button type="button" data-action="add-exercise">+ Übung</button></div>${ex.extra?'<button type="button" class="wo-set-count" data-action="remove-exercise">Zusatzübung entfernen</button>':''}</section>`}
function completeMarkup(ex){return`<section class="wo-complete-card"><button type="button" class="wo-complete" data-action="complete-exercise">${ex.status==='completed'?'✓ Übung abgeschlossen':'Übung abschließen'}</button></section>`}
function render(forceTop=false,restore={}){const d=dialog();if(!d?.open||!state)return;const oldApp=q('.wo-app',d),oldScroll=oldApp?.scrollTop||0,oldTab=q('.wo-tabs',d)?.scrollLeft||0,oldVariant=q('.wo-variants',d)?.scrollLeft||0;const ex=current();d.innerHTML=`<div class="wo-app"><header class="wo-top"><button type="button" class="wo-close" data-action="close">×</button><div class="wo-heading"><small>TRAINING HEUTE</small><strong>Training ${esc(state.code)}</strong></div><button type="button" class="wo-timer" data-action="timer"><span>${clock()}</span><small>${state.running?'Pause':state.elapsed?'Fortsetzen':'Training starten'}</small></button></header><nav class="wo-tabs"></nav><main class="wo-page"><header class="wo-hero"><div><span class="wo-eyebrow">ÜBUNG ${state.selected+1} VON ${state.exercises.length}</span><h1>${esc(ex.name)}</h1><p>Planrahmen: ${ex.target.sets} Arbeitssätze · ${ex.target.min}–${ex.target.max} Wdh. · RIR ${esc(ex.target.rir)}</p></div></header>${deviceMarkup(ex)}${coachMarkup(ex)}${warmupMarkup(ex)}${setsMarkup(ex)}${completeMarkup(ex)}</main><nav class="wo-bottom"><button type="button" data-action="prev" ${state.selected===0?'disabled':''}>‹ Vorherige</button><button type="button" class="wo-menu" data-action="menu">☷</button><button type="button" class="wo-next" data-action="next" ${state.selected===state.exercises.length-1?'disabled':''}>Nächste ›</button></nav></div>`;renderTabs();const app=q('.wo-app',d);app.scrollTop=forceTop?0:(restore.scrollTop??oldScroll);q('.wo-tabs',d).scrollLeft=restore.tabScroll??oldTab;q('.wo-variants',d).scrollLeft=restore.variantScroll??oldVariant;renderHeader()}

function modal(title,html){let m=q('#workout-modal');if(!m){m=document.createElement('dialog');m.id='workout-modal';m.className='wo-modal';document.body.append(m)}m.innerHTML=`<div class="wo-modal-card"><header><h2>${esc(title)}</h2><button type="button" data-modal-close>Schließen</button></header><div class="wo-modal-body">${html}</div></div>`;q('[data-modal-close]',m).onclick=()=>m.close();if(!m.open)m.showModal();return m}
function historyModal(){const name=currentVariant().name,h=historyFor(name),sets=workHistory(name);modal(`Verlauf · ${name}`,sets.length?sets.map((s,i)=>`<div class="wo-history-row"><span>Satz ${i+1}</span><strong>${fmt(s.weight)} kg × ${s.reps}</strong><span>${s.rir==null?'':`RIR ${s.rir}`}</span></div>`).join('')+`<p class="wo-history-date">${esc(h?.date||'')}</p>`:'<p>Noch keine gespeicherten Werte an diesem Gerät.</p>')}
function infoModal(){const ex=current(),name=currentVariant().name,c=coach(ex,name);modal(`Info · ${ex.name}`,`<p><strong>Planrahmen:</strong> ${ex.target.sets} Arbeitssätze · ${ex.target.min}–${ex.target.max} Wiederholungen · RIR ${esc(ex.target.rir)}</p><p><strong>Heutige Coach-Empfehlung:</strong> ${c.sets} Arbeitssätze · Ziel RIR ${esc(c.rir)}</p><p><strong>Aktuelles Gerät:</strong> ${esc(name)}</p><p><strong>Studio-Code:</strong> ${esc(studioCode(name))}</p><p>${esc(c.text)}</p>`)}
function menuModal(){const m=modal('Übungsübersicht',state.exercises.map((ex,i)=>`<div class="wo-order"><b>${i+1}</b><button type="button" data-menu-select="${i}">${esc(ex.name)}</button><div><button type="button" data-menu-up="${i}" ${i===0?'disabled':''}>↑</button><button type="button" data-menu-down="${i}" ${i===state.exercises.length-1?'disabled':''}>↓</button></div></div>`).join('')+'<button type="button" class="wo-modal-action" data-menu-add>+ Übung hinzufügen</button><button type="button" class="wo-modal-secondary" data-menu-finish>Training abschließen</button>');qa('[data-menu-select]',m).forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.menuSelect);save();m.close();render(true)});qa('[data-menu-up]',m).forEach(b=>b.onclick=()=>moveExercise(Number(b.dataset.menuUp),-1,m));qa('[data-menu-down]',m).forEach(b=>b.onclick=()=>moveExercise(Number(b.dataset.menuDown),1,m));q('[data-menu-add]',m).onclick=()=>{m.close();addExerciseModal()};q('[data-menu-finish]',m).onclick=()=>completeTraining()}
function moveExercise(i,delta,m){const j=i+delta;if(j<0||j>=state.exercises.length)return;[state.exercises[i],state.exercises[j]]=[state.exercises[j],state.exercises[i]];if(state.selected===i)state.selected=j;else if(state.selected===j)state.selected=i;save();m.close();menuModal();render(false)}
function addExerciseModal(){const names=new Set();Object.values(snapshot().workouts||{}).forEach(w=>(w.exercises||[]).forEach(ex=>names.add(ex.name)));Object.keys(studioProfile()?.devices||{}).forEach(n=>available(n)&&names.add(n));const m=modal('Übung hinzufügen',`<div class="wo-set"><div class="wo-field" style="grid-column:1/-1"><label>Suche</label><input id="wo-ex-search" type="search" placeholder="Übung oder Gerät"></div></div><div id="wo-ex-results"></div>`);const input=q('#wo-ex-search',m),root=q('#wo-ex-results',m);const paint=()=>{const term=canon(input.value);root.innerHTML=[...names].filter(n=>!term||canon(n).includes(term)).slice(0,40).map(n=>`<button type="button" class="wo-modal-secondary" data-add-name="${esc(n)}">${esc(n)}</button>`).join('');qa('[data-add-name]',root).forEach(b=>b.onclick=()=>{const name=b.dataset.addName,ex={id:`extra-${crypto.randomUUID()}`,planExerciseId:null,standardExerciseId:null,name,image:null,extra:true,target:{sets:3,min:8,max:12,rir:'1–2'},variants:[{name,image:imageFor(name)}],variantIndex:0,status:'pending',warmups:[],sets:Array.from({length:3},()=>({weight:'',reps:'',rir:''}))};state.exercises.push(ex);state.selected=state.exercises.length-1;save();m.close();render(true)})};input.oninput=paint;paint();input.focus()}

function handleInput(e){const input=e.target.closest('#workout-dialog input[data-kind]');if(!input||!state)return;const ex=current(),arr=input.dataset.kind==='warmup'?ex.warmups:ex.sets,row=arr[Number(input.dataset.index)];if(!row)return;row[input.dataset.field]=input.value;save()}
function copySet(i){const ex=current(),c=coach(ex,currentVariant().name);if(i===0&&c.base)ex.sets[0]={weight:String(c.base.weight??''),reps:String(c.base.reps??''),rir:String(c.base.rir??'')};else if(i>0)ex.sets[i]={...ex.sets[i-1]};save();render(false)}
function setCoachCount(){const ex=current(),wanted=coach(ex,currentVariant().name).sets;if(ex.sets.length>wanted&&ex.sets.slice(wanted).some(s=>!blankSet(s)))return alert('Die zusätzlichen Arbeitssätze enthalten bereits Werte.');while(ex.sets.length<wanted)ex.sets.push({weight:'',reps:'',rir:''});while(ex.sets.length>wanted)ex.sets.pop();save();render(false)}
function handleClick(e){const button=e.target.closest('#workout-dialog [data-action]');if(!button||!state)return;const a=button.dataset.action;e.preventDefault();if(a==='close')return closeSession();if(a==='timer')return toggleTimer();if(a==='prev'&&state.selected>0){state.selected--;save();return render(true)}if(a==='next'&&state.selected<state.exercises.length-1){state.selected++;save();return render(true)}if(a==='select'){state.selected=Number(button.dataset.index);save();return render(true)}if(a==='variant'){const variantScroll=q('.wo-variants',dialog())?.scrollLeft||0;current().variantIndex=Number(button.dataset.index);save();return render(false,{variantScroll})}if(a==='history')return historyModal();if(a==='info')return infoModal();if(a==='menu')return menuModal();if(a==='zoom')return modal('Gerätebild',`<img class="wo-modal-image" src="${esc(button.getAttribute('src'))}" alt="Gerätebild">`);if(a==='add-warmup'){current().warmups.push({weight:'',reps:''});save();return render(false)}if(a==='remove-warmup'){current().warmups.splice(Number(button.dataset.index),1);save();return render(false)}if(a==='add-set'){current().sets.push({weight:'',reps:'',rir:''});save();return render(false)}if(a==='remove-set'){if(current().sets.length>1)current().sets.pop();save();return render(false)}if(a==='copy-set')return copySet(Number(button.dataset.index));if(a==='coach-count')return setCoachCount();if(a==='add-exercise')return addExerciseModal();if(a==='remove-exercise'){if(!current().extra)return;if(confirm(`„${current().name}“ entfernen?`)){state.exercises.splice(state.selected,1);state.selected=Math.max(0,state.selected-1);save();render(true)}return}if(a==='complete-exercise'){current().status=current().status==='completed'?'pending':'completed';save();return render(false)}}

async function ensureExercise(userId,ex,variant){if(ex.standardExerciseId&&canon(variant.name)===canon(ex.name))return ex.standardExerciseId;const found=await supabase.from('exercises').select('id,name').ilike('name',variant.name).limit(10);if(found.error)throw found.error;const exact=(found.data||[]).find(r=>canon(r.name)===canon(variant.name));if(exact)return exact.id;const ins=await supabase.from('exercises').insert({owner_id:userId,name:variant.name,studio:'John Reed Essen',equipment:'Gerätevariante',is_shared_catalogue:false,is_active:true}).select('id').single();if(ins.error)throw ins.error;return ins.data.id}
async function completeTraining(){if(!state)return;const incomplete=state.exercises.filter(x=>x.status!=='completed').length;if(incomplete&&!confirm(`${incomplete} Übungen sind noch offen. Training trotzdem teilweise speichern?`))return;try{const {data:{session},error}=await supabase.auth.getSession();if(error||!session)throw error||new Error('Bitte neu anmelden.');const snap=snapshot(),plan=snap.plan,workout=snap.workouts?.[state.code],elapsedSeconds=Math.floor(elapsed()/1000),status=incomplete?'partial':'completed';const wr=await supabase.from('workouts').insert({user_id:session.user.id,plan_id:plan.id,plan_workout_id:workout.id,workout_date:state.date,started_at:state.startedAt||new Date(Date.now()-elapsedSeconds*1000).toISOString(),finished_at:new Date().toISOString(),elapsed_seconds:elapsedSeconds,status}).select('id').single();if(wr.error)throw wr.error;for(let i=0;i<state.exercises.length;i++){const ex=state.exercises[i],variant=ex.variants[ex.variantIndex]||ex.variants[0],exerciseId=await ensureExercise(session.user.id,ex,variant);const we=await supabase.from('workout_exercises').insert({user_id:session.user.id,workout_id:wr.data.id,plan_exercise_id:ex.planExerciseId,exercise_id:exerciseId,exercise_order:i+1,status:ex.status==='completed'?'completed':'not_completed'}).select('id').single();if(we.error)throw we.error;const all=[...ex.warmups.map(s=>({...s,rir:'',warmup:true})),...ex.sets.map(s=>({...s,warmup:false}))].filter(s=>s.weight||s.reps||s.rir||s.warmup);if(all.length){const rows=all.map((s,j)=>({user_id:session.user.id,workout_exercise_id:we.data.id,set_number:j+1,weight_kg:num(s.weight),repetitions:num(s.reps),rir:num(s.rir)==null?null:Math.round(num(s.rir)),completed:Boolean(s.weight||s.reps),notes:s.warmup?'warmup':''}));const si=await supabase.from('workout_sets').insert(rows);if(si.error)throw si.error}}const currentSnap=snapshot();currentSnap.completed=Array.isArray(currentSnap.completed)?currentSnap.completed:[];if(!currentSnap.completed.some(x=>String(x.id)===String(wr.data.id)))currentSnap.completed.push({id:wr.data.id,user_id:session.user.id,plan_id:plan.id,plan_workout_id:workout.id,date:state.date,workout_date:state.date,code:state.code,status});write(SNAP,currentSnap);localStorage.removeItem(SESSION);state=null;dialog().close();q('#workout-modal')?.close();stopTick();window.dispatchEvent(new CustomEvent('gym:schedule-refresh'));}catch(err){alert(`Training konnte nicht gespeichert werden: ${err?.message||err}`)}}

function interceptOpen(e){const b=e.target.closest('[data-workout],#start-workout');if(!b)return;const code=b.dataset.workout||q('#next-workout')?.textContent?.match(/\b([AB])\b/)?.[1];if(!code)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openSession(code)}
function install(){setViewport();localStorage.removeItem(LEGACY_ACTIVE);document.addEventListener('click',interceptOpen,true);document.addEventListener('click',handleClick);document.addEventListener('input',handleInput);dialog()?.addEventListener('close',stopTick)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
