const q=(s,r=document)=>r.querySelector(s);
const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const HISTORY='gym-v55-device-history';
const STUDIO='gym-studio-profile-v35';
let observer=null,scheduled=false,startX=0,startY=0;

const canon=v=>String(v||'').toLowerCase().replaceAll('ä','a').replaceAll('ö','o').replaceAll('ü','u').replaceAll('ß','ss').replace(/[^a-z0-9]+/g,' ').trim();
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
const fmt=v=>num(v)==null?'–':num(v).toLocaleString('de-DE',{maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const IMG={
 'bauchmuskelmaschine':'IMG_3040.png','bauchmuskelmaschine crunch liegend':'IMG_3041.png','klappsitz bauchmaschine sitzend':'IMG_3042.png','klappsitz bauchmaschine liegend plate loaded':'IMG_3043.png','bizepsmaschine':'IMG_3044.png','bizepsmaschine plate loaded':'IMG_3045.png','scott curler sitzend':'IMG_3046.png','brustpresse sitzend':'IMG_3047.png','bankdruckmaschine sitzend dual':'IMG_3048.png','bankdruckmaschine liegend dual':'IMG_3049.png','butterfly mit griffen':'pics_johnreed/IMG_3452.jpeg','butterfly mit pads':'IMG_3051.png','schragbankdruckmaschine dual':'IMG_3062.png','schragbankmaschine sitzend':'IMG_3063.png','seithebemaschine ohne armpolster':'IMG_3064.png','seithebemaschine dual ohne armpolster':'IMG_3065.png','trizepsmaschine uber kopf':'IMG_3066.png','trizepsmaschine horizontal':'IMG_3067.png','trizeps dip maschine sitzend dual':'IMG_3068.png','kurzhantel seitheben sitzend':'IMG_3069.png','kurzhantel seitheben stehend':'IMG_3070.png','kurzhantel schragbankdrucken':'IMG_3071.png'
};

function historyFor(name){const all=read(HISTORY,{}),key=canon(name);return all[name]||Object.entries(all).find(([n])=>canon(n)===key)?.[1]||null}
function workSets(name){return (historyFor(name)?.sets||[]).filter(s=>!s.warmup&&num(s.weight)!=null&&num(s.reps)!=null)}
function warmSets(name){return (historyFor(name)?.sets||[]).filter(s=>s.warmup&&num(s.weight)!=null&&num(s.reps)!=null)}
function lastSet(name){return workSets(name).at(-1)||null}
function topSet(name){const sets=workSets(name);if(!sets.length)return null;return sets.reduce((a,b)=>num(b.weight)>num(a.weight)||(num(b.weight)===num(a.weight)&&num(b.reps)>num(a.reps))?b:a)}
function studioEntry(name){const p=read(STUDIO,read('gym-studio-profile-v32',{studio:'John Reed Essen',devices:{}}));return Object.entries(p?.devices||{}).find(([n])=>canon(n)===canon(name))?.[1]||null}
function present(name){const key=canon(name),profile=read(STUDIO,read('gym-studio-profile-v32',{studio:'John Reed Essen',devices:{}})),studio=canon(profile?.studio||'John Reed Essen');if(studio==='john reed essen'&&(key==='butterfly mit pads'||key==='butterfly reverse mit pads'))return false;return studioEntry(name)?.present!=='no'}
function studioCode(name){const e=studioEntry(name);return e?.code||e?.number||e?.device_code||'–'}
function imgFor(name,fallback=''){return IMG[canon(name)]||fallback||''}

function engine(d){return q('#exercise-list',d)}
function items(d){return qa('#exercise-list [data-select-ex-v53]',d)}
function activeIndex(d){const all=items(d);const i=all.findIndex(x=>x.classList.contains('active'));return i<0?0:i}
function detail(d){return q('#exercise-list .training-exercise-v53',d)}
function exerciseName(d){return q('.exercise-title-v53 h3',detail(d))?.textContent?.trim()||q('strong',items(d)[activeIndex(d)])?.textContent?.trim()||'Übung'}
function targetText(d){return q('.exercise-title-v53 p',detail(d))?.textContent?.trim()||''}
function currentDevice(d){return q('.device-nav-v53 strong',detail(d))?.textContent?.trim()||exerciseName(d)}
function engineRows(d){return qa('.set-row-v53',detail(d))}
function engineField(row,name){return q(`[data-field-v53="${name}"]`,row)}
function engineVariants(d){return qa('.device-history-v55 button',detail(d))}
function variantName(btn){return q('strong',btn)?.textContent?.trim()||''}
function currentVariantFallback(d){return q('.device-image-v53 img',detail(d))?.getAttribute('src')||''}

function targetRange(d){const text=targetText(d);const m=text.match(/(\d+)\s*Arbeitssätze.*?(\d+)\s*[–-]\s*(\d+).*?RIR\s*([0-9–-]+)/i);return{sets:m?Number(m[1]):Math.max(2,engineRows(d).length),min:m?Number(m[2]):6,max:m?Number(m[3]):12,rir:m?.[4]||'1–2'}}
function coach(name,d){const range=targetRange(d),last=lastSet(name);if(!last)return{title:'Neue Gerätereferenz setzen',text:`Wähle ein Gewicht für ${range.min}–${range.max} saubere Wiederholungen bei ungefähr RIR ${range.rir}.`,next:'–'};const kg=num(last.weight),reps=num(last.reps),rir=num(last.rir);let target=reps,text='';if(rir!=null&&rir>=3){target=Math.max(range.min,reps-2);text=`${fmt(kg)} kg waren deutlich unter deinem Limit. Erhöhe das Gewicht kontrolliert und bleibe im Zielbereich ${range.min}–${range.max}.`}else if(rir===0){target=Math.min(range.max,reps+1);text=`${fmt(kg)} kg beibehalten. Du warst am Limit. Ziel ist jetzt mindestens ${reps} saubere Wiederholungen und danach schrittweise bis ${range.max}.`}else{target=Math.min(range.max,reps+1);text=`${fmt(kg)} kg beibehalten. Ziel heute: ${target} saubere Wiederholungen bei etwa RIR ${range.rir}.`}return{title:`${fmt(kg)} kg · Ziel ${target}`,text,next:`${fmt(kg)} × ${target}`}}
function suggestion(name,d,rowIndex){const range=targetRange(d),last=lastSet(name);if(!last)return['','',''];const c=coach(name,d),kg=num(last.weight),goal=Number(String(c.next).split('×')[1])||num(last.reps);if(rowIndex===0)return[kg,num(last.reps),last.rir??''];return[kg,Math.max(range.min,goal-Math.max(0,rowIndex-1)),rowIndex===1?1:2]}
function chart(name){const h=historyFor(name),sets=workSets(name);if(!sets.length)return'<p class="wo-empty">Noch kein Verlauf an diesem Gerät.</p>';const vals=sets.map((s,i)=>({kg:num(s.weight),date:h?.date||'',i})),kgs=vals.map(v=>v.kg),min=Math.max(0,Math.min(...kgs)-5),max=Math.max(...kgs)+5,span=Math.max(1,max-min),x=i=>42+i*(240/Math.max(1,vals.length-1)),y=kg=>92-(kg-min)/span*68,pts=vals.map(v=>`${x(v.i)},${y(v.kg)}`).join(' ');return `<svg viewBox="0 0 310 125"><line x1="40" y1="12" x2="40" y2="96"/><line x1="40" y1="96" x2="292" y2="96"/><text x="4" y="18">${max} kg</text><text x="8" y="96">${min} kg</text><polyline points="${pts}"/>${vals.map(v=>`<circle cx="${x(v.i)}" cy="${y(v.kg)}" r="4"/>`).join('')}<text x="112" y="116">${esc(h?.date||'Training')}</text><text x="6" y="62" transform="rotate(-90 12 62)">Arbeitsgewicht</text></svg>`}

function schedule(ms=0){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;render()},ms)}
function ensureShell(d){let shell=q('.wo-app',d);if(shell)return shell;shell=document.createElement('div');shell.className='wo-app';shell.innerHTML=`<header class="wo-top"><button class="wo-close" type="button">×</button><div class="wo-heading"><small>TRAINING HEUTE</small><strong></strong></div><button class="wo-timer" type="button"><span>00:00</span><small>Training starten</small></button></header><nav class="wo-tabs"></nav><main class="wo-page"></main><nav class="wo-bottom"><button class="wo-prev" type="button">‹ Vorherige</button><button class="wo-menu" type="button">☷</button><button class="wo-next" type="button">Nächste ›</button></nav><section class="wo-sheet"><div class="wo-sheet-card"><header><h2>Übersicht</h2><button class="wo-sheet-close" type="button">Schließen</button></header><div class="wo-sheet-body"></div></div></section><section class="wo-lightbox"><button type="button">×</button><img alt="Gerätebild vergrößert"></section>`;d.append(shell);q('.wo-close',shell).onclick=()=>q('#close-dialog',d)?.click();q('.wo-timer',shell).onclick=()=>q('#timer-toggle',d)?.click();q('.wo-prev',shell).onclick=()=>q('[data-prev-ex-v53]',detail(d))?.click();q('.wo-next',shell).onclick=()=>q('[data-next-ex-v53]',detail(d))?.click();q('.wo-menu',shell).onclick=()=>openOrder(d);q('.wo-sheet-close',shell).onclick=()=>closeSheet(d);q('.wo-sheet',shell).onclick=e=>{if(e.target===q('.wo-sheet',shell))closeSheet(d)};q('.wo-lightbox>button',shell).onclick=()=>q('.wo-lightbox',shell).classList.remove('open');q('.wo-lightbox',shell).onclick=e=>{if(e.target===q('.wo-lightbox',shell))q('.wo-lightbox',shell).classList.remove('open')};return shell}
function closeSheet(d){q('.wo-sheet',d)?.classList.remove('open')}
function openSheet(d,title,html){const shell=ensureShell(d);q('.wo-sheet h2',shell).textContent=title;q('.wo-sheet-body',shell).innerHTML=html;q('.wo-sheet',shell).classList.add('open')}
function openOrder(d){const all=items(d);openSheet(d,'Übungsreihenfolge',all.map((it,i)=>`<div class="wo-order"><b>${i+1}</b><strong>${esc(q('strong',it)?.textContent||`Übung ${i+1}`)}</strong><div><button data-wo-up="${i}">↑</button><button data-wo-down="${i}">↓</button></div></div>`).join('')+`<button class="wo-sheet-action" data-wo-add>+ Übung hinzufügen</button>`);qa('[data-wo-up]',q('.wo-sheet',d)).forEach(b=>b.onclick=()=>{q(`[data-order-up-v53="${b.dataset.woUp}"]`,d)?.click();setTimeout(()=>openOrder(d),80)});qa('[data-wo-down]',q('.wo-sheet',d)).forEach(b=>b.onclick=()=>{q(`[data-order-down-v53="${b.dataset.woDown}"]`,d)?.click();setTimeout(()=>openOrder(d),80)});const add=q('[data-wo-add]',q('.wo-sheet',d));if(add)add.onclick=()=>{closeSheet(d);q('#add-exercise-v54',d)?.click()}}
function openHistory(d,name){const h=historyFor(name),sets=workSets(name);openSheet(d,`Verlauf · ${name}`,sets.length?sets.map((s,i)=>`<div class="wo-history-row"><span>Satz ${i+1}</span><strong>${fmt(s.weight)} kg × ${s.reps}</strong><span>${s.rir==null?'':`RIR ${s.rir}`}</span></div>`).join('')+`<p class="wo-history-date">Letzter gespeicherter Trainingstag: ${esc(h?.date||'–')}</p>`:'<p>Noch keine Werte an diesem Gerät.</p>')}
function openWarm(d,name){const sets=warmSets(name);openSheet(d,'Warm-up',`<p>Gespeicherte Warm-up-Historie für <strong>${esc(name)}</strong></p>${sets.length?sets.map(s=>`<div class="wo-history-row"><span>Warm-up</span><strong>${fmt(s.weight)} kg × ${s.reps}</strong></div>`).join(''):'<p>Noch keine Warm-up-Historie.</p>'}<p class="wo-sheet-note">Im aktuellen Training markierst du einen Satz mit <strong>W</strong>; Warm-up-Sätze zählen nicht für Coach und Progression.</p>`)}
function zoom(d,src){if(!src)return;const box=q('.wo-lightbox',ensureShell(d));q('img',box).src=src;box.classList.add('open')}

function renderTabs(d,shell){const all=items(d),active=activeIndex(d);q('.wo-tabs',shell).innerHTML=all.map((it,i)=>{const name=q('strong',it)?.textContent||`Übung ${i+1}`,done=it.classList.contains('completed'),skip=it.classList.contains('skipped'),started=!done&&!skip&&i===active&&engineRows(d).some(r=>['weight','reps','rir'].some(f=>String(engineField(r,f)?.value||'').trim()));return `<button class="wo-tab ${i===active?'active':''} ${done?'done':''} ${started?'started':''}" data-wo-tab="${i}"><b>${done?'✓':i+1}</b><span>${esc(name)}</span></button>`}).join('');qa('[data-wo-tab]',shell).forEach(b=>b.onclick=()=>items(d)[Number(b.dataset.woTab)]?.click());q('.wo-tab.active',shell)?.scrollIntoView({inline:'center',block:'nearest'})}
function variants(d){let buttons=engineVariants(d);if(!buttons.length){const name=currentDevice(d);return[{name,img:imgFor(name,currentVariantFallback(d)),active:true,present:present(name)}]}return buttons.map(btn=>{const name=variantName(btn);return{name,img:imgFor(name,q('img',btn)?.getAttribute('src')||''),active:btn.classList.contains('active'),present:present(name),engine:btn}}).filter(v=>v.present||v.active)}
function renderDevice(d){const name=currentDevice(d),vars=variants(d),h=historyFor(name),last=lastSet(name),pr=topSet(name),img=imgFor(name,currentVariantFallback(d));return `<section class="wo-card"><div class="wo-card-head"><small>GERÄT & ALTERNATIVEN</small><button type="button" data-wo-history>Verlauf</button></div><div class="wo-device-main"><img src="${esc(img)}" alt="${esc(name)}" data-wo-zoom><div><span class="wo-eyebrow">AKTIV</span><h2>${esc(name)}</h2><dl><dt>PR</dt><dd>${pr?`${fmt(pr.weight)} × ${pr.reps}${pr.rir==null?'':` · RIR ${pr.rir}`}`:'–'}</dd><dt>Zuletzt</dt><dd>${last?`${fmt(last.weight)} × ${last.reps}${last.rir==null?'':` · RIR ${last.rir}`} · ${esc(h?.date||'')}`:'–'}</dd><dt>Studio-Code</dt><dd>${esc(studioCode(name))}</dd></dl></div></div><div class="wo-variants">${vars.map((v,i)=>`<button class="wo-variant ${v.active?'active':''} ${v.present?'':'missing'}" data-wo-variant="${i}"><img src="${esc(v.img)}" alt=""><span><strong>${esc(v.name)}</strong><span>${v.present?(lastSet(v.name)?`Zuletzt ${fmt(lastSet(v.name).weight)} × ${lastSet(v.name).reps}${lastSet(v.name).rir==null?'':` · RIR ${lastSet(v.name).rir}`}`:'Noch keine Werte'):'Nicht im Studio'}</span></span></button>`).join('')}</div></section>`}
function renderCoach(d){const name=currentDevice(d),pr=topSet(name),last=lastSet(name),c=coach(name,d);return `<section class="wo-card"><div class="wo-card-head"><small>COACH · GERÄTESPEZIFISCH</small><button type="button" data-wo-coach>Details</button></div><div class="wo-coachbox"><span class="wo-eyebrow">GESAMTZIEL + PROGRESSION AN DIESEM GERÄT</span><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p></div><div class="wo-coachstats"><article><small>PR</small><strong>${pr?`${fmt(pr.weight)} × ${pr.reps}${pr.rir==null?'':` · RIR ${pr.rir}`}`:'–'}</strong></article><article><small>LETZTES MAL</small><strong>${last?`${fmt(last.weight)} × ${last.reps}${last.rir==null?'':` · RIR ${last.rir}`}`:'–'}</strong></article><article><small>NÄCHSTES ZIEL</small><strong>${esc(c.next)}</strong></article></div><div class="wo-chart">${chart(name)}</div></section>`}
function renderSets(d){const name=currentDevice(d),rows=engineRows(d);return `<section class="wo-card"><div class="wo-card-head"><small>ARBEITSSÄTZE</small><button type="button" data-wo-set-history>Verlauf</button></div><div class="wo-sets">${rows.map((row,i)=>{const s=suggestion(name,d,i),w=engineField(row,'weight')?.value||'',r=engineField(row,'reps')?.value||'',rir=engineField(row,'rir')?.value||'',warm=engineField(row,'warmup')?.checked;return `<div class="wo-set" data-wo-row="${i}"><span class="wo-setno">${i+1}</span><div class="wo-field"><label>kg</label><input inputmode="decimal" data-wo-field="weight" value="${esc(w)}" placeholder="${esc(s[0])}"></div><div class="wo-field"><label>Wdh.</label><input inputmode="numeric" data-wo-field="reps" value="${esc(r)}" placeholder="${esc(s[1])}"></div><div class="wo-field"><label>RIR</label><input inputmode="decimal" data-wo-field="rir" value="${esc(rir)}" placeholder="${esc(s[2])}"></div><button class="wo-apply" type="button" data-wo-apply title="Vorwerte übernehmen">↙</button><div class="wo-suggest">Coach-Vorschlag: ${s[0]===''?'neue Referenz':`${fmt(s[0])} kg · ${s[1]} Wdh. · RIR ${s[2]}`}</div><label class="wo-warm"><input type="checkbox" data-wo-warm ${warm?'checked':''}> W</label></div>`}).join('')}</div><div class="wo-set-actions"><button type="button" data-wo-remove>− Satz</button><button type="button" data-wo-add>+ Satz</button></div><div class="wo-warmup">Warm-up: ${warmSets(name).length?warmSets(name).map(s=>`${fmt(s.weight)} kg × ${s.reps}`).join(' | '):'noch nicht gespeichert'} <button type="button" data-wo-warm-history>ändern</button></div><div class="wo-wide"><button type="button" data-wo-info>Info</button><button type="button" data-wo-extra>+ Übung</button></div><button class="wo-complete" type="button" data-wo-complete>Übung abschließen</button></section>`}
function renderPage(d,shell){const idx=activeIndex(d),name=exerciseName(d),target=targetText(d);q('.wo-page',shell).innerHTML=`<header class="wo-hero"><div><span class="wo-eyebrow">ÜBUNG ${idx+1} VON ${items(d).length}</span><h1>${esc(name)}</h1><p>${esc(target)}</p></div></header>${renderDevice(d)}${renderCoach(d)}${renderSets(d)}`;bindPage(d,shell)}
function syncField(d,rowIndex,field,value,checked=false){const row=engineRows(d)[rowIndex],el=engineField(row,field);if(!el)return;if(field==='warmup')el.checked=checked;else el.value=value;el.dispatchEvent(new Event(field==='warmup'?'change':'input',{bubbles:true}))}
function bindPage(d,shell){const page=q('.wo-page',shell);q('[data-wo-history]',page)?.addEventListener('click',()=>openHistory(d,currentDevice(d)));q('[data-wo-set-history]',page)?.addEventListener('click',()=>openHistory(d,currentDevice(d)));q('[data-wo-coach]',page)?.addEventListener('click',()=>openHistory(d,currentDevice(d)));q('[data-wo-zoom]',page)?.addEventListener('click',e=>zoom(d,e.currentTarget.src));qa('[data-wo-variant]',page).forEach(b=>b.onclick=()=>{const v=variants(d)[Number(b.dataset.woVariant)];if(v?.engine)v.engine.click()});qa('[data-wo-row]',page).forEach(set=>{const i=Number(set.dataset.woRow);qa('[data-wo-field]',set).forEach(inp=>inp.oninput=()=>syncField(d,i,inp.dataset.woField,inp.value));q('[data-wo-warm]',set).onchange=e=>syncField(d,i,'warmup','',e.target.checked);q('[data-wo-apply]',set).onclick=()=>{const s=suggestion(currentDevice(d),d,i);if(s[0]==='')return;syncField(d,i,'weight',s[0]);syncField(d,i,'reps',s[1]);syncField(d,i,'rir',String(s[2]).split('–')[0]);setTimeout(()=>schedule(40),20)}});q('[data-wo-add]',page)?.addEventListener('click',()=>q('[data-add-set-v53]',detail(d))?.click());q('[data-wo-remove]',page)?.addEventListener('click',()=>q('[data-remove-set-v53]',detail(d))?.click());q('[data-wo-warm-history]',page)?.addEventListener('click',()=>openWarm(d,currentDevice(d)));q('[data-wo-extra]',page)?.addEventListener('click',()=>q('#add-exercise-v54',d)?.click());q('[data-wo-info]',page)?.addEventListener('click',()=>openHistory(d,currentDevice(d)));q('[data-wo-complete]',page)?.addEventListener('click',()=>q('[data-status-v53="completed"]',detail(d))?.click());}
function bindSwipe(d,shell){if(shell.dataset.swipe==='1')return;shell.dataset.swipe='1';const page=q('.wo-page',shell);page.addEventListener('touchstart',e=>{if(e.target.closest('.wo-variants,input,button')){startX=0;return}startX=e.touches[0].clientX;startY=e.touches[0].clientY},{passive:true});page.addEventListener('touchend',e=>{if(!startX)return;const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;startX=0;if(Math.abs(dx)<75||Math.abs(dx)<=Math.abs(dy)*1.2)return;(dx<0?q('[data-next-ex-v53]',detail(d)):q('[data-prev-ex-v53]',detail(d)))?.click()},{passive:true})}
function render(){const d=q('#workout-dialog');if(!d?.open)return;const eng=engine(d);if(!eng||!items(d).length||!detail(d))return;const shell=ensureShell(d);d.classList.add('workout-approved');eng.classList.add('wo-engine');q('.wo-heading strong',shell).textContent=q('#dialog-title',d)?.textContent||'Training';q('.wo-timer span',shell).textContent=q('#workout-timer',d)?.textContent||'00:00';q('.wo-timer small',shell).textContent=q('#timer-toggle',d)?.textContent||'Training starten';renderTabs(d,shell);renderPage(d,shell);const idx=activeIndex(d);q('.wo-prev',shell).disabled=idx===0;q('.wo-next',shell).disabled=idx===items(d).length-1;bindSwipe(d,shell)}
function connect(){const d=q('#workout-dialog'),eng=engine(d);if(!eng)return;observer??=new MutationObserver(()=>schedule(35));observer.disconnect();observer.observe(eng,{subtree:true,childList:true,attributes:true,characterData:true})}
function install(){const d=q('#workout-dialog');d?.addEventListener('toggle',()=>{if(d.open){[20,80,180].forEach(schedule);setTimeout(connect,200)}});document.addEventListener('click',e=>{if(e.target.closest('[data-workout],#start-workout,#timer-toggle,[data-select-ex-v53],[data-prev-ex-v53],[data-next-ex-v53],[data-variant-prev-v53],[data-variant-next-v53],[data-add-set-v53],[data-remove-set-v53],[data-status-v53],#order-toggle-v53,[data-order-up-v53],[data-order-down-v53],#add-exercise-v54'))schedule(50)},true);if(d?.open){schedule();connect()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
