const q=(s,r=document)=>r.querySelector(s);
const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const HISTORY='gym-v55-device-history';
const STUDIO='gym-studio-profile-v35';
const EDIT='gym-v53-edit';
const ACTIVE='gym-active-workout-v11';
let observer=null,scheduled=false,startX=0,startY=0;

const canon=v=>String(v||'').toLowerCase().replaceAll('ä','a').replaceAll('ö','o').replaceAll('ü','u').replaceAll('ß','ss').replace(/[^a-z0-9]+/g,' ').trim();
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
const fmt=v=>num(v)==null?'–':num(v).toLocaleString('de-DE',{maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const IMG={
 'bauchmuskelmaschine':'IMG_3040.png','bauchmuskelmaschine crunch liegend':'IMG_3041.png','klappsitz bauchmaschine sitzend':'IMG_3042.png','klappsitz bauchmaschine liegend plate loaded':'IMG_3043.png','bizepsmaschine':'IMG_3044.png','bizepsmaschine plate loaded':'IMG_3045.png','scott curler sitzend':'IMG_3046.png','brustpresse sitzend':'IMG_3047.png','bankdruckmaschine sitzend dual':'IMG_3048.png','bankdruckmaschine liegend dual':'IMG_3049.png','butterfly mit griffen':'pics_johnreed/IMG_3452.jpeg','butterfly mit pads':'IMG_3051.png','schragbankdruckmaschine dual':'IMG_3062.png','schragbankmaschine sitzend':'IMG_3063.png','seithebemaschine ohne armpolster':'IMG_3064.png','seithebemaschine dual ohne armpolster':'IMG_3065.png','trizepsmaschine uber kopf':'IMG_3066.png','trizepsmaschine horizontal':'IMG_3067.png','trizeps dip maschine sitzend dual':'IMG_3068.png','kurzhantel seitheben sitzend':'IMG_3069.png','kurzhantel seitheben stehend':'IMG_3070.png','kurzhantel schragbankdrucken':'IMG_3071.png'
};

function historyFor(name){const all=read(HISTORY,{}),key=canon(name);return all[name]||Object.entries(all).find(([n])=>canon(n)===key)?.[1]||null}
function workSets(name){return (historyFor(name)?.sets||[]).filter(s=>!s.warmup&&num(s.weight)!=null&&num(s.reps)!=null)}
function warmSets(name){return (historyFor(name)?.sets||[]).filter(s=>s.warmup&&num(s.weight)!=null&&num(s.reps)!=null)}
function lastSet(name){return workSets(name).at(-1)||null}
function topSet(name){const sets=workSets(name);if(!sets.length)return null;return sets.reduce((a,b)=>num(b.weight)>num(a.weight)||(num(b.weight)===num(a.weight)&&num(b.reps)>num(a.reps))?b:a)}
function previousSet(name,index){return workSets(name)[index]||null}
function studioEntry(name){const p=read(STUDIO,read('gym-studio-profile-v32',{studio:'John Reed Essen',devices:{}}));return Object.entries(p?.devices||{}).find(([n])=>canon(n)===canon(name))?.[1]||null}
function present(name){const key=canon(name),profile=read(STUDIO,read('gym-studio-profile-v32',{studio:'John Reed Essen',devices:{}})),studio=canon(profile?.studio||'John Reed Essen');if(studio==='john reed essen'&&(key==='butterfly mit pads'||key==='butterfly reverse mit pads'))return false;return studioEntry(name)?.present!=='no'}
function studioCode(name){const e=studioEntry(name);return e?.code||e?.number||e?.device_code||'–'}
function imgFor(name,fallback=''){return IMG[canon(name)]||fallback||''}

function engine(d){return q('#exercise-list',d)}
function items(d){return qa('#exercise-list [data-select-ex-v53]',d)}
function activeIndex(d){const all=items(d),i=all.findIndex(x=>x.classList.contains('active'));return i<0?0:i}
function detail(d){return q('#exercise-list .training-exercise-v53',d)}
function exerciseName(d){return q('.exercise-title-v53 h3',detail(d))?.textContent?.trim()||q('strong',items(d)[activeIndex(d)])?.textContent?.trim()||'Übung'}
function targetText(d){return q('.exercise-title-v53 p',detail(d))?.textContent?.trim()||''}
function currentDevice(d){return q('.device-nav-v53 strong',detail(d))?.textContent?.trim()||exerciseName(d)}
function engineRows(d){return qa('.set-row-v53',detail(d))}
function engineField(row,name){return q(`[data-field-v53="${name}"]`,row)}
function engineVariants(d){return qa('.device-history-v55 button',detail(d))}
function variantName(btn){return q('strong',btn)?.textContent?.trim()||''}
function currentVariantFallback(d){return q('.device-image-v53 img',detail(d))?.getAttribute('src')||''}
function targetRange(d){const text=targetText(d),m=text.match(/(\d+)\s*Arbeitssätze.*?(\d+)\s*[–-]\s*(\d+).*?RIR\s*([0-9–-]+)/i);return{sets:m?Number(m[1]):Math.max(2,engineRows(d).length),min:m?Number(m[2]):6,max:m?Number(m[3]):12,rir:m?.[4]||'1–2'}}
function compound(name){return /(schragbank|bankdruck|brustpresse|latzug|ruckenzug|rudermaschine|low row|high row)/.test(canon(name))}

function coach(name,d){
  const range=targetRange(d),last=lastSet(name);
  if(!last)return{title:'Neue Gerätereferenz setzen',text:`Wähle ein Gewicht für ${range.min}–${range.max} saubere Wiederholungen. Starte mit ${range.sets} Arbeitssätzen bei ungefähr RIR ${range.rir}.`,next:'–',sets:range.sets,targetRir:range.rir,targetReps:range.min};
  const kg=num(last.weight),reps=num(last.reps),rir=num(last.rir),isCompound=compound(name);
  let target=Math.min(range.max,reps+1),sets=range.sets,targetRir=range.rir,text='';
  if(isCompound&&rir!=null&&rir<=0){sets=Math.min(2,range.sets);targetRir='0–1';text=`${fmt(kg)} kg beibehalten. Heute ${sets} sehr harte Arbeitssätze: Satz 1 etwa RIR 1, der letzte Satz bis RIR 0–1. Mehr Volumen ist hier nicht automatisch besser, wenn die Satzqualität bereits maximal ist.`}
  else if(isCompound&&rir===1){sets=Math.min(3,range.sets);targetRir='1';text=`${fmt(kg)} kg beibehalten. ${sets} harte Arbeitssätze. Ziel: zuerst ${target} saubere Wiederholungen; der letzte Satz darf bei stabiler Technik bis RIR 0–1 gehen.`}
  else if(rir!=null&&rir>=3){target=Math.max(range.min,reps-1);targetRir=range.rir;text=`${fmt(kg)} kg waren deutlich unter deinem Limit. Nimm den nächsten sinnvollen Geräteschritt und bleibe mit ${range.sets} Arbeitssätzen im Zielbereich ${range.min}–${range.max}.`}
  else{text=`${fmt(kg)} kg beibehalten. Ziel heute: ${target} saubere Wiederholungen. Bei Isolationsübungen kann der letzte Satz bei sauberer Technik bis RIR 0 gehen.`}
  return{title:`${fmt(kg)} kg · Ziel ${target}`,text,next:`${fmt(kg)} × ${target}`,sets,targetRir,targetReps:target};
}
function suggestion(name,d,rowIndex){const c=coach(name,d),last=lastSet(name);if(!last)return['','',''];const kg=num(last.weight),reps=Math.max(1,c.targetReps-Math.max(0,rowIndex)),rir=rowIndex===c.sets-1&&c.targetRir==='0–1'?0:String(c.targetRir).split('–')[0];return[kg,reps,rir]}

function chart(name){const h=historyFor(name),sets=workSets(name);if(!sets.length)return'<p class="wo-empty">Noch kein Verlauf an diesem Gerät.</p>';const vals=sets.map((s,i)=>({kg:num(s.weight),date:h?.date||'',i})),kgs=vals.map(v=>v.kg),min=Math.max(0,Math.min(...kgs)-5),max=Math.max(...kgs)+5,span=Math.max(1,max-min),x=i=>42+i*(240/Math.max(1,vals.length-1)),y=kg=>92-(kg-min)/span*68,pts=vals.map(v=>`${x(v.i)},${y(v.kg)}`).join(' ');return `<svg viewBox="0 0 310 125"><line x1="40" y1="12" x2="40" y2="96"/><line x1="40" y1="96" x2="292" y2="96"/><text x="4" y="18">${max} kg</text><text x="8" y="96">${min} kg</text><polyline points="${pts}"/>${vals.map(v=>`<circle cx="${x(v.i)}" cy="${y(v.kg)}" r="4"/>`).join('')}<text x="112" y="116">${esc(h?.date||'Training')}</text><text x="6" y="62" transform="rotate(-90 12 62)">Arbeitsgewicht</text></svg>`}

function schedule(ms=0){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;render()},ms)}
function ensureModal(){let m=q('#wo-modal');if(m)return m;m=document.createElement('dialog');m.id='wo-modal';m.className='wo-modal';m.innerHTML='<div class="wo-modal-card"><header><h2></h2><button type="button" data-wo-modal-close>Schließen</button></header><div class="wo-modal-body"></div></div>';document.body.append(m);q('[data-wo-modal-close]',m).onclick=()=>m.close();return m}
function openModal(title,html,bind){const m=ensureModal();q('h2',m).textContent=title;q('.wo-modal-body',m).innerHTML=html;if(!m.open)m.showModal();bind?.(m)}
function ensureShell(d){
  let shell=q('.wo-app',d);if(shell)return shell;
  shell=document.createElement('div');shell.className='wo-app';shell.innerHTML='<header class="wo-top"><button class="wo-close" type="button">×</button><div class="wo-heading"><small>TRAINING HEUTE</small><strong></strong></div><button class="wo-timer" type="button"><span>00:00</span><small>Training starten</small></button></header><nav class="wo-tabs"></nav><main class="wo-page"></main><nav class="wo-bottom"><button class="wo-prev" type="button">‹ Vorherige</button><button class="wo-menu" type="button">☷</button><button class="wo-next" type="button">Nächste ›</button></nav>';
  d.append(shell);q('.wo-close',shell).onclick=()=>q('#close-dialog',d)?.click();q('.wo-timer',shell).onclick=()=>q('#timer-toggle',d)?.click();q('.wo-prev',shell).onclick=()=>{q('[data-prev-ex-v53]',detail(d))?.click();setTimeout(()=>render(true),40)};q('.wo-next',shell).onclick=()=>{q('[data-next-ex-v53]',detail(d))?.click();setTimeout(()=>render(true),40)};q('.wo-menu',shell).onclick=()=>openOrder(d);return shell;
}

function openOrder(d){
  const toggle=q('#order-toggle-v53',d);if(toggle&&!q('[data-order-up-v53]',d))toggle.click();
  setTimeout(()=>{
    const all=items(d);
    openModal('Übungsübersicht',all.map((it,i)=>`<div class="wo-order"><b>${i+1}</b><strong>${esc(q('strong',it)?.textContent||`Übung ${i+1}`)}</strong><div><button data-wo-up="${i}">↑</button><button data-wo-down="${i}">↓</button></div></div>`).join('')+'<button class="wo-modal-action" data-wo-add-ex>+ Übung hinzufügen</button><button class="wo-modal-secondary" data-wo-finish-order>Reihenfolge übernehmen</button>',m=>{
      qa('[data-wo-up]',m).forEach(b=>b.onclick=()=>{q(`[data-order-up-v53="${b.dataset.woUp}"]`,d)?.click();setTimeout(()=>{m.close();openOrder(d)},80)});
      qa('[data-wo-down]',m).forEach(b=>b.onclick=()=>{q(`[data-order-down-v53="${b.dataset.woDown}"]`,d)?.click();setTimeout(()=>{m.close();openOrder(d)},80)});
      q('[data-wo-add-ex]',m).onclick=()=>{m.close();q('#add-exercise-v54',d)?.click()};
      q('[data-wo-finish-order]',m).onclick=()=>{q('#order-toggle-v53',d)?.click();m.close();setTimeout(()=>render(true),60)};
    });
  },70);
}
function openHistory(name){const h=historyFor(name),sets=workSets(name);openModal(`Verlauf · ${name}`,sets.length?sets.map((s,i)=>`<div class="wo-history-row"><span>Satz ${i+1}</span><strong>${fmt(s.weight)} kg × ${s.reps}</strong><span>${s.rir==null?'':`RIR ${s.rir}`}</span></div>`).join('')+`<p class="wo-history-date">Letzter gespeicherter Trainingstag: ${esc(h?.date||'–')}</p>`:'<p>Noch keine gespeicherten Werte an diesem Gerät.</p>')}
function openWarm(d,name){const sets=warmSets(name);openModal('Warm-up',`<p>Gespeicherte Warm-up-Historie für <strong>${esc(name)}</strong></p>${sets.length?sets.map(s=>`<div class="wo-history-row"><span>Warm-up</span><strong>${fmt(s.weight)} kg × ${s.reps}</strong></div>`).join(''):'<p>Noch keine Warm-up-Historie.</p>'}<p class="wo-modal-note">Warm-up zählt nicht für Coach oder Progression.</p><button class="wo-modal-action" data-wo-add-warm>Warm-up-Satz hinzufügen</button>`,m=>{q('[data-wo-add-warm]',m).onclick=()=>{q('[data-add-set-v53]',detail(d))?.click();setTimeout(()=>{const rows=engineRows(d),row=rows.at(-1);if(row){const w=engineField(row,'warmup');if(w){w.checked=true;w.dispatchEvent(new Event('change',{bubbles:true}))}}m.close();render(true)},80)}})}
function openInfo(d,name){const c=coach(name,d),range=targetRange(d);openModal(`Info · ${exerciseName(d)}`,`<p><strong>Zielbereich:</strong> ${range.min}–${range.max} Wiederholungen</p><p><strong>Aktuelles Gerät:</strong> ${esc(name)}</p><p><strong>Studio-Code:</strong> ${esc(studioCode(name))}</p><p><strong>Coach:</strong> ${esc(c.text)}</p><p><strong>Empfohlene Arbeitssätze heute:</strong> ${c.sets}</p><p><strong>Ziel-RIR:</strong> ${esc(c.targetRir)}</p>`)}
function zoom(src){if(!src)return;openModal('Gerätebild',`<img class="wo-modal-image" src="${esc(src)}" alt="Gerätebild">`)}

function renderTabs(d,shell,force=false){
  const all=items(d),active=activeIndex(d),signature=all.map((it,i)=>`${q('strong',it)?.textContent}|${it.className}|${i}`).join('§');
  const tabs=q('.wo-tabs',shell),oldScroll=tabs.scrollLeft;
  if(force||tabs.dataset.signature!==signature){tabs.dataset.signature=signature;tabs.innerHTML=all.map((it,i)=>{const name=q('strong',it)?.textContent||`Übung ${i+1}`,done=it.classList.contains('completed'),skip=it.classList.contains('skipped');return `<button class="wo-tab ${i===active?'active':''} ${done?'done':''} ${skip?'skipped':''}" data-wo-tab="${i}"><b>${done?'✓':i+1}</b><span>${esc(name)}</span></button>`}).join('');qa('[data-wo-tab]',tabs).forEach(b=>b.onclick=()=>{items(d)[Number(b.dataset.woTab)]?.click();setTimeout(()=>render(true),40)});tabs.scrollLeft=oldScroll}
  qa('.wo-tab',tabs).forEach((b,i)=>b.classList.toggle('active',i===active));
  if(shell.dataset.active!==String(active)){shell.dataset.active=String(active);q(`.wo-tab[data-wo-tab="${active}"]`,tabs)?.scrollIntoView({inline:'nearest',block:'nearest',behavior:'smooth'})}
}
function variants(d){const buttons=engineVariants(d);if(!buttons.length){const name=currentDevice(d);return[{name,img:imgFor(name,currentVariantFallback(d)),active:true,present:present(name)}]}return buttons.map(btn=>{const name=variantName(btn);return{name,img:imgFor(name,q('img',btn)?.getAttribute('src')||''),active:btn.classList.contains('active'),present:present(name),engine:btn}}).filter(v=>v.present||v.active)}
function renderDevice(d){const name=currentDevice(d),vars=variants(d),h=historyFor(name),last=lastSet(name),pr=topSet(name),img=imgFor(name,currentVariantFallback(d));return `<section class="wo-card"><div class="wo-card-head"><small>GERÄT & ALTERNATIVEN</small><button type="button" data-wo-history>Verlauf</button></div><div class="wo-device-main"><img src="${esc(img)}" alt="${esc(name)}" data-wo-zoom><div><span class="wo-eyebrow">AKTIV</span><h2>${esc(name)}</h2><dl><dt>PR</dt><dd>${pr?`${fmt(pr.weight)} × ${pr.reps}${pr.rir==null?'':` · RIR ${pr.rir}`}`:'–'}</dd><dt>Zuletzt</dt><dd>${last?`${fmt(last.weight)} × ${last.reps}${last.rir==null?'':` · RIR ${last.rir}`} · ${esc(h?.date||'')}`:'–'}</dd><dt>Studio-Code</dt><dd>${esc(studioCode(name))}</dd></dl></div></div><div class="wo-variants">${vars.map((v,i)=>`<button class="wo-variant ${v.active?'active':''}" data-wo-variant="${i}"><img src="${esc(v.img)}" alt=""><span><strong>${esc(v.name)}</strong><span>${lastSet(v.name)?`Zuletzt ${fmt(lastSet(v.name).weight)} × ${lastSet(v.name).reps}${lastSet(v.name).rir==null?'':` · RIR ${lastSet(v.name).rir}`}`:'Noch keine Werte'}</span></span></button>`).join('')}</div></section>`}
function renderCoach(d){const name=currentDevice(d),pr=topSet(name),last=lastSet(name),c=coach(name,d);return `<section class="wo-card"><div class="wo-card-head"><small>COACH · GERÄTESPEZIFISCH</small><button type="button" data-wo-info>Info</button></div><div class="wo-coachbox"><span class="wo-eyebrow">GESAMTZIEL + PROGRESSION AN DIESEM GERÄT</span><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p></div><div class="wo-coachstats"><article><small>PR</small><strong>${pr?`${fmt(pr.weight)} × ${pr.reps}${pr.rir==null?'':` · RIR ${pr.rir}`}`:'–'}</strong></article><article><small>LETZTES MAL</small><strong>${last?`${fmt(last.weight)} × ${last.reps}${last.rir==null?'':` · RIR ${last.rir}`}`:'–'}</strong></article><article><small>HEUTE</small><strong>${c.sets} Sätze · RIR ${esc(c.targetRir)}</strong></article></div><div class="wo-chart">${chart(name)}</div></section>`}
function renderSets(d){const name=currentDevice(d),rows=engineRows(d),c=coach(name,d);return `<section class="wo-card"><div class="wo-card-head"><small>ARBEITSSÄTZE</small><button type="button" data-wo-history>Verlauf</button></div><div class="wo-sets">${rows.map((row,i)=>{const s=suggestion(name,d,i),prev=previousSet(name,i),w=engineField(row,'weight')?.value||'',r=engineField(row,'reps')?.value||'',rir=engineField(row,'rir')?.value||'',warm=engineField(row,'warmup')?.checked;return `<div class="wo-set" data-wo-row="${i}"><span class="wo-setno">${i+1}</span><div class="wo-field"><label>kg</label><input inputmode="decimal" data-wo-field="weight" value="${esc(w)}" placeholder="${esc(s[0])}"></div><div class="wo-field"><label>Wdh.</label><input inputmode="numeric" data-wo-field="reps" value="${esc(r)}" placeholder="${esc(s[1])}"></div><div class="wo-field"><label>RIR</label><input inputmode="decimal" data-wo-field="rir" value="${esc(rir)}" placeholder="${esc(s[2])}"></div><button class="wo-previous" type="button" data-wo-previous ${prev?'':'disabled'}>Vorwerte</button><div class="wo-suggest">Coach: ${s[0]===''?'neue Referenz':`${fmt(s[0])} kg · ${s[1]} Wdh. · RIR ${s[2]}`} <button type="button" data-wo-coach-apply>Übernehmen</button></div><label class="wo-warm"><input type="checkbox" data-wo-warm ${warm?'checked':''}> W</label></div>`}).join('')}</div><div class="wo-set-actions"><button type="button" data-wo-remove>− Satz</button><button type="button" data-wo-add>+ Satz</button></div><button class="wo-set-count" type="button" data-wo-set-count>${c.sets} Coach-Sätze übernehmen</button><div class="wo-warmup">Warm-up: ${warmSets(name).length?warmSets(name).map(s=>`${fmt(s.weight)} kg × ${s.reps}`).join(' | '):'noch nicht gespeichert'} <button type="button" data-wo-warm-history>ändern</button></div><div class="wo-wide"><button type="button" data-wo-info>Info</button><button type="button" data-wo-extra>+ Übung</button></div><button class="wo-complete" type="button" data-wo-complete>Übung abschließen</button></section>`}
function renderPage(d,shell){const appScroll=shell.scrollTop,variantScroll=q('.wo-variants',shell)?.scrollLeft||0,idx=activeIndex(d),name=exerciseName(d),target=targetText(d);q('.wo-page',shell).innerHTML=`<header class="wo-hero"><div><span class="wo-eyebrow">ÜBUNG ${idx+1} VON ${items(d).length}</span><h1>${esc(name)}</h1><p>${esc(target)}</p></div></header>${renderDevice(d)}${renderCoach(d)}${renderSets(d)}`;bindPage(d,shell);shell.scrollTop=appScroll;const variantsEl=q('.wo-variants',shell);if(variantsEl)variantsEl.scrollLeft=variantScroll}
function syncField(d,rowIndex,field,value,checked=false){const row=engineRows(d)[rowIndex],el=engineField(row,field);if(!el)return;if(field==='warmup')el.checked=checked;else el.value=value;el.dispatchEvent(new Event(field==='warmup'?'change':'input',{bubbles:true}))}
function applyValues(d,i,values){if(!values)return;syncField(d,i,'weight',values[0]);syncField(d,i,'reps',values[1]);syncField(d,i,'rir',values[2]??'');}
function adjustSetCount(d,count){let rows=engineRows(d);while(rows.length<count){q('[data-add-set-v53]',detail(d))?.click();rows=engineRows(d)}while(rows.length>count){q('[data-remove-set-v53]',detail(d))?.click();rows=engineRows(d)}setTimeout(()=>render(true),70)}
function bindPage(d,shell){
  const page=q('.wo-page',shell);qa('[data-wo-history]',page).forEach(b=>b.onclick=()=>openHistory(currentDevice(d)));qa('[data-wo-info]',page).forEach(b=>b.onclick=()=>openInfo(d,currentDevice(d)));q('[data-wo-zoom]',page)?.addEventListener('click',e=>zoom(e.currentTarget.src));
  qa('[data-wo-variant]',page).forEach(b=>b.onclick=()=>{const v=variants(d)[Number(b.dataset.woVariant)];if(v?.engine){v.engine.click();setTimeout(()=>render(true),60)}});
  qa('[data-wo-row]',page).forEach(set=>{const i=Number(set.dataset.woRow);qa('[data-wo-field]',set).forEach(inp=>inp.oninput=()=>syncField(d,i,inp.dataset.woField,inp.value));q('[data-wo-warm]',set).onchange=e=>syncField(d,i,'warmup','',e.target.checked);q('[data-wo-previous]',set).onclick=()=>{const p=previousSet(currentDevice(d),i);if(p)applyValues(d,i,[p.weight,p.reps,p.rir??''])};q('[data-wo-coach-apply]',set).onclick=()=>applyValues(d,i,suggestion(currentDevice(d),d,i))});
  q('[data-wo-add]',page)?.addEventListener('click',()=>{q('[data-add-set-v53]',detail(d))?.click();setTimeout(()=>render(true),60)});q('[data-wo-remove]',page)?.addEventListener('click',()=>{q('[data-remove-set-v53]',detail(d))?.click();setTimeout(()=>render(true),60)});q('[data-wo-set-count]',page)?.addEventListener('click',()=>adjustSetCount(d,coach(currentDevice(d),d).sets));q('[data-wo-warm-history]',page)?.addEventListener('click',()=>openWarm(d,currentDevice(d)));q('[data-wo-extra]',page)?.addEventListener('click',()=>q('#add-exercise-v54',d)?.click());q('[data-wo-complete]',page)?.addEventListener('click',()=>q('[data-status-v53="completed"]',detail(d))?.click());
}
function bindSwipe(d,shell){if(shell.dataset.swipe==='1')return;shell.dataset.swipe='1';const page=q('.wo-page',shell);page.addEventListener('touchstart',e=>{if(e.target.closest('.wo-variants,input,button,.wo-set')){startX=0;return}startX=e.touches[0].clientX;startY=e.touches[0].clientY},{passive:true});page.addEventListener('touchend',e=>{if(!startX)return;const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;startX=0;if(Math.abs(dx)<90||Math.abs(dx)<=Math.abs(dy)*1.5)return;(dx<0?q('[data-next-ex-v53]',detail(d)):q('[data-prev-ex-v53]',detail(d)))?.click();setTimeout(()=>render(true),60)},{passive:true})}
function clearLegacyPrefill(d){
  if(read(EDIT,null))return;const active=read(ACTIVE,{}),key=`gym-workout-cleared:${active?.code||q('#dialog-title',d)?.textContent||'x'}:${active?.date||active?.workout_date||new Date().toISOString().slice(0,10)}`;if(sessionStorage.getItem(key)==='1')return;
  const timer=q('#workout-timer',d)?.textContent?.trim();if(timer&&timer!=='00:00')return;
  engineRows(d).forEach(row=>{['weight','reps','rir'].forEach(f=>{const el=engineField(row,f);if(el&&el.value){el.value='';el.dispatchEvent(new Event('input',{bubbles:true}))}});const w=engineField(row,'warmup');if(w?.checked){w.checked=false;w.dispatchEvent(new Event('change',{bubbles:true}))}});sessionStorage.setItem(key,'1');
}
function render(force=false){const d=q('#workout-dialog');if(!d?.open)return;const eng=engine(d);if(!eng||!items(d).length||!detail(d))return;const shell=ensureShell(d);clearLegacyPrefill(d);d.classList.add('workout-approved');eng.classList.add('wo-engine');q('.wo-heading strong',shell).textContent=q('#dialog-title',d)?.textContent||'Training';q('.wo-timer span',shell).textContent=q('#workout-timer',d)?.textContent||'00:00';q('.wo-timer small',shell).textContent=q('#timer-toggle',d)?.textContent||'Training starten';renderTabs(d,shell,force);renderPage(d,shell);const idx=activeIndex(d);q('.wo-prev',shell).disabled=idx===0;q('.wo-next',shell).disabled=idx===items(d).length-1;bindSwipe(d,shell)}
function connect(){const d=q('#workout-dialog'),eng=engine(d);if(!eng)return;observer??=new MutationObserver(muts=>{if(muts.some(m=>m.type==='childList'))schedule(50)});observer.disconnect();observer.observe(eng,{subtree:true,childList:true})}
function install(){const d=q('#workout-dialog');d?.addEventListener('toggle',()=>{if(d.open){[30,100,220,450].forEach(ms=>setTimeout(()=>render(true),ms));setTimeout(connect,250)}});document.addEventListener('click',e=>{if(e.target.closest('[data-workout],#start-workout'))[80,180,350].forEach(ms=>setTimeout(()=>render(true),ms))},true);if(d?.open){render(true);connect()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();